### ISSUE TITLE
[Decorator] Response formatting

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#10]
`@ResponseSet(headers)` let you to configure response header from annotation.

```typescript
@Controller("/calendars")
export class CalendarCtrl {

    @Get("/:id")
    @ResponseSet({"Content-Type": "application/json", status: 200})
    public get(): ICalendar {

        return <ICalendar> {id: request.params.id, name: "test"};
    }
// or
    @Get("/:id")
    @ResponseSet("Content-Type",  "application/json")
    @ResponseSet("status",  200)
    public get(): ICalendar {

        return <ICalendar> {id: request.params.id, name: "test"};
    }
}
```

Annotation's name is a proposal. If you have a better idea of name, tell-it !

**Comment by alexproca** [comment]
Name proposal :)

Why not name it simply `@Headers({ "Content-Type": "application/json", "X-Foo": "Bar" })` or `@ResponseHeaders()`

**Comment by Romakita** [comment]
ResponseSet just because I use `response.set` method :)
But `ResponseHeaders` is fine.
`Headers` is too confusing between headers sent with the request and the headers sent on the response.

**Comment by Romakita** [comment]
#30
