### ISSUE TITLE
Become Reviewers and/or Contributors

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#102]
Hi all,

Actually, the project Ts.ED growth and the code too. To ensure a good level of quality, we have set up Gitflow which is used on many projects. But that it is effective, we need contributors to review the code we produce. 
Is not a big or hard work, but if you like this project you can bring enormously to the project, just with the code review. Your opinion is important and will be considered!

So if you want to contribute as reviewer or contributor, just reply a message in this issues!

Your are welcome :D
See you,
Romain

**Comment by myfingersarebroken** [comment]
Hi, I wanna become a contributor

**Comment by Romakita** [comment]
Nice :)

**Comment by milewski** [comment]
i would like to i really like typescript.. and am also kind of opensourcer ( if you check my repos everything is in typescript :D ) .. i'm just very afraid of semicolons and double quotes hahah if there are something pending let me know

**Comment by Romakita** [comment]
- @milewski: Simple feature to begin https://github.com/Romakita/ts-express-decorators/issues/243

**Comment by milewski** [comment]
@Romakita is there a private slack channel or something?

**Comment by Romakita** [comment]
@milewski No. I already try to create a slack channel for this project, but I'm never connected at the right time.  Finally, issue in github let me the time to answer.

**Comment by mikerhyssmith** [comment]
Hi @Romakita, love tsed!  Would be happy to contribute to any issues that you want having a look at ?

**Comment by Romakita** [comment]
@mikerhyssmith You are welcome :)
Actually one of the issue is related to Swagger documentation #298 

The problem come from the switch case here: https://github.com/Romakita/ts-express-decorators/blob/master/src/swagger/class/OpenApiParamsBuilder.ts#L64

**Comment by mikerhyssmith** [comment]
@Romakita Thanks ! I will take a look at that issue tomorrow 🙂
