### ISSUE TITLE
Controller methods respond with 404 if a Promise resolving with no data is returned 

### ISSUE THREAD

**Issue by m0uneer** [Romakita/ts-express-decorators#104]
Hi Romain,

Code example:
```javascript
Class Ctrl {
  method() {  // Responding with 404
     return Promise.resolve();
  }
}
```

I wonder if there is a reason for this behavior? I think a 200 O.K would be more intuitive.

Thanks for your continuous support :)

**Comment by Romakita** [comment]
Hi @m0uneer,

Unfortunately, I can't do that. When I've solve the problem for the issue #29, I had to make a technical choice to conciliate multiple endpoints for the same routes, solve the twice calling bug and allow classic express call and decorators call. So to send a response I need a value to send a response. 

You can find the code that handle all middleware and endpoints:
https://github.com/Romakita/ts-express-decorators/blob/production/src/mvc/class/HandlerBuilder.ts#L129-L184
https://github.com/Romakita/ts-express-decorators/blob/production/src/mvc/components/SendResponseMiddleware.ts

If you find a better solution, I'll take it ;). I looked for several solutions and it is the only one that seems to work well.

See you, 
Romain

**Comment by m0uneer** [comment]
Thanks Romain for explaining this to me. I'll return something, for now, to respond with a 200. Also, thanks for inviting me to check the code and I'll investigate this soon. Hopefully, we can find a better solution :)
