### ISSUE TITLE
Mounting controllers for a bundled server with fuse-box

### ISSUE THREAD

**Issue by jperezdavinchi** [Romakita/ts-express-decorators#107]
Hi there,
thanks for your amazing work!.
I'm trying to use fusebox to bundle and minify the code.
I already prepared the environment and the bundling works fine.
The problems come in the runtime with the configuration, the property "mount" of the server must be the files to load as controllers, but in this case, the controllers are in the same file as the server.
I tried pointing "mount" to the bundled file but it doesn't work.
Is there another way to load the controllers and the services? For example, providing the class instead of the path to the file

Something like:
```typescript
import {GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings} from "ts-express-decorators";
import {$log} from "ts-log-debug";
import Path = require("path");
const rootDir = Path.resolve(__dirname);
import {RestCtrl} from "./controllers/RestCtrl";
@ServerSettings({
    rootDir,
    mount: {
        '/rest': RestCtrl
    },
    acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
}
```
Can someone help me?
Thank you!

**Comment by Romakita** [comment]
Hi @jperezdavinchi ,

Actually, is not possible to do that, but I think it's possible to create this new feature easily.

The method concerned is this one:
https://github.com/Romakita/ts-express-decorators/blob/master/src/server/components/ServerLoader.ts#L451-L458
and:
https://github.com/Romakita/ts-express-decorators/blob/master/src/server/components/ServerLoader.ts#L411-L431

The path parameters must be changed to accept a Type<any> (class) and build the mapping directly with the class.

See you,
Romain

**Comment by Romakita** [comment]
Hi @jperezdavinchi ,

One question ! Why you minify the server and controllers ? Isn't not necessary, this files will never loaded by the browser. 
I recommend you to change the rule to minify only the file exposed by your server ;)

See you,
Romain

**Comment by jperezdavinchi** [comment]
Hi @Romakita,
I'm sorry for not answer before!
I was thinking in the minification to reduce the number of files for fastest deploy and the optimization of the code that uglify does.
But you are right, is not really necessary. I came from frontend development and I have the constant concern of the size, number of files and optimization.
Thank you so much for your answer and for your hard work! I love this framework.

**Comment by Romakita** [comment]
Thanks @jperezdavinchi ;)
