### ISSUE TITLE
migration from 1.4.6 to 2.3.3: login rest call does not return 

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/ts-express-decorators#114]
## Informations
Question/2.3.3

## Description
I'm currently migrating from 1.4.6 to 2.3.3 and did all required changes.
The server seems to start as expected, logs the mounted routes with endpoints and controller methods.
No errors so far.

When trying to login from the client I see the incoming request and passport authentication but no response is created. The browser console log does not show any errors.

Do you please have any hints for me to narrow down the issue?

## Todos

- [ ] Example: logfile output for initialization and login
[server-login.txt](https://github.com/Romakita/ts-express-decorators/files/1313730/server-login.txt)
[server-log.txt](https://github.com/Romakita/ts-express-decorators/files/1313731/server-log.txt)

- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hi @WalterLeinert ,

I think, you to change something in your controller. You can compare your code with the example on passport.js here:
https://github.com/Romakita/example-ts-express-decorator/blob/2.0.0/example-passport/controllers/passport/PassportCtrl.ts#L20-L48

The signup have the same change ;)

See you,
Romain

**Comment by Romakita** [comment]
In addition: https://romakita.github.io/ts-express-decorators/#/tutorials/passport

**Comment by Romakita** [comment]
Hi @WalterLeinert ,

Have you fix your problem ?
