### ISSUE TITLE
[Decorator] Static

### ISSUE THREAD

**Issue by alexproca** [Romakita/ts-express-decorators#12]
If we want to add some static resources we have to:

```
this.getExpressApp()
            .use(Express.static('./app'))
            .get('*', (req, res) => {
                res.sendFile(__dirname + '/app/index.html')
            })
```

It would be nice to add static resources from decorators. This decorator could be added to server.

Example:
```
@Static({
  '/': './app',
  '/css', './css-files'
})
export Server extends ServerLoader {
......
}
```

**Comment by Romakita** [comment]
The module serve-static can do that. No ?

```typescript
class ServerLoader {
     $onMountingMiddlewares(){
           const serveStatic =   require('serve-static');
           this.getExpressApp()
                 .use(serveStatic('app'))
                 .use('css', serveStatic('css-files'));
     }
}
```

**Comment by alexproca** [comment]
Yes it can do it and it will do it. The proposal is only syntactic sugar. If one have to implement this he have to be careful with `__directory` because the path should be absolute, to use Path.resolve and so on. This would be very intuitive; you only have to add the route and the directory. May be even extended to nested static routes:
```
@Static({
  '/css': {
    'old': './old-css-files',
    'new': './new-css-files'
  },
  'public': './public'
})
```

Usually syntactic sugar shrinks the room for errors. ;)

**Comment by Romakita** [comment]
Ok Alex :) you can propose your implementation of this decorator !

**Comment by alexproca** [comment]
Sure you can assign it to me! I will do it at the end of the week. I always wanted to extract express utils in a library like this but somehow managed not to do it. Your project is exactly the right thing I needed for migrating an older project in the brave new world of typescript.

**Comment by Romakita** [comment]
You are assigned to this task :D

**Comment by alexproca** [comment]
Cool thanks. You can assign #13 to me too.

**Comment by Romakita** [comment]
Implemented with the new decorator 
```typescript
@ServerSettings({
   serveStatic: {
      "\": "webapp"
   }
})
class Server extends ServerLoader {}
