### ISSUE TITLE
Mixing ts-express- and typegoose decorators

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#120]
## Informations

Type | Version
---|---
Question | 2.3.*

****

## Description
I really like _ts-express-decorators_! At the same time I am very fund of what [typegoose](https://www.npmjs.com/package/typegoose) brings to the table. The question is how one should bring these two ideas together? 

Both libraries wants to decorate the model objects. And I love the idea of having the model in one place and have Swagger documentation (_Ts.ED_) and Mongoose schemas (typegoose) generated from the same source. 
An example could be:

```
export class User extends Typegoose {
    
    //@prop()
    @JsonProperty()
    username?: string;

    @prop()
    @JsonProperty()
    email?: string; 

  ...
}

```

But they do not seem be able to coexist. Both libraries are into the serialize/deserialize business.  

The ConverterService from _Ts.ED_ dies on properties decorated with the _typegoose_ `@prop` decorator:

```
TypeError: Cannot assign to read only property 'email' of object '#<User>'
```

## Question
I am currently looking into the above issue and perhaps find a workaround.
I just wanted to ask:
 - if anyone has experience including mongoose schemas into the decorator world? Either as part of _Ts.ED_ or through a library like typegoose?
 - if it could be an idea to make the serialization pluggable - so that _mongoose_ schemas could be used in _Ts.ED_? It seems one could easily end up specifying the schema twice?

Any thoughts? 
... meanwhile I will continue my own investigation  :-)

**Comment by Romakita** [comment]
Hi @lwallent ,

Yes, it's big subject and it's planed with this story #85. But I'm blocked on this because the library to validate a model it's choice for the developer and the stack chosen on his project. I didn't know the typegoose, but it's this is something that sounds like what I wanted to do to facilitate the integration of mongoose with Ts.ED (big work).

To answer to your question, I can try the typegoose with one of the Ts.ED example and find a fix if it's a problem with Ts.ED. According to your error, I think typegoose set a readonly flag on the decorated property.

My goal is to stay compatible and agnostic with other libraries ! (as possible :p)

See you,
Romain

**Comment by lwallent** [comment]
Hi Romain,

Yes, you are right about the typegoose property interfering with Ts.ED. I have temporarily changed the typegoose code to fix the problem. I might reach out to the guys behind with a PR or just asking them if the change would be ok :-)
Before I make such a PR, however, I wish to see if everything can play well together. Else there is really no point.


I completely agree with your goal of being compatible and agnostic :-)

KR 
Lasse

**Comment by lwallent** [comment]
I have created a PR on the _typegoose_ project. I now have the two packages locally living peacefully together :-)

**Comment by Romakita** [comment]
Yes :) nice job !

**Comment by scopsy** [comment]
@lwallent I'm trying to use typegoose with ts-express-decorators and the moment i do `class User extends Typegoose`

```
TypeError: Cannot read property 'get' of undefined
    at new ConverterService (/Users/dmitrigrossman/projects/node-typescript-starter/node_modules/ts-express-decorators/src/converters/services/ConverterService.ts:24:6)
    at Function.invoke (/Users/dmitrigrossman/projects/node-typescript-starter/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:278:16)
    at registry.forEach.provider (/Users/dmitr```

**Comment by lwallent** [comment]
Hi @scopsy 

As I just explained on the Typegoose side of things I now have quite a differet view on how this is to be done.
 
I have a picture in my mind of how this should be done within the boundaries of ts-express-decorators (Not involving Typegoose). It is currently a looooong running issue (#140). Sorry but other things keep having higher priority :-(

So what have I done, you may ask? I mean when I am not using Typegoose and I haven't yet implemented it on the TsED side.

Well, I have prepared for the future I hope will some day come;

1) having a Pojo decorated using TsED decorators
2) having a plain no-nonsense Mongoose schema (which should then later be generated from the Pojo)

So I have quite a large test-suite for when I do get around to implementing the schema generation :-)

In the meantime @Romakita has done a great job on create a jsonSchema from the Pojo and from there it should be even easier to create the mongoose schema. There are also different existing initiatives out there which bridges the gap between json-schema and mongoose-schema:
https://stackoverflow.com/questions/29239239/define-a-schema-with-json-schema-and-use-mongoose

Hope this helps :-)

**Comment by scopsy** [comment]
@lwallent Thanks for the detailed response! 

I was not even trying to do validation, the app just crashed the moment I introduced Typegoose. 

Simply changed the version to 3.4.5 (looked the one you forked on your page). seems like after this version the two projects are not compatible at all

**Comment by troyanskiy** [comment]
Hello to all.
I also had an issue with typegoose + ts.ED.
So I have just created some alternative to typegoose which I've called tsgoose.
It's very early alpha I would say and not fully documented yet (just one example how to use).
So if you have time and wish, please help me to test it.
NPM https://www.npmjs.com/package/tsgoose
GitHub: https://github.com/troyanskiy/tsgoose

I still need to implement some things. 
Feel free to create issues with bugs and improvements. 
Thanks!

**Comment by Romakita** [comment]
Nice initiative @troyanskiy ;)
