### ISSUE TITLE
Handler Chain Data

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#122]
## Informations

Type | Version
---|---
Question | 2.3.*

****

## Description
I am investigating how to best do handler chaining in _Ts.ED_

In Express _IRoute_ each endpoint is defined as IRouteHandler, which again is an array of chained handlers:

```typescript
interface IRouterHandler<T> {
    (...handlers: RequestHandler[]): T;
    (...handlers: RequestHandlerParams[]): T;
} 
```

In _Ts.ED_ the `@ResponseData ()`  according to the documentation will provide:

> Provide the data returned by the previous middlewares.

The documentation suggests simply returning the data, but that does not not work in the Middleware. Looking at the _Ts.ED_ source code I found that the Express Request was decorated with some additional methods (these are not found in the build lib):

```typescript
 export interface Request {
            ...
            getStoredData(): any;
            storeData(obj: any): Express.Request;
        }
```
Based on this I successfully created the following example doing what I expected, but not as elegantly as I had hoped for:

 ```typescript
@Middleware()
export class Middleware1 implements IMiddleware {
    async use(@Request()     request: Express.Request,
              @ResponseData() data: any,
              @Next()        next: Express.NextFunction) {

                    console.log("M1 Incoming Data: ", data);
                    console.log("M1 returning 1");        
                    (<any>request).storeData(1);
                    next();
    }
}

@Middleware()
export class Middleware2 implements IMiddleware {
    async use(@Request()     request: Express.Request,
              @ResponseData() data: any,
              @Next()        next: Express.NextFunction) {
         
                    console.log("M2 Incoming Data: ", data);
                    console.log("M2 returning 2");
                    (<any>request).storeData(2)
                    next();
    }
}

@Middleware()
export class Middleware3 implements IMiddleware {
    async use(@Request()     request: Express.Request,
              @ResponseData() data: any,
              @Next()        next: Express.NextFunction) {
                    
                    console.log("M3 Incoming Data: ", data);
                    console.log("M3 returning 3");                
                    (<any>request).storeData(3)
                    next();
    }
}
```

In the controller I specify my chain as:

 ```typescript
   @Get('/testing')
   @UseAfter(Middleware1, Middleware3, Middleware2)  
    async testing() {
        return 5;
    }
```

and this correctly produces the expected output:

```
M1 Incoming Data:  5
M1 returning 1
M3 Incoming Data:  1
M3 returning 3
M2 Incoming Data:  3
M2 returning 2
```

The question is (finally) if I am missing the correct way to alter the data traveling down the chain? How is this supposed to be done?

**Comment by lwallent** [comment]
Continuing my question :-)

I really like the way the Middlewares can be listed in the sequence:

```typescript
@UseAfter(Middleware1, Middleware3, Middleware2) 
```
I guess the only thing needed is getting the typings through to the released code so that one can simply write:

```typescript
request.storeData(3)
```
And finally I would like to incorporate this whole thing in the documentation?

KR
Lasse

**Comment by Romakita** [comment]
Hi @lwallent,

It's interesting. 
In my mind, the middleware can return data, but it doesn't work. So it's bug XD.
This code is responsible to store the data:
https://github.com/Romakita/ts-express-decorators/blob/production/src/mvc/class/HandlerBuilder.ts#L173-L175

For the problem with the typings, you can fix that ^^ and you can add the documentation about the storeData. 

I'll investigate on the problem with the HandlerBuilder ;)
See you,
Romain

**Comment by lwallent** [comment]
Hi Romain,

I have created a pull request that will make the data read/writable within the middleware using the Express request extensions that was already there. Adding to the example to the documentation will follow later.

Kind Regards

Lasse

**Comment by Romakita** [comment]
Hi @lwallent,

I'd just test your example and it work fine when I returned a data in each middleware.
I've created a PR to show you the test.
https://github.com/Romakita/ts-express-decorators/pull/125

The test print this
```bash
number : 2
M1 Incoming Data:  2
M1 returning 3
M2 Incoming Data:  3
M3 returning 5
M3 Incoming Data:  5
M3 returning 8
number : 10
M1 Incoming Data:  10
M1 returning 11
M2 Incoming Data:  11
M3 returning 13
M3 Incoming Data:  13
M3 returning 16
```
You can try this test ;)
See you,
Romain

**Comment by lwallent** [comment]
Hi Romain,

I have now found the issue that caused my example to not work.

I was trying out different things while not cleaning up the parameters of the Middleware! 

Injecting `@Next` without calling it will stop the chain. So in short the first of the following examples work while the seconds does not, which kinds of makes sense :-)

```typescript
async use(@ResponseData() data: any) {
               return 3;
}
```

```typescript
async use(@ResponseData() data: any,   
          @Next()        next: Express.NextFunction) {
               return 3;
}
```

Thanks, I really like being able to leave out the next function all together !

KR

Lasse
