### ISSUE TITLE
@Required() does not validate @BodyParams

### ISSUE THREAD

**Issue by Ahagan** [Romakita/ts-express-decorators#130]
## Informations

Type | Version
---|---
Bug | 2.3.8

****

## Description
When @Required() is added before @BodyParam(), it is expected that an exception would be thrown if no body params were posted to the endpoint or if the body params did not match the expected type.

E.g.

    @Post('/')
    async broadcast(@Required() @BodyParams() webhook: Webhook): Promise<any> {
        ,,,
    }

and the models is
export class WebHook {
   url: string;
  name: string;
}

- if I posted up {}, I'd expected the Required decorator to throw an exception.
- if i posted up { a: '', b: ''} I'd expect the Required decorator to throw an exception because the properties do not match what is on the WebHook class.
- if i posted up no body, I'd expect the Required decorator to throw an exception
- if i posted up { url: 'http://google.co.uk', name: 'test'}, I'd expect the Required decorator to not throw an exception
- if the body params has nested objects these should also be checked that they have been set.

At the moment Required does not validate the BodyParams at all.

## Todos

- [ ] Update Required decorator to validate the BodyParams

**Comment by Romakita** [comment]
Hi @Ahagan,
It's a part of these stories #85 and #35 .

Actually Required work fine only with simple data like this:

```typescript
@Required @BodyParam('name') name: string;
```
With a model, we need to implement a model validators. It's planed :)
See you

**Comment by Ahagan** [comment]
Ok, thanks for letting me know. Do you know when the work will be started on this?

**Comment by Romakita** [comment]
October, I hope ^^.

**Comment by virus2016** [comment]
Hey @Romakita,

Is it possible to add the class validation library now for existing apps? Then once it’s implemented then just move back?

I would love to help out on this but just don’t seem to have time. :-(

Just a thought!

**Comment by Ahagan** [comment]
@Romalita thanks, and keep up all the great work! 😊

**Comment by Romakita** [comment]
@Ahagan the story for the validation feature is ready. You can follow this issue #85
