### ISSUE TITLE
Ability to overwrite initial request log

### ISSUE THREAD

**Issue by Ionaru** [Romakita/ts-express-decorators#135]
## Information

Type | Version
---|---
Improvement | 2.4.1

****

## Story
As a developer, I want to be able to conditionally disable the logging of requests so that I can keep requests to images, JS files, CSS files, etc. out of the log.

## Possible solution
Change the current implementation in `LogIncomingRequestMiddleware.ts`
```typescript
public use(@Req() request: Express.Request, @Res() response: Express.Response): void {

    this.configureRequest(request);

    request.log.info();

    applyBefore(response, "end", () => this.onLogEnd(request, response));
}
```

To something like this
```typescript
public use(@Req() request: Express.Request, @Res() response: Express.Response): void {

    this.configureRequest(request);

    this.onLogStart(request);

    applyBefore(response, "end", () => this.onLogEnd(request, response));
}

protected onLogStart(request: Express.Request): void {
     request.log.info();
}
```

The seperate `onLogStart()` function will allow me to overwrite the initial request log and to add my own logic to it.

**Comment by Romakita** [comment]
Hi @Ionaru ,

You can create PR ;)
See you,
Romain

**Comment by Ionaru** [comment]
I'm not really up-to-speed on the dev environment, documentation and testing of Ts.ED, thought it would be faster to make an issue instead. :wink:

**Comment by Romakita** [comment]
ok :)

**Comment by Romakita** [comment]
@Ionaru  PR ready : https://github.com/Romakita/ts-express-decorators/pull/136
