### ISSUE TITLE
Confuse about service router

### ISSUE THREAD

**Issue by vincent178** [Romakita/ts-express-decorators#14]
https://github.com/Romakita/ts-express-decorators/blob/master/src/services/index.ts#L3

I'm confused about this code, is there any reason to use `express-serve-static-core` instead of `express`?

**Comment by Romakita** [comment]
Express.d.ts didn't provide the type for Express.Router, but in express-serve-static-core we have it. It's just for TypeScript compilation. 

Maybe we need to improve this code in next version.

**Comment by vincent178** [comment]
Thank you for your response, :)

I found that the express already include package `express-serve-static-core`, so we can use `express` types directly.

I will make a PR to remove the dependency of `express-serve-static-core` to make the reference consistent.

**Comment by Romakita** [comment]
fix in 1.2.6
