### ISSUE TITLE
[Feature] Mongoose

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#140]
## Status
New feature

## Description
As a developer, I want to be able to use decorator to create a Mongoose model from Ts.Ed model.

## Usage Example

```typescript
import {Property, Model, createModel}
export class CalendarEvent extends Model {
    @JsonProperty("id")
    _id: string;

    @Property()
    @Required()
    @Ref(CalendarModel) // @Ref("Calendar")
    calendarId: string;

    @Property(schemaOptions)
    name: string;

    @Property()
    dateCreate: Date = new Date();

    @Property()
    dateUpdate: Date = new Date();

    @Property()
    dateStart: Date = new Date();

    @Property()
    dateEnd: Date = new Date();

    @Property()
    description: string;

    @Property()
    complex: Complex;
}

export CalendarEventModel = createModel<CalendarEvent>(CalendarEvent); 
```

### Configuration
Proposal quick configuration:
```typescript
import {ServerSettings, ServerLoader} from "ts-express-decorators";
import "ts-expressd-decorators/mongoose";

@ServerSettings({
   mongoose: {
      'host':  'host',
      'name: 'name'
   }
})
class Server extend ServerLoader {}
```

## Acceptance criteria

   - [ ] A invalid model throw a BadRequest after model is deserialized by Ts.ED,
   - [ ] Property inherit from JsonProperty,
   - [ ] Metadata should be used to fill the swagger doc.
   - [ ] Attribute type is retrieve from metadata ({type: String}).

**Comment by Romakita** [comment]
I've tried a lot of solution, but mongoose with typescript ... is very hard to have the good implementation.
Actually the best solution (IDE completion, type checking, etc...) is the typegoose proposal.
I've write an example, with the Ts.Ed API:
```typescript
import * as Mongoose from "mongoose";
import {Store, Type} from "ts-express-decorators";
export class Model extends Mongoose.Model {
}
export function createModel<T>(target: Type<T>) {
    const schema = Store.from(target).get("schema") || {
        name: String
    };
    return Mongoose.model<T & Mongoose.Document>(target as any, new Mongoose.Schema(schema));
}
```
If you have a better solution, I get it :)

**Comment by vologab** [comment]
It would be nice have common solution, because except Mongoose & Typegoose we have  RDBMS and ORMs for them such as Sequilize and Sequilize-Typescript https://github.com/RobinBuschmann/sequelize-typescript. What do you think, Is it possible?

**Comment by Romakita** [comment]
Hi @vologab ,

This feature will be packaged like swagger. It's a plugin ;). We can create another plugin based on sequelize and sequelize-typescript :). All is possible ^^ but I need help. I work on validation feature actually !

See you
Romain

**Comment by lwallent** [comment]
Hi @Romakita,

In your example you have included:
```typescript
export class CalendarEvent extends Model {
```
Is there a special reason for extending Model as such a dependency is one of the things that I disliked about Typegoose.

I would love to work on this task and have a pretty good idea about how to proceed. However I am going away on holidays, so I will not promise any timeframe :-)

KR

Lasse

**Comment by Romakita** [comment]
@lwallent,

Isn’t necessary. You can extends from Mongoose.Model directly. But Mongoose throw an exception if the model didn’t inherit from Model.

No problem, I haven’t due date for that ;). Have a Good holiday Lasse !

**Comment by robgrimball** [comment]
Just as a quick comment for those not married to mongoose, I've had a good deal of success just using [Hydrate](https://github.com/artifacthealth/hydrate-mongodb) as an ODM with TsED.  It has decorators of its own built in and from TsED's standpoint I just do the initialization of Hydrate in $onReady via a small service I inject.  If you don't mind the JPA style sessions (or like them as I do) then Hydrate is a pretty good solution and integrates well with TsED.

**Comment by Romakita** [comment]
First step. Add database connection from ServerSettings https://github.com/Romakita/ts-express-decorators/tree/feat_mongoose
