### ISSUE TITLE
Async middleware

### ISSUE THREAD

**Issue by FrozenDroid** [Romakita/ts-express-decorators#145]
## Informations

Type | Version
---|---
Question | 2.6.4

****

## Description
I would like to use an async middleware. Is this possible?

**Comment by Romakita** [comment]
Hi @FrozenDroid ,

```typescript
@Middleware(){
    async user(){}
}
```

see you :)

**Comment by FrozenDroid** [comment]
Hmm, does that also work with `$onAuth`? I can't get that to work:
```js
    public async $onAuth(req: Request, res: Response, next, options?: any) {
        const firebase: Firebase = InjectorService.get(Firebase);
        const admin = firebase.getAdmin();
        const authorization: string = req.header('Authorization');
        if (!authorization) {
            return next(false);
        }
        const token = authorization.split(' ')[1];
        await admin.auth().verifyIdToken(token).then((decodedToken) => {
            console.log(decodedToken);
        });
        return next(false);
    }
```
Before the await, returning `next(false);` works like it's supposed to. After the await, it ignores the return and behaves as if the user is authenticated.

**Comment by Romakita** [comment]
Can you not mix the conversations? it's disturbing ... ^^

**Comment by FrozenDroid** [comment]
Sorry, I probably misunderstood; I thought `$onAuth` is essentially a middleware?

**Comment by Romakita** [comment]
I'll continue this thread on the original subject ;) #144

**Comment by FrozenDroid** [comment]
These are two different issues. This one is the problem that it doesn't wait for the`await`. The other one is just about finding the best method to inject a factory. The way I do it now, the factory works. I just feel like it could be done better.

**Comment by Romakita** [comment]
It's because you use next() function and async at the same time. In your case this example will work:

```typescript
public $onAuth(req: Request, res: Response, next, options?: any) {
        const firebase: Firebase = InjectorService.get(Firebase);
        const admin = firebase.getAdmin();
        const authorization: string = req.header('Authorization');
        if (!authorization) {
            return next(false);
        }
        const token = authorization.split(' ')[1];
        admin.auth().verifyIdToken(token).then((decodedToken) => {
            console.log(decodedToken);
            next()
        });
}
```

**Comment by FrozenDroid** [comment]
That works! Awesome :)  
Thanks for such an awesome project!

**Comment by Romakita** [comment]
Thanks ;)
