### ISSUE TITLE
No controller response?

### ISSUE THREAD

**Issue by dennisli92** [Romakita/ts-express-decorators#150]
## Information

Bug/Question|2.70

****

## Description
My controller method won't return a response. But it does work if use `response.status(200).json(body)`.

My method looks something like this:
```typescript
  @Post('/verify')
  @Authenticated()
  public verify(
    @Required @BodyParams('countryCode') countryCode: string,
    @Required @BodyParams('phoneNumber') phoneNumber: string,
  ): Promise<any> {
    const userId = req.decoded.id

    const parameters = {
      api_key: API_KEY,
      country_code: countryCode,
      phone_number: phoneNumber,
    }
    return rp({
        method: 'POST',
        uri: 'https://api.authy.com/protected/json/phones/verification/start',
        body: parameters,
        json: true,
        resolveWithFullResponse: true,
   })
   .then((response) => {
      // Returns nothing. but res.status(200).json(response.body) does work.
      return response.body
   })
  }
```
If it's relevant, I use an overridden middleware for `AuthenticatedMiddleware` (which modifies request to add `request.decoded`). The request works, but no response is ever sent. Instead, if I add the response/next decorator and use `res.status(200).json(response.body)`, I will get a response as expected. Any idea what's going on?

**Comment by Romakita** [comment]
Hi @dennisli92,
I think, the only reason why the method didn't return a response, it'll be that `response.body` is undefined.

You can enable the debug mode to see the called middlewares and data sent by Ts.ED.

```typescript
@ServerSettings({debug: true})
class Server extends ServerLoader{}
```

Can check the value of response.body ? if it's undefined, just return a default value like empty string or other.

See you.
Romain

**Comment by Romakita** [comment]
In complement for your req.body.decoded. You can create a Filter and a decorator like that:

```typescript
/**
 * @module common/filters
 */
/** */

import {Filter} from "../decorators/filter";
import {IFilter} from "../interfaces";
import {ParseService} from "../services/ParseService";

@Filter()
export class DecodedParamsFilter implements IFilter {
    constructor(private parseService: ParseService) {
    }
    transform(expression: string, request: any, response: any) {
        return this.parseService.eval(expression, request["decoded"]);
    }
}
```
And the decorator:
```typescript
export function DecodedParams(expression?: string | any, useType?: any): Function {
    return <T>(target: Type<T>, propertyKey: string | symbol, parameterIndex: number): void => {
        if (typeof parameterIndex === "number") {
            ParamRegistry.useFilter(DecodedParamsFilter, {
                target,
                propertyKey,
                parameterIndex,
                expression,
                useType
            });
        }
    };
}
```
Example Usage:
```typescript
public verify(
    @Required @DecodedParams('id') id: string,
    @Required @BodyParams('countryCode') countryCode: string,
    @Required @BodyParams('phoneNumber') phoneNumber: string,
  ): Promise<any> {
...
}
```

See you,
Romain

**Comment by lwallent** [comment]
Hi @dennisli92,

Also if you do inject the `next` function and do not call it, the response is not sent. This has bitten me a couple of times :-)

I know it is not part of your example, but if you have moved from a response/next decorator version to just returning the value, chances are that you could have forgotten to remove the injection?

just my 2 cents.

Kind Regards

Lasse

**Comment by dennisli92** [comment]
Thanks so much @Romakita for the custom decorator! I was trying to figure out how to do that :)

As for, `response.body`, it definitely is not empty. Here's a sample:
```
{
  "carrier":"T-Mobile USA, Inc.",
  "is_cellphone":true,
  ...
  "success":true
}
```

**Comment by dennisli92** [comment]
@lwallent . Thanks! Just gave that a shot, and it seems to have fixed it. Is that expected behavior with the `@Next` decoration?

**Comment by lwallent** [comment]
Hi @dennisli92 ,

It makes sense when you think about it? Either you take control with response/next or you rely on the return/throw pipeline. 

In _TsED_ this is by far the easiest way to determine wether it should call `next` for you or not. If you have used the @Next decorator it must be assumed that you plan to pass on the control to the next handler?

This is comparable to testing asynchronous code with Mocha where you pass the `done` callback.

Hope this helps.

Kind Regards

Lasse

**Comment by dennisli92** [comment]
@lwallent : Yup, fair point, and I don't disagree. It makes sense, but was just fairly confusing at the time since I was still trying to figure out how the framework worked. (It's quite a delight to work with, by the way!)

Perhaps I should just change my linter settings to be a bit more restrict and forbid unused function parameters :)
