### ISSUE TITLE
Swagger Documentation for Response Models

### ISSUE THREAD

**Issue by Ahagan** [Romakita/ts-express-decorators#153]
## Informations

Type | Version
---|---
Question | 2.x

****

## Description
The swagger documentation that is generated contains all the endpoints and example request models (defined by decorators on models).

Does the library currently generate the same documentation for response models to inform users of the API what will be returned to them? 

If so, how is this done? I currently have the same decorators on the response objects.

If not, is this a feature that could be added?

Thanks.

**Comment by Romakita** [comment]
Hi @Ahagan ,

@Returns do that :) 
```typescript
@Returns(Model, {description: "Description"}) //OR
@Returns(Model)
 async myMethod(): Promise<Model>  {

 }
```
> more details : https://romakita.github.io/ts-express-decorators/#/api/swagger/returns

**Comment by Ahagan** [comment]
Thanks :)

On 25 Oct 2017, at 22:11, Romain Lenzotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Ahagan<https://github.com/ahagan> ,

@returns<https://github.com/returns> do that :)

@Returns(Model, {description: "Description"}) //OR
@Returns(Model)
 async myMethod(): Promise<Model>  {

 }

more details : https://romakita.github.io/ts-express-decorators/#/api/swagger/returns
