### ISSUE TITLE
[Feature] Socket.io

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#161]
## Informations

Type | Version
---|---
Improvement | 2.x

****

## Description
Add a package on top of Socket.io. Goal: simplify Socket.io integration with Ts.ED.
- WebSocket,
- Decorators (@SocketCtrl, @Event)

## Example

```typescript
import {WebSocket, Socket, IO, OnConnection, OnDisconnect, Event, Args} from "ts-express-decorators/socketio";

@SocketService("/chat") // support Namespacing and Injectable to another Service or Controller
class ChatWS implements OnConnection, OnDisconnect {
   constructor(@IO private io: SocketIO.Server) {}

   $onConnection(socket: SocketIO.Socket, nsp: SocketIO.Namespace)  {

   }

   $onDisconnect(socket: SocketIO.Socket, nsp: SocketIO.Namespace) {
   
   }    

   @Input("eventName")
   @Emit("eventNameResponse") // @Broadcast("event") || @BroacastOthers("event")
   async method(@Args() arguments: any[], @Socket socket: SocketIO.Socket, @Nsp nsp: SocketIO.Namespace) : any | Promise<any> {
      return "My message" // emit message
   }

   // OR
   @Input("eventName")
   method(@Args(0) arg0: string, @Socket socket) : void {
     socket.emit("eventNameResponse", "My message");
   }
}
```
## Acceptance criteria

- [ ] WebSocket can use the socket namespace,
- [ ] WebSocket instance can be injected to another Service or Controller

**Comment by CarterLi** [comment]
I was searching for web socket support in ts-express-decorators, and then found this.

Looking forward to it 👍

**Comment by CarterLi** [comment]
Just noticed that this feature was postponed.  Could you please explain what's the best way to integrate Web Socket into Ts.ED?

**Comment by Romakita** [comment]
Hi @CarterLi,
Sorry about that, I didn't have a time to start this feature.
In the meantime, you have an example with Socket.io here https://romakita.github.io/ts-express-decorators/#/tutorials/socket-io 

Project example: https://github.com/NodeLabs/techday-node/tree/solution

See you,
Romain

**Comment by CarterLi** [comment]
Thanks for your explanation @Romakita

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/tree/feat_socket_io
