### ISSUE TITLE
How to consume a single controller manually?

### ISSUE THREAD

**Issue by vekexasia** [Romakita/ts-express-decorators#165]
## Informations

Type | Version
---|---
Question | 2.x

****

## Description
How do I consume a controller only?

**Comment by vekexasia** [comment]
Let me explain. Lets say I already have an express app. I just want to migreate a single controller. How do I get the controller "router" or something I can `use` ?

**Comment by Romakita** [comment]
Hi @vekexasia,
Sorry for the late reply.

I'm not sure if I understood your need. But I try to answer you.

In first you need to create your server:
```typescript
@ServerSettings({
   "mount": {
    "/rest": "./controllers/**/*.js"
  }
})
export class Server extends ServerLoader {
}
```
Then you need to create a controller:

```typescript
@Controller("/path")
class MyController {
   constructor() {
   }

   @Get("/:id")
   getMethod() {}
}
```
 So, to use the routerController of the MyController class, you must inject the RouterController in his constructor:

```typescript
@Controller("/path")
class MyController {
   constructor(routerController: RouterController) {
         const router = routerController.getRouter();
         router.get('/:id', this.getMethod)
   }

   getMethod() { 
   
   }
}
```
> Interface  : https://romakita.github.io/ts-express-decorators/#/api/common/mvc/routercontroller

I know, this part isn't in the documentation. If this example work fine with you, I'll move on the official documentation ;)

See you,
Romain

**Comment by krnprdp** [comment]
Hi @Romakita 
As a follow up, Can I use the controllers without using the Server class? 

I want to use something like:

import * as express from "express";

const app = express();

// Something like this ->
app.register(MyController);

app.listen(port, function () {
    console.log(`Web App listening on port ${port}`);
});

**Comment by Romakita** [comment]
Hi @krnprdp,

Is not possible simply like that. Because, Ts.ED didn't add method to Express and ServerLoader has lifecycle to bootstrap Injector, Service, Controller, Middlewares.

You can write your bootstrap script using the ServerLoader class as an example, but you will out of the framework.

Why you need that ?
See you
