### ISSUE TITLE
performance 

### ISSUE THREAD

**Issue by laof** [Romakita/ts-express-decorators#167]
## Informations

Finding performance problems

****

## Description
The server is too slow, not a network problem. You can't use it. Have you tried it?

**Comment by Romakita** [comment]
Hi laof ?

Which version have you ?

**Comment by laof** [comment]
@Romakita ， version  ^2.9.1，You can't request frequently on the server ，but I haven't tried the latest version。I don't have this problem with anything else, for example：express。

**Comment by Romakita** [comment]
Your last message Isn’t complete ^^

**Comment by laof** [comment]
The same problem with the new version~

**Comment by Romakita** [comment]
Actually, I haven't problem performance with the latest version.
To help you, I need more information. Ts.ED have debug mode configurable as follow:
```typescript
@ServerSettings({debug: true})
class Server extends ServerLoader {}
```
In this mode you'll see the complete log for each request.  Retry a request where you have a performance problem and send me the log. 
In addition, can you send me the partial implementation of your method controller (the one where you have a performance problem) ?

See you

**Comment by vologab** [comment]
@Romakita How can we improve performance? By default "Hello world" app with pure express 5 times faster than TsED - https://github.com/vologab/TsED_perf
Or maybe I'm doing something wrong?

**Comment by Romakita** [comment]
@vologab Thanks for the test, very useful. I'll investigate on the performance problem and publish new fix :)

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/pull/168

**Comment by Romakita** [comment]
I've added a new configuration to optimize the server:
```typescript
@ServerSettings({
    logger: {
         logRequest: false|true, // disable Ts.ED request log for each incoming request.
         requestFields: ["reqId", "duration"] // if logRequest = true, you can customize the fields displayed in the log.
    }
})
```
See you,
Romain

**Comment by Romakita** [comment]
v2.14.1

**Comment by laof** [comment]
@vologab Thanks for the test ，very useful。
@Romakita Thank you for your response, I also study  it in my spare time.
