### ISSUE TITLE
Mount a controller class

### ISSUE THREAD

**Issue by Ionaru** [Romakita/ts-express-decorators#172]
## Information

Type | Version
---|---
Improvement | 2.14.2

****

## Description
Option to manually import controller class instead of a directory search.
```typescript
this.mount('/home', HomeController);
```

I prefer to manually import models, services and controllers without doing a directory search. Models and services can already be imported this way, but I haven't found a way for controllers. Is this possible?

**Comment by Romakita** [comment]
Hi @Ionaru ,

You can do that with the mount options:

```typescript
@ServerSettings({
  "mount": {
    "/rest/": [
      "./controller/MyController1.js", 
      "./controller/MyController2.js"
    ]
  }
})
```
See you :)
Romain

**Comment by Ionaru** [comment]
I'd like to do that without needing the file name, instead something like this:

```typescript
import { HomeController } from './controllers/home.controller';

@ServerSettings({
    // ...
})
export class Server extends ServerLoader {
    // ...
    public $onMountingMiddlewares(): void {
        // ...
        this.mount('/home', HomeController);
        // ...
    }
}
```

or through the settings

```typescript
import { HomeController } from './controllers/home.controller';
import { NESController } from './controllers/nes.controller';

@ServerSettings({
    // ...
    "mount": {
        "/rest/": [
            HomeController, 
            NESController
        ]
    }
})
export class Server extends ServerLoader {
    // ...
}
```

This would be very useful for me because I am using ts-node for development & debugging and in production I want to use the compiled javascript, this means I need some way of having dynamic file extensions in the code `controller.ts` vs `controller.js`, or use the direct imports.

**Comment by Romakita** [comment]
@Ionaru 

Ok, I'll add your needs to the backlog :)

**Comment by Romakita** [comment]
@lwallent  Can I merge this feature ?

**Comment by nicojs** [comment]
Cool! I was searching for exactly this feature. Just-in-time delivery indeed! 🍰
