### ISSUE TITLE
How to change the built-in address 0.0.0.0 to your own?

### ISSUE THREAD

**Issue by khusamov** [Romakita/ts-express-decorators#184]
Hello!
I did not find in the server settings @ServerSettings a parameter that changes the server address. How to change the built-in address 0.0.0.0 to your own?

**Comment by Romakita** [comment]
Hi @khusamov ,
You can set your address on the httpPort attribut too.
```typescript
@ServerSettings({
  httpPort: "0.0.0.0:8008"
})
```
See you
Romain

**Comment by khusamov** [comment]
Thank you!
