### ISSUE TITLE
Custom multer storage engine

### ISSUE THREAD

**Issue by marccampbell** [Romakita/ts-express-decorators#187]
## Information

Type | Version
---|---
Improvement | 2.16.3

****

## Description
I'd like to be able to pass custom multer configuration through to the multer object created by the MultipartFile object. More than `uploadPath`, I'd specifically like to be able to create a custom [multer storage engine](https://github.com/expressjs/multer/blob/master/StorageEngine.md) and pass that in the TSED server config.

From the looks of the docs and code, I don't believe this is possible today.

Would you be open to accepting this as a PR if submitted?

## Example
```typescript
@ServerSetttings({
   multer: {
     /// global multer configuration 
  }
})
export class Server extends ServerLoader {}
```

## Acceptance criteria
 - [ ] Multer can be configured from global server configuration
 - [ ] Documentation is updated https://github.com/Romakita/ts-express-decorators/blob/master/docs/tutorials/upload-files-with-multer.md

**Comment by Romakita** [comment]
Hi @marccampbell,

Yes exactly, Global configuration it's just to configure the path. Other options is provided by the decorator. Is not sufficient in your case.

PR are always welcome :)

Just be you sure to read this documentatoin https://github.com/Romakita/ts-express-decorators/blob/master/CONTRIBUTING.md ;)

See you
Romain

**Comment by Romakita** [comment]
#196

**Comment by Romakita** [comment]
v2.19.0
