### ISSUE TITLE
BodyParams Decorator not working.

### ISSUE THREAD

**Issue by robgrimball** [Romakita/ts-express-decorators#189]
## Information

Type | Version
---|---
Bug/Improvement/Question | 2.17.0

****

## Description
What I am about to describe was working fine in a previous 2.x version before I blew away my node_modules and npm installed and it upgraded automatically my version of ts-express-decorators.  Presently it is at 2.17.0.

I have an endpoint, which handles authorization for my app(though the problem with @BodyParams is throughout the application, this is just a simple example to use the auth endpoint).  It receives a username and password from the front end via the body of a POST request to that endpoint.  However, it seems that the @BodyParams is not pulling the parameters out into the variables even though the logging for the endpoint clearly shows that the values are there.  

This is suficient snippet of my code which shows the username/password @BodyParams decorator, the variables being used, and me outputting the results in a console statement:

![image](https://user-images.githubusercontent.com/8190747/33953740-0cfb0e76-e004-11e7-8643-388f12f4c2a9.png)

The below shows an attempt to use this endpoint with username/password set as test/test, and as you can see the console statement is printing out the values of those variables as both being undefined, while the log for the execution of the endpoint shows that it clearly has the given values in the body with those property names.

![image](https://user-images.githubusercontent.com/8190747/33953881-98b60b96-e004-11e7-9d66-4a29bcde7ca0.png)

So I am wondering what I am doing wrong here or if this is a bug I have stumbled upon.  I am running with node v8.9.3 for this.

**Comment by Romakita** [comment]
Hi @robgrimball,

Yes, I've identified the bug on the FilterBuilder when the @Required decorator is used.
It'll be fixed with 2.17.1
