### ISSUE TITLE
[Decorator] UseBefore and UserAfter hooks

### ISSUE THREAD

**Issue by vincent178** [Romakita/ts-express-decorators#19]
Hi @Romakita and @alexproca ,

I'm thinking about add `BeforeAction` and `AfterAction` for this project.

The main reason here is using middleware can add generic logic with `request, response next` way, but for our controller methods aka endpoints, is there a way to intercept the result around the method? The `BeforeAction AfterAction` is my proposal.

For example

```
@Controller("")
export default class HomeController {

    ...
    @Get("/")
    @ResponseView("home/index")
    @AfterAction('renderAssets')
    public async indexAction(request: Express.Request): Promise<Object> {

        const members = await this.memberService.findAll();
        
        return {
            title: 'blog | 博客',
            content: "This is content",
            members
        };
    }

    private renderAssets(result: any,
                         request?: Express.Request,
                         response?: Express.Response,
                         next?: Function) {

        const assets = {};
        result['assets'] = assets;
        return result;
    }
}
```

With `AfterAction`, I have a way to change the data before render to the page.

For global Actions, we can register these functions in ServerLoader.

Do you guys think it's a right way to go? or you guys have any idea on this?

Comments are very welcome.

Thanks,
Vincent

**Comment by alexproca** [comment]
Can we see them as a generalisation of `@Authenticated() extends @BeforeAction()` and `@ResponseView extends @AfterAction()` ?

**Comment by vincent178** [comment]
yes, they do

**Comment by Romakita** [comment]
Hi @vincent178 ,

Good idea. For your decorator, you can set a function/method as parameters like that:

```typescript
@Controller("")
export default class HomeController {

    ...
    @Get("/")
    @ResponseView("home/index")
    @AfterAction(this.renderAssets)
    public async indexAction(request: Express.Request): Promise<Object> {

        const members = await this.memberService.findAll();
        
        return {
            title: 'blog | 博客',
            content: "This is content",
            members
        };
    }

    private renderAssets = (result: any,
                         request?: Express.Request,
                         response?: Express.Response,
                         next?: Function)  => {

        const assets = {};
        result['assets'] = assets;
        return result;
    }
}
```
Isn't necessary to give a name function with typescript :D . Static method work too ^^

I think `@ResponseView` and #10 response formatting are the same actions like `AfterAction` (according to @alexproca).

**Comment by vincent178** [comment]
ok, I will try my best to work on this.
