### ISSUE TITLE
[Feature] Acknowledgements to Socket.IO

### ISSUE THREAD

**Issue by Kapulara** [Romakita/ts-express-decorators#192]
## Informations

Type | Version
---|---
Improvement | 2.x

****

## Description
Right now you define the "@Input" and the "@Emit", which would mean Input and Emit are on different channels.

I would love [acknowledgements](https://socket.io/docs/##sending-and-getting-data-(acknowledgements)) to be added to the socket.io library.

What the documentation suggests:
```typescript
@SocketService("/my-namespace") 
export class MySocketService {
    @Input("eventName")
    @Emit("responseEventName") // or Broadcast or BroadcastOthers
    async myMethod(@Args(0) userName: string, @SocketSession session: SocketSession) {
        
        const user = session.get("user") || {}
        user.name = userName;
        
        session.set("user", user);
        
        return user;
    }
}
```

My improvement would be:
```typescript
@SocketService("/my-namespace") 
export class MySocketService {
    @InputCallback("eventName")
    async myMethod(@Args(0) userName: string, @SocketSession session: SocketSession) {
        
        const user = session.get("user") || {}
        user.name = userName;
        
        session.set("user", user);
        
        return user;
    }
}
```

And this would be used like this:
```javascript
socket.emit('eventName', 'bartvanvliet', function (data) {
    console.log(data); // data will be the user
});
```

[More info on acknowledgements](https://socket.io/docs/##sending-and-getting-data-(acknowledgements))

**Comment by Romakita** [comment]
Hi @Kapulara ,
Thanks for your message. If I understand, you want a decorator that merge the `@Input` and `@Emit` decorator behavior ?

Why not, but the proposed name is not clear for me? `@InputAndEmit` has more sense, in the same idea, @InputAndBroadcast and @InputAndBroadcastOthers should be added. 

![socket](https://romakita.github.io/ts-express-decorators/_media/socketio.png)

You can propose a PR ;)
```typescript
export function InputAndEmit(event) {
   return (...args: any[])  => {
        Input(event)(...args);
        Emit(event)(...args);
   }
} 
```

See you,
Romain

**Comment by Romakita** [comment]
Code example with socket.io and Ts.ED: https://gist.github.com/Romakita/6696edb0d51838c5c14a26dcfda97d18

**Comment by Kapulara** [comment]
However, The name you are suggesting I think is much better! 😄

**Comment by Romakita** [comment]
#197

**Comment by Romakita** [comment]
v2.20.0
