### ISSUE TITLE
Typescript enums validation

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#198]
Hi,
Is there any way to validate typescript enum in models without _ajv_ module?

```typescript
enum Size {
    L = 'L',
    XL = 'XL'
}

@Strict(true)
class Model {
    @JsonProperty()
    public size: Size;

    @JsonProperty()
    public sizes: Size[];
}
```

**Comment by Romakita** [comment]
Hi @kalu111,

Validation is only supported with AJV module. But you can create you own validation service like AJV package.

Look this service: 
https://github.com/Romakita/ts-express-decorators/blob/master/src/ajv/services/AjvService.ts 

Important things, you need to override the ValidationService of Ts.ED and implement your own methods:
```typescript
@OverrideService(ValidationService)
class MyCustomValidationService {
    constructor(private jsonSchemaService: JsonSchemesService) {
        super();
    }
    public validate(obj: any, targetType: any, baseType?: any): void {
        const schema = this.jsonSchemaService.getSchemaDefinition(targetType);

        if (schema) {
            const ajv = new Ajv();
            const valid = ajv.validate(schema, obj);

            if (!valid) {
                throw(this.buildErrors(ajv.errors!));
            }
        }
    }
}
```
I hope this example will help you :)

jsonSchemaService store all metadata like validation metadata:
https://github.com/Romakita/ts-express-decorators/blob/master/src/ajv/decorators/enum.ts

> I realize that I will be able to move the JsonSchema-based validation designers into the jsonschema package, because these decorators aren't coupled with AJV.

You can reused these decorators to implement your own ValidationService without AJV ;)

Romain

**Comment by kalu111** [comment]
OK, thanks for explanation.

When the ValidationService.validate is called?
I have created ValidationService and send request with data but the validate method is not called at all.

**Comment by Romakita** [comment]
The ValidationService.validate is called when you have a model used on a method controller like that:

```typescript
@Controller("/")
class MyCtrl {
   @Get("/")
   method(model: Model) {}
}
```

But you need to import you CustomValidationService manually in your server:

```typescript
import {ServerLoader} from "ts-express-decorators";
import "./services/overrides/MyCustomValidationService";
 
class Server extends ServerLoader{
}
```
See you :)

**Comment by kalu111** [comment]
Still does not work.

**Comment by Romakita** [comment]
Have you set the OverrideService decorator on your class ?
```typescript
import {ValidationService} from "ts-express-decorators";

@OverrideService(ValidationService)
class MyCustomValidationService {

}
```

**Comment by kalu111** [comment]
Yes.

**Comment by Romakita** [comment]
What is your Ts.ED version ?

**Comment by Romakita** [comment]
@kalu111, I've found an issue with the validation (and the custom validation too).
Fix is already released on v2.20.1 and v3.0.1.

See you :)

**Comment by kalu111** [comment]
OK, 
The validate method is working now.

Thanks!

**Comment by kalu111** [comment]
For the tests I decided to install ajv module and used some of validation decorators.

I have issues with type of "number".

```
@Strict(true)
class Model {
    @ExclusiveMinimum(1)
    value: number;
}
```

I send a body:

```
{
    "value": 2
}
```
 
and get an error: "chema is invalid: data.properties['value'].exclusiveMinimum should be number"

When the ajv module is not included and even I send "value" as string "2", then the decorators properly cast value to number.

What is wrong?

**Comment by Romakita** [comment]
I've the same issue. Maybe the generated json schema is not correct for AJV, I'll check the documentation and find the fix ;)

**Comment by Romakita** [comment]
And any with typescript generate an Object as type. I can't generate the right json schema if you didn't make the right type.

**Comment by kalu111** [comment]
Do you have solution to handle **any** type?

Maybe create decorator to skip casting?
```
class Model {
    @Cast(false)
    public value: any;
}
```
Next issue.
How does the @Default() decorator should work?
I use it in that way:
```
class Model {
    @Required()
    public value: number;

     @Default(10)
     public limit: number;
}
```
I send:
```
{
    value: 1
}
```
Does value of property **limit** should be 10? In my case **limit** property is not set. Am I  wrong?

**Comment by Romakita** [comment]
You need to distinguish the converter and the validation concept. 

Converter use type to deserialize an object from his model. The `any` type disable automatically the deserialization for an attribute.

This error "{{name}}.value should be object (type)" is given by AJV not by the converter. So is not a casting problem, just a problem with AJV and the using decorators.

You can find a documentation about jsonSchema decorator here https://romakita.github.io/ts-express-decorators/#/docs/jsonschema

And the validation rules with AJV here https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#type

Actually `@Default` haven't a behavior on the deserialized object. It's just a decorator to describe your schema.

I'll add two new decorators to describe the type correctly  AllowTypes and Any.

**Comment by kalu111** [comment]
A next problem is with "Date" type (ajv included)
```javascript
@Strict(true)
class Model {
    value: Date;
}
```

I send a body:
```javascript
{
    "value": "2018-01-30T23:00:00.000Z"
}
```
An error occur: "{{name}}.value should be string (type)"

**Comment by Romakita** [comment]
Try that:
```typescript
@Strict(true)
class Model {
   @Property()
    value: Date;
}
```

**Comment by kalu111** [comment]
Does not work, too.

**Comment by Romakita** [comment]
Yes it's a bug. AJV need a string to validate the date format, but the object contain a Date object.

**Comment by Romakita** [comment]
@kalu111 Latest version fix the problem with Enum and date validation ;)

**Comment by kalu111** [comment]
Hi,
Validation of numbers and dates works fine ;)
Array of enums, too.

I have found an issue with numbers from query parameters (eg. /?limit=1)

```javascript
class Model {
    public limit: number;
}
```
And I got an error: 
```
{{name}}.limit should be number (type)
```
How to avoid this?

And second question - how to replace _{{name}}_ in error messages? 

What about with @Any(). I can see a new tag in repo?

**Comment by Romakita** [comment]
Normally {{name}} is solved and it should be replaced by the parameters name. I don't why it doesn't work. 
`@any()` is fixed :)

**Comment by kalu111** [comment]
```
{{name}}.limit
```
The "limit" name is included - so maybe {{name}} should be a Model name?

The fix with @any() exists only in master but new tag is not included ;)

https://github.com/Romakita/ts-express-decorators/blob/v3.4.0/src/jsonschema/decorators/any.ts
https://github.com/Romakita/ts-express-decorators/blob/master/src/jsonschema/decorators/any.ts

**Comment by Romakita** [comment]
Hi see, travis-ci had some problem with the build... Some container crash for any reason :/

**Comment by Romakita** [comment]
3.4.1 :)

**Comment by lwallent** [comment]
Hi @kalu111 and @Romakita 

> And second question - how to replace {{name}} in error messages?

I actually though that `{{name}}` relied on some templating stuff further downstream which was the primary reason why I added the `errorFormat` setting to ServerSettings:

```
 ajv: {
        errorFormat: (error) => `At ${error.schema[0]}${error.dataPath}, value '${error.data}' ${error.message}`,
        options: {verbose: true}
     },
```

Anyways, errorFormat will still allow you to change the message

KR

Lasse

**Comment by kalu111** [comment]
Either way, if {{name}} is not used maybe it should be removed or replaced with something else?
I think, that the default implementation should work without an unexpected behaviours.

What do you think?

**Comment by Romakita** [comment]
It'll be replaced by the model class name. 

For the problem with the query param, I thinks the express.query is only an object of {key => value} with the value as string type. It's a problem for me, because, to fix the issue on the date validation, I put the validation before the deserialization.

I've an idea to fix that but I can do that this week. I've another issues/enhancement in the backlog XD.

I'll let you know
See you

**Comment by Romakita** [comment]
#214

**Comment by Romakita** [comment]
I've created new issue for the queryparam validation issue :)

**Comment by kalu111** [comment]
OK, no problem.
Thanks!
