### ISSUE TITLE
@PropertyType decorator 

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#200]
Hi,

```javascript
type Type = 'value' | 'value1';

class Model {
    @PropertyType(Type)
    public types: Array<Type>;
}
```

I can't do that ;(

The "Type" word is misleading.

**Comment by Romakita** [comment]
Type as String, Number, Array or Class ;)

**Comment by Romakita** [comment]
What kind of work you propose to describe a type ?

**Comment by kalu111** [comment]
I need to have validation that each element in given array is only type of "Type". Not else.

**Comment by Romakita** [comment]
It's a problem with Typescript. When you create a type, it's only for the check typing on compile time. After the compilation, the type is lost and the stored metadata is an Object in this case. 
 
The AllowTypes decorators will solve your problem (when it'll be release).

**Comment by Romakita** [comment]
v3.2.0 is release.

You can try this:
```typescript
type Type = 'string' | 'number';

class Model {
    @AllowTypes('string', 'number')
    public types: Array<Type>;
}
```
If the type is a list of value, I haven't decorator to do that actually.

**Comment by kalu111** [comment]
There is no 3.2.0 tag.
I have just download 3.1.0 but I can not see the new decorators.

**Comment by Romakita** [comment]
Problem with the build on travis. It's ok now :)

**Comment by kalu111** [comment]
OK, so how to use these new decorators for property that may have multiple type definition (number, string, or an array)?

**Comment by Romakita** [comment]
AllowTypes have the same behavior described in this AJV documentation http://epoberezkin.github.io/ajv/keywords.html#type

**Comment by kalu111** [comment]
So @Any() and @AllowTypes() are only for items in array?

**Comment by kalu111** [comment]
```javascript
    @AllowTypes('integer', 'number', 'string', 'boolean', 'array', 'object', 'null')
    public type: any;
```
works perfect

but 
```javascript
    @Any()
    public type: any;
```
throws error

**Comment by Romakita** [comment]
@kalu111, I'll investigate on this Any decorator issue. 

This PR https://github.com/Romakita/ts-express-decorators/pull/205 will solve some problems:
- Date validation,
- Enum on array.

See you

**Comment by Romakita** [comment]
Ok "any" keyword type didn't exists :/ . I'll create a patch soon.

**Comment by kalu111** [comment]
Great job! Thanks.
I will leave a feedback tomorrow.

**Comment by kalu111** [comment]
Hi,
Validation of numbers and dates works fine ;)
Array of enums, too.

@Any() still does not work.

I have found an issue with numbers from query parameters (eg. /?limit=1)

```javascript
class Model {
    public limit: number;
}
```
And I got an error: 
```
{{name}}.limit should be number (type)
```
How to avoid this?

And second question - how to replace _{{name}}_ in error messages?
