### ISSUE TITLE
Strict validation

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#203]
Hi,
In ServerSettings there is an option called **validationModelStrict** which has global scope (works for all models). How to disable it on particular model (or how to enable)?
What is for the RouterOptions.strict option?
What is for the @Strict()?

**Comment by Romakita** [comment]
`@Strict()` is used by Express.js but this decorator is not documented sorry.

To answer you, is not possible actually. (All validation part is experimental and as you see, isn't stable XD).

**Comment by kalu111** [comment]
Do you have any plan to figure out my all issues?

**Comment by Romakita** [comment]
Maybe this week or the next week.

**Comment by Romakita** [comment]
I work on your other issue on AJV validation in first :)

**Comment by Romakita** [comment]
Spec:
```typescript
@ModelStrict(true/false)
class MyModel {

}
```

**Comment by kalu111** [comment]
+1
