### ISSUE TITLE
Enum Array Decorator for Array

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#209]
Hi @Romakita,

Given that my beautiful EnumArray decorator didn't make it ;-) 
... allow me to ask a question

Shouldn't it be possible to extract the type from the passed Enums?

Assume we have an enum:
````
export enum SomeEnum {
    ENUM_1 = 'ENUM_1', ENUM_2 = 'ENUM_2'
}
````

and we wish to use these with Ajv - then we currently have to do the following;

````typescript
@Property({use:String})  // <---------------Needed else the type will be object
@Enum(SomeEnum.ENUM_1, SomeEnum.ENUM_2)  
someEnums?: SomeEnum[];
````

The schema: (with string)
```
    { items: { enum: [ 'ENUM_1', 'ENUM_2' ], type: 'string' },
        type: 'array' },
```

The schema: (without string)
```
    { items: { enum: [ 'ENUM_1', 'ENUM_2' ], type: 'object' },
        type: 'array' },
```

Perhaps one should look at the type passed in?

KR

Lasse

**Comment by Romakita** [comment]
Haaa, now I understand why you need a decorator to do that XD.

I think we can do that:
```typescript
@Enum(SomeEnum)  
someEnums: SomeEnum[];
```
Enum will detect if the argument is an Object (TypeScript enum) and set the type as string.
I thinks it's possible :) 

PR ?

Romain

**Comment by lwallent** [comment]
Hi @Romakita 
Yes, really that is what we need. 👍 
I am not sure I can do a PR right now. I will just have to get my codebase to work with TsED 3.4.1 first :-) Ajv is not really behaving - maybe I was too early to adopt? :-)   
KR
Lasse

**Comment by Romakita** [comment]
I'll work on ;)
