### ISSUE TITLE
ReadOnly / WriteOnly properties on Models?

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#215]
Sometimes a model has properties that one wish to send on GET and either Ignore or throw an error when used In PUT or POST. These would be considered ReadOnly.

Sometimes it is the other way around you allow data to flow in but will not let the user see what is already there (this may not be as common). These properties are WriteOnly. 

Swagger and Ajv (the schema) supports the notion of readOnly and writeOnly properties.

It would be nice to be able to define two modes for ReadOnly/WriteOnly:
* **throw**: Throw an error if the property is there (in the direction where it is not supposed to)
* **ignore**: Simply do not include the property in serialization/deserialization if it is there  (in the direction where it is not supposed to)

The _ignore_ mode could possibly be helpful when API users send the same data back in, but you wish to exclude the data from flowing further downstream on the server side.

There already is a ReadOnly and Writable decorator, but that is for a different purpose. 

Does this make sense? Is it just me who think this could be quite usable?

KR 

Lasse

**Comment by Romakita** [comment]
I never do that before, so I haven't experience over that. But I understand your needs and I agree, we need this feature. 

The Readonly and Writable are exposed in the core module but I'm not sure if it's used by the developers.

ajv and swagger can expose his own readonly decorator. Isn't not problem ;)

See you,
Romain
