### ISSUE TITLE
value 'null' should be object?

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#216]
## Description
When the an object reference is null the validation fails even though null should be allowed. This seems to be caused by the additional type property?

## Example 

Using the following model:

```typescript
export class Stuff {
    @Property()   
    name:string;
}

export class Thingy  { 
    @Property()    
    @AllowTypes("object", "null") // <------- Allow it to be null ?
    stuff?: Stuff;
}

```

Creating a simple Controller:
```typescript
@Controller("/tests")
export class TestCtrl {
    @Put("/:id")
    @Returns(Thingy)
    async update(@PathParams("id") @Required() id: string,
                 @BodyParams() thingy: Thingy): Promise<Thingy> {                
        return null;
    }
}
```

Launch the server. Call the endpoint with the following body:

```
{
  "stuff":null
}
```

In AjvService the `ajv.validate(schema, obj)` is then called with the *schema*:

```
{ properties: { stuff: { '$ref': '#/definitions/Stuff', type: [ 'object', 'null' ] } },
  type: 'object',
  definitions: { Stuff: { properties: { name: { type: 'string' } }, type: 'object' } } }
``` 

and the *obj*:

```
{ stuff: null }
```

This will make the validate call throw the following error:

```
$ref: keywords ignored in schema at path "#/properties/stuff"

AJV errors:  [ { keyword: 'type',
    dataPath: '.stuff',
    schemaPath: '#/definitions/Stuff/type',
    params: { type: 'object' },
    message: 'should be object',
    schema: 'object',
    parentSchema: { properties: [Object], type: 'object' },
    data: null } ]

BAD_REQUEST(400): At Thingy.stuff, value 'null' should be object

```

Is this not how to make it accept null values?

Type | Version
---|---
Bug | 3.5.0

****

**Comment by kalu111** [comment]
Did you try with default value of property?

```javascript
class Thingy  { 
    @Property()    
    @Allow(null)
    stuff?: Stuff = null;
}
```

**Comment by lwallent** [comment]
hi @kalu111 

I tried the `@Allow(null)` with no luck.

KR

Lasse

**Comment by lwallent** [comment]
I have looked some more at it :-)

I have produced 3 different versions of the schema that make it behave the way I want it to :-)

Now the question is what to do about it.

I believe that option 3 is probably the preferred choice?

How one should then produce the schema in option 3 is yet another question - should one solve this with:

1.  an `@OnOff(null,Stuff)` approach, or
2. an `@Allow(null)` approach which adds the null to the oneOf, or

I do not think` @AllowTypes('object','null')` makes as much sense here?

@Romakita what do you think? Do you have any thoughts on this?

Below is the original schema and the 3 options to make validation pass.


**Original Schema**
```
{ 
  properties: { 
    stuff: { '$ref': '#/definitions/Stuff' }
  },
  type: 'object',
  definitions: { 
    Stuff: { 
      properties: { name: { type: 'string' } }, type: 'object' } 
   }  
}
```

**Option 1**
If I remove the type object from the Stuff definition:

```
{ 
properties: { 
    stuff: { '$ref': '#/definitions/Stuff' } 
},
type: 'object',
definitions: { 
  Stuff: { 
    properties: { name: { type: 'string' } } } }
}
```
validation passes!

**Option 2**
If I add the null type to the Stuff definition:

```
{ properties: { stuff: { '$ref': '#/definitions/Stuff' } },
  type: 'object',
  definitions:
   { Stuff:
      { properties: { name: { type: 'string' } },
        type: [ 'object', 'null' ] } } }
```

validation passes!

**Option 3**
If I use **oneOf** the null check can be moved from definitions to property:

```
{ 
 properties: { 
    stuff: { oneOf: [ 
                               { type: 'null' }, 
                               { '$ref': '#/definitions/Stuff' } 
                          ] } 
  },
  type: 'object',
  definitions: { Stuff: { properties: { name: { type: 'string' } }, type: 'object' } } }
```

this also makes validation pass!
