### ISSUE TITLE
mounting endpoints .ts file names not replaced with .js when running outside ts-node

### ISSUE THREAD

**Issue by scopsy** [Romakita/ts-express-decorators#220]
My current server config is:

```
const rootDir = Path.resolve(__dirname);
@ServerSettings({
    rootDir,
    mount: {
        '/v1': `${rootDir}/controllers/**/**.controller.ts`
    },
    componentsScan: [
        `${rootDir}/services/**/**.service.ts`
    ],
    httpPort: process.env.PORT || 3000,
    httpsPort: false,
    acceptMimes: ['application/json'],
    swagger: {
        path: '/api-docs'
    }
})
```

when running with ts node from "./src" folder works like a charm.

but when building to dist folder and compiled to js the scanner can't find any files since it looks for .ts files.

when manually changing to .js extensions it works in prod build but fails in dev mode.

```
    componentsScan: [
        `${rootDir}/services/**/**.service.{ts,js}`
    ],
```
Doing the fix above resolves the issue, but i noticed the documentation stated it should be done automaticly when not using ts-node. 

Did I miss something ?

**Comment by Romakita** [comment]
Hi @scopsy ,
Yes, normally the .ts extension is automatically replaced by .js if the .ts extension is not supported by the runtime. (See https://github.com/Romakita/ts-express-decorators/blob/master/src/server/components/ServerLoader.ts#L594-L598).

Can you try this condition in both profile please:
```typescript
console.log("TS runtime ?", !!require.extensions[".ts"])
```
See you,
Romain

**Comment by scopsy** [comment]
I think i found the issue, because im running the prod from dist folder which does not contain any ts files the issue is 
```
const files = require("glob").sync(path);
```
called with the wrong path (.ts) path and since it's not finding any files the files array is empty.

if i add 
```
        const files = require("glob").sync(ServerLoader.file(path));
```

It works as expected

**Comment by Romakita** [comment]
haaa ok :) Nice job.

**Comment by scopsy** [comment]
@Romakita I would also suggest changing the ServerLoader.file function to be more fine grained regarding the replace function.

Using regex for replacing only .ts in the end of the file name instead of general replace would be better.

If someone for some reason will have `.ts` as part of their file naming convention (file.tsuname.ts) it will lead to weird bugs :)

Do you want me to create a PR ?

**Comment by Romakita** [comment]
You can create a PR if you have a time ;)
