### ISSUE TITLE
Building with webpack

### ISSUE THREAD

**Issue by crisdanilo** [Romakita/ts-express-decorators#224]
I'm trying create a build with webpack in a project with angular 5, but I can not create the build with ts-express-decorators#3.8.1

WARNING in ./node_modules/ts-express-decorators/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./src/server/index.ts 15:0-69

WARNING in ./node_modules/ts-express-decorators/lib/server/components/ServerLoader.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/ts-express-decorators/lib/server/index.js 9:21-57
 @ ./node_modules/ts-express-decorators/lib/index.js
 @ ./src/server/index.ts

**Comment by Romakita** [comment]
Hi @crisdanilo ,
Your problem is that you mix your webpack project and your Backend server.
You need to separate your back-end server file from your front-end project.

See you :)

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/issues/79
