### ISSUE TITLE
A good way to inject service into middlewares

### ISSUE THREAD

**Issue by vincent178** [Romakita/ts-express-decorators#23]
Hi @Romakita ,

is there a good way to inject service into middleware?

For example:

I have a middleware called `currentUser`, it's just a basic express middleware which receive three parameters: req, res, next. The currentUser aims to get the userId from session, and use `UserService` to get the user information.

**Comment by Romakita** [comment]
Hello @vincent178,

You can use the InjectorService to get your service in a middleware function:
```typescript
function middleware(req, res, next){

}
```

**Comment by vincent178** [comment]
Thank you, this is very useful.
