### ISSUE TITLE
join to translate English into Indonesian

### ISSUE THREAD

**Issue by rabooe** [Romakita/ts-express-decorators#236]
## Informations

Type | Version
---|---
Improvement | 4.x

**Comment by Romakita** [comment]
Hooo nice :) 

I use https://github.com/QingWei-Li/docsify to produce the documentation. Translation is also supported but not configured for Ts.ED.

Documentation configuration is here https://github.com/Romakita/ts-express-decorators/blob/master/docs/index.html#L228

You have a npm task to build documention:
```bash
npm run doc:build
```
And another one to preview the website (localhost:3000):
```bash
npm run doc:serve
```
Tell me if you need something? 

See you,
Romain

**Comment by rabooe** [comment]
thank-you ser, I will give my best

**Comment by Romakita** [comment]
Hi @rabooe
If Iyou haven't started your work about the translation, I can help you, create the branch and configure docsify with the multilang options, this week ;)

See you
Romain

**Comment by Romakita** [comment]
Hi @rabooe 

I've created a new branch with the localization feature on the website. 
You can fork this https://github.com/Romakita/ts-express-decorators/tree/docs_improve_docs

I've added an example with the Fr localization. (`docs/fr`).

Tell me if you have a question or problem :)

See Romain

**Comment by Romakita** [comment]
Hi @rabooe ,

Multi localization is in production :) https://romakita.github.io/ts-express-decorators/#/

See you,
Romain

**Comment by rabooe** [comment]
okay mr, i will learn this project, then i will give best 

thanks
