### ISSUE TITLE
Ignore properties using a decorator

### ISSUE THREAD

**Issue by joakimbugge** [Romakita/ts-express-decorators#238]
## Information

Type | Version
---|---
Improvement/Question | 3.10.2

****

## Description
Is there a way to prevent properties from being serialized when a model is returned from a controller using a decorator? A typical use case is to prevent the password property from being exposed to the client.

```TypeScript
export class User {
    id: number;
    @JsonProperty('username');
    email: string;
    @Ignore()
    password: string;
}
```

I've currently solved this by implementing a `toJSON` method returning only the properties I want to expose, but I would like to have a decorator for this purpose as well, to keep with the theme of the library.

**Comment by Romakita** [comment]
Hi @joakimbugge ,
This decorator don't exists actually, but It's a nice Idea :)

I'll add this feature to the backlog :)

See you,
Romain

**Comment by joakimbugge** [comment]
@Romakita This is my first shot at TypeScript, but I'll have a look at it as soon as I've got time and I'll create a pull request if I find a decent solution.

**Comment by Romakita** [comment]
@joakimbugge No problem. You can look on this file https://github.com/Romakita/ts-express-decorators/blob/master/src/converters/services/ConverterService.ts#L59

The serializer use Property metadata to get configuration for each property (L.89).

For the decorator, you have a lot of example here: https://github.com/Romakita/ts-express-decorators/tree/master/src/jsonschema/decorators . Just check if the ignore option exist exists on JsonSchema ;)

See you,
Romain

**Comment by Romakita** [comment]
Hi @joakimbugge 
PR #259 is ready
