### ISSUE TITLE
SocketIO Redis Adapter - not working in cluster

### ISSUE THREAD

**Issue by ryanpager** [Romakita/ts-express-decorators#240]
## Information

Type | Version
---|---
Question | 2.18.1

****

## Description
When trying to use socket IO on the server, we have a 2 server setup and need to use redis as the intermediary adapter. I have set up the adapter options like this:

```
import * as ioRedis from 'socket.io-redis';

const socketIO: any = {
  serveClient: false,
  origins: '*',
};

if (config.REDIS_HOST && config.REDIS_PORT) {
  socketIO.adapter = ioRedis({
    host: config.REDIS_HOST,
    port: config.REDIS_PORT,
  });
}
```

This is registering on the server without any issue at all -- but when an event comes through, it does not get emitted to both nodes. A sample emit event is the following,

```
io.to(`user:${friend.friendId}`).emit('receive', {
        eventName: 'user:online-status',
        payload: {
          id: decoded.session.user.id,
          status: onlineStatus,
        },
      })
```

Is there a step im missing, or something like that in order to get the event to broadcast to both nodes?

**Comment by Romakita** [comment]
Hi @ryanpager,

If you have installed the socket.io  server Ts.ED, you need to configure the socket.io with the Adaptater.

I think it should be something like that:

In your server:
```typescript
import {ServerLoader, ServerSettings} from "ts-express-decorators";
import "ts-express-decorators/socketio"; // import socketio Ts.ED module

@ServerSettings({
    rootDir: __dirname,
    socketIO: {
        // ... see configuration
    },
   socketIORedis: {
     host: 'localhost', 
     port: 6379 
   }
})
export class Server extends ServerLoader {

}
```
Then in the service:
```typescript
import * as SocketIO from "socket.io";
import {SocketService, IO, Nsp, Socket, SocketSession} from "ts-express-decorators/socketio";

const redis = require('socket.io-redis');

@SocketService("/my-namespace")
export class MySocketService {

    @Nsp nsp: SocketIO.Namespace;

    constructor(@IO private io: SocketIO.Server, serverSettings: ServerSettingsService) {
         io.adapter(redis(serverSettings.get("socketIORedis"));
    }
}
```
Try this configuration and tell me if it works :)
See you,
Romain

**Comment by ryanpager** [comment]
@Romakita 

Worked super great -- thanks a ton. One thing to note -- theres a setting on the socketIO config called 'adapter' which doesn't seem to do anything; if this is the normal way to do that setup -- should the docs change?

Id be happy to do a PR with the docs change if needed.

**Comment by Romakita** [comment]
@ryanpager I think it's the default interface to configure the Socket server (SocketIO.ServerOptions).

https://github.com/Romakita/ts-express-decorators/blob/master/src/socketio/services/SocketIOService.ts#L28

But the documentation can be improved with an example to adding an Adaptater ;)
PR are welcome :)

See you,
Romain

**Comment by Romakita** [comment]
#243
