### ISSUE TITLE
Can't compile 4.0.0, invalid reference?

### ISSUE THREAD

**Issue by Ravendarksky** [Romakita/ts-express-decorators#246]
## Information

Type | Version
---|---
Bug | 4.0.0

****

## Description
Getting error when compiling after upgrading to the latest version.

```
Cannot find module '../../common/config/services/ServerSettingsService' in 
node_modules\@tsed\swagger\lib\services\SwaggerService.d.ts
```

Looking at the path it looks like it should be something more like:

```
import { ServerSettingsService } from "../../../common/lib/config/services/ServerSettingsService";
import { ControllerService } from "../../../common/lib/mvc/services/ControllerService";
```

Sorry if this isn't an issue and I'm missing something obvious here.

**Comment by Romakita** [comment]
Hello @Ravendarksky ,
I'll fixed it quickly. v4 has a new architecture and some bug with the dependencies is possible.

See you
Romain

**Comment by Romakita** [comment]
Hello @Ravendarksky 
Normally it's fixed with the version 4.0.4 ;)

See you,
Romain

**Comment by Ravendarksky** [comment]
HI Romakita,

Thanks for the speedy reply! I upgraded my project to V3.10.2 today and I've just given an upgrade to V4.0.4 a go tonight. I'm hitting another issue though which may be similar to the first one? I did a npm clear cache and fresh install to make sure it's nothing at my end.

```
Exception has occurred: Error
Error: Cannot find module '../../common/jsonschema/class/JsonSchema'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (xxx\node_modules\@tsed\src\swagger\class\OpenApiPropertiesBuilder.ts:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

(also spotted there is still an old reference to ts-express-decorators/testing on: https://romakita.github.io/ts-express-decorators/#/docs/testing ).

Thanks again for all your hard work, we are using this in several projects

**Comment by Romakita** [comment]
Hi @Ravendarksky ,

I hope with the 4.0.5, the problem is fixed. New architecture with multi packages on npm change the internal dependencies between each Ts.ED. In fact, all relative paths (as in your error) must be replaced by `@tsed/common` import. Unfortunately, in development, the relative path work fine and didn't emit errors T.T and unit test don't cover this problem...

That explain why I have some relative link in the npm module. My apologies. 

I'll find a solution to prevent this problem in future :)

See you,
Romain

**Comment by Ravendarksky** [comment]
Hi @Romakita. I've got my project upgraded to 4.0.5 and integration tests are passing. Thanks very much again for your hard work!
