### ISSUE TITLE
Object in Allow Types Swagger Decorator?

### ISSUE THREAD

**Issue by Ravendarksky** [Romakita/ts-express-decorators#247]
## Information

Type | Version
---|---
Question | 4.0.5
****

## Description
Is it possible to specify the type of an array if it's not a primitive type? I've been trying out the allowtypes decorator but can't see how to specify an Object. 
```typescript
@Title('My Property example')
@Description('An array of MyObject')
@AllowTypes(string, MyObject) // Included string just for this example
@JsonProperty()
myProp?: Array<MyObject>;

// An array with allowed types of string and MyObject
"myProp": {
    "items": {
        "type": [
            {
                "type": "object",
                "schema": {
                    "$ref": "#/definitions/MyObjectRef"
                }
            },{
                "type": "string"
            }
        ]
    },
    "description": "An array of MyObject",
    "title": "My Property example",
    "type": "array"
}

"definitions": {
    "MyObjectRef": {
        "type": "object",
            "properties": {
            "someId": {
                "type": "string"
            },
            "someOtherObject": {
                "$ref": "#/definitions/AnotherObjectRef"
            }
        }
    }
}
```
https://romakita.github.io/ts-express-decorators/#/api/common/jsonschema/allowtypes

**Comment by Romakita** [comment]
Hi @Ravendarksky 

For a property with a complex type you can do that:

```typescript
class Model {
      @PropertyType(String)
      property: string[];
}
````
AllowTypes is for validating your data with AJV.

https://github.com/Romakita/ts-express-decorators/blob/master/src/common/jsonschema/decorators/propertyType.ts

If the documentation isn't clear, PR are welcome :)

See you,
Romain

**Comment by Ravendarksky** [comment]
Hi @Romakita, What I'm trying to do is find a way of seeing the allowed type for the array in the generated swagger doc/swagger.json file.

PropertyType works for validating the actual passed data, but it doesn't help me define what this is to the person looking at swagger JSON / UI

```
    @Title('Some Object')
    @Description('Details of object)
    @AllowTypes('object')
    @PropertyType(MyObject)
    @JsonProperty()
    @Example('TODO')
    someObject: Array<MyObject>;
```

produces:

```
"someObject": {
    "items": {
        "type": [
            "object"
        ]
    },
    "example": "TODO",
    "description": "Details of object",
    "title": "Some Object",
    "type": "array"
}
```

**Comment by Romakita** [comment]
@Ravendarksky Try that:

**Comment by Romakita** [comment]
PropertyType already apply a JsonProperty. AllowTypes is here for apply a multi  primitive types (string, number, etc...). 

See you

**Comment by Ravendarksky** [comment]
Like that I get the same output in swagger.JSON :

No way to see from the swagger what the structure to the objects in this array is.
```
"someObject":{
   "items":{
      "type":"object"
   },
   "example":"TODO",
   "description":"Details of object",
   "title":"Some Object",
   "type":"array"
}
```

**Comment by Romakita** [comment]
MyObject has a Schema ? (Attribut with Property decorator) 

```typescript
class MyObject {
  @Property()
  attr1: string;
}
```

By default, if a class is used and hasn't a property description, the type will be an object instead of the Schema class.

**Comment by Ravendarksky** [comment]
Hi @Romakita. Sorry for not giving you the full picture. Here is the my object class
```
class MyObject {
    @Title('First Prop')
    @Description('I am the first prop')
    @JsonProperty()
    @Example('12')
    firstProp: number;

    @Title('Second Prop')
    @Description('I am the second prop')
    @JsonProperty()
    @Example('50')
    secondProp: number;
}
```

Here is what the swagger generates for it: 
```
"MyObject": {
            "properties": {
                "firstProp": {
                    "example": "12",
                    "description": "I am the first prop",
                    "title": "First Prop",
                    "type": "number"
                },
                "secondProp": {
                    "example": "50",
                    "description": "I am the second prop",
                    "title": "Second Prop",
                    "type": "number"
                }
            },
            "type": "object"
        },
```

**Comment by Romakita** [comment]
Ok, I've found a bug when the Example decorator is used. Remove the example (just for test) and tell me if it works.

**Comment by Ravendarksky** [comment]
Nice catch! I've removed the example and it's working.

"someObject": {
                    "items": {
                        "$ref": "#/definitions/MyObject"
                    },
                    "type": "array"
                },
