### ISSUE TITLE
@Returns (@tsed/swagger) can't specify types with generics

### ISSUE THREAD

**Issue by Ravendarksky** [Romakita/ts-express-decorators#248]
## Informations
Type | Version
---|---
Bug| 4.0.5
****
I can't seem to set return values which include generics
## Description
`@Returns(200, { description: 'Success', type: Array<string> })`

`@Returns(200, { description: 'Success', type: PagingModel<SomeOutboundModel> })`

**Comment by Romakita** [comment]
Hi @Ravendarksky 

Typescript don't give the right metadata type when we use a generic type.

Example:
```typescript
string => String
Array<string> => Object or Array (not sure)
PagingModel<SomeOutboundModel> => Object
```

For the array you have this decorator : https://github.com/Romakita/ts-express-decorators/blob/master/src/swagger/decorators/returnsArray.ts

For other generic type, unfortunately , you need to write your Schema manually.

See you,
Romain

**Comment by Ravendarksky** [comment]
Thanks for letting me know! Looks like I'll remove the generics from my code and have a Model per controller response instead.
