### ISSUE TITLE
Logger configuration in ServerSettings doesn't seem to change logger output.

### ISSUE THREAD

**Issue by dennisli92** [Romakita/ts-express-decorators#249]
## Informations

Type | Version
Bug|4.0.5

****

## Description
Modifying the logger configuration in ServerSettings does not do anything. I've tried this in v2.7 as well, and it wasn't working then either.

I'm setting up my server with a limited subset of logger requestfields (or even none at all), but it still prints the whole request. This is an issue because I'd like to keep the request body hidden.
```
backend_1        | [Node] [2018-02-21T02:34:47.439] [INFO ] [TSED] - settings.logger => { requestFields:
backend_1        | [Node]    [ 'reqId',
backend_1        | [Node]      'method',
backend_1        | [Node]      'url',
backend_1        | [Node]      'headers',
backend_1        | [Node]      'query',
backend_1        | [Node]      'params',
backend_1        | [Node]      'duration' ] }
```

`body` is missing, but when my server receives a request, it still prints `request.body.
```
backend_1        | [Node] [2018-02-21T02:34:48.506] [DEBUG] [TSED] - {
backend_1        | [Node]   "status": ...,
backend_1        | [Node]   "reqId": "1",
backend_1        | [Node]   "method": "POST",
backend_1        | [Node]   "url": ...
backend_1        | [Node]   "duration": ...
backend_1        | [Node]   "headers": ...
backend_1        | [Node]   "body": {
backend_1        | [Node]     "username": "...",
backend_1        | [Node]     "password": "...."
backend_1        | [Node]   },
backend_1        | [Node]   "query": {},
backend_1        | [Node]   "params": {}
backend_1        | [Node] }
```

**Comment by Romakita** [comment]
Normally the log come from this class https://github.com/Romakita/ts-express-decorators/blob/master/src/common/mvc/components/LogIncomingRequestMiddleware.ts#L102-L110

I'll test if there is a problem. If you find a fix before me you can create a PR :)

See you,
Romain

**Comment by dennisli92** [comment]
Sorry about the late reply, but looks like that fixed it. I had set debug on the top level to false, too, though.

**Comment by Romakita** [comment]
Hi @dennisli92 
I confirm with v4.4.1, the configuration given previously works fine.
You can checkout this example https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-basic

I don't know in you case why the body is printed. Possible reasons are:
- You have a overridden the LogIncomingRequestMiddleware,
- You have a bad configuration on ServerSettings level. 

Can you send me you ServerSettings Configuration ?
See you
Romain

**Comment by dennisli92** [comment]
oh oops, i dropped a word there. I meant to say that i had _to also_ set `debug` in the top level to false, too. Here are my current ServerSettings:

```
@ServerSettings({
  rootDir,
  port: PORT,
  httpsPort: false,
  mount: {
    '/api/v1/': `${rootDir}/controllers/**/*.js`,
  },
  acceptMimes: ['application/json'],
  debug: false,
  componentsScan: [
    `${rootDir}/services/**/**.js`,
    `${rootDir}/middlewares/**/**.js`,
  ],
  logger: {
    debug: false,
    logRequest: true,
    requestFields: ['reqId', 'method', 'url', 'headers', 'query', 'params', 'duration'],
  },
})
```

This config works, but if I throw an error in the controller then it seems that the original request gets printed. e.g.
```
backend_1        | [Node] [2018-03-09T07:57:46.274] [ERROR] [TSED] - {
backend_1        | [Node]   "error": {
backend_1        | [Node]     "status": 500,
...
backend_1        | [Node]   },
backend_1        | [Node]   "body": {
backend_1        | [Node]     "username": "...",
backend_1        | [Node]     "password": "..."
backend_1        | [Node]   },
```

**Comment by Romakita** [comment]
Hooo the log is an error level...
Actually the filters rules are applied only on the log level info.

Debug print all field and Error level too.

I think you need to override the LogIncomingRequestMiddleware. Here the documentation to do that:
https://romakita.github.io/ts-express-decorators/#/configuration?id=request-logger

See you,
Romain

**Comment by Romakita** [comment]
@lwallent What do you think about filtering the console output when a request error is logged ?
