### ISSUE TITLE
@EndpointInfo endpoint is undefined in middleware

### ISSUE THREAD

**Issue by dennisli92** [Romakita/ts-express-decorators#250]
## Informations

Type | Version
Question|4.0.5

****

## Description
Following the example on https://romakita.github.io/ts-express-decorators/#/docs/middlewares/endpoint-middleware, I get an error that `endpoint is undefined` for my middleware.

Decorator:
```
export function Foo(options: Options) {
  return Store.decorate((store) => {
    store.set(middleware, { options })
    return UseBefore(Middleware)
  })
```

Middleware:
```
@Middleware()
export default class FooMiddleware implements IMiddleware {
  public use(
    @Request() request,
    @EndpointInfo() endpoint: EndpointMetadata,
    @Response() response: Express.Response,
    @Next() next: Express.NextFunction,
  ) {
    ...
  }
}
```

## Todos

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Where have you adding you middleware ?

The endpoint info is only available on a controller method. 
Example:

```typescript
@Controller("/")
export class Ctrl {
 
   @Get("/")
   @UseBefore(MyMiddleware)
   get() {
     
   }
}
```

With a decorator:
```typescript
export function Foo(options: Options) {
  return Store.decorate((store) => {
    store.set("middleware", { options })
    return UseBefore(FooMiddleware)
  })
```

```typescript
@Controller("/")
export class Ctrl {
 
   @Get("/")
   @FooMiddleware()
   get() {
     
   }
}
```

See you ;)

**Comment by dennisli92** [comment]
Ah, I see. I was using it on a controller. Is there anything similar to `@EndpointInfo` if I want to access the decorator store when applying it to the entire controller?

**Comment by Romakita** [comment]
## Info
Here the code where the middleware are added for an endpoint:
https://github.com/Romakita/ts-express-decorators/blob/master/src/common/mvc/class/EndpointBuilder.ts#L53-L70

Example of  the UseBefore decorator: 
https://github.com/Romakita/ts-express-decorators/blob/master/src/common/mvc/decorators/method/useBefore.ts

The endpoint metadata (method to adding a middleware before endpoint):
https://github.com/Romakita/ts-express-decorators/blob/master/src/common/mvc/class/EndpointMetadata.ts#L77

**Comment by dennisli92** [comment]
Got it. Thanks so much for the quick response!
