### ISSUE TITLE
SocketIO middlewares

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#252]
Hi,
Is it possible to set middleware for socket event?

**Comment by Romakita** [comment]
Hello @kalu111 ,
Is not possible actually. Socket.io don't provide a middleware mechanism. Sorry :/

See you,
Romain

**Comment by kalu111** [comment]
Yes, I known that :) 
But, what about the new feature with similiar behaviour?
In my projects I very often have to check that socket is authorized before handle event listener.
What do you think to implement such feature?

It would be a event method decorator or special method in main Server class. 

Other usefull and linked feature is error handling for event listeners. After throw an error we can use @EmitError(eventName) to catch an error and send error.message to user.

**Comment by kalu111** [comment]
Ping :)

**Comment by Romakita** [comment]
Hi @kalu111,

We can plan new feature to handle error. Actually, I work on the new website (Localisation) for Ts.ED. 
I keep in mind your propositions ;)

See romain

**Comment by Romakita** [comment]
Proposal:

```typescript
import {SocketService, SocketUse, Emit, Input, Args, SocketSession} from "@tsed/socketio";

@SocketService("/my-namespace")
export class MySocketService {
    @Input("eventName")
    @Emit("responseEventName") // or Broadcast or BroadcastOthers
    @SocketUse(MySocketMiddleware)
    async myMethod(@Args(0) userName: string, @SocketSession session: SocketSession) {

        const user = session.get("user") || {}
        user.name = userName;

        session.set("user", user);

        return user;
    }
}
```

The middleware:
```typescript
@SocketMiddleware()
export class MySocketService {
    async myMethod(@Args(0) userName: string, @SocketSession session: SocketSession) {

    }
}
```
If you have any idea. Tell me :)

**Comment by kalu111** [comment]
Thanks for quick answer and proposal.
I have a few quiestions.
1. Can we inject `@Socket()` to `@SocketMiddleware()` and `@SocketMiddlewareError()` method?
2. What instance of is `@SocketErr()`?
3. If we throw an error in `@SocketMiddleware()`  or in `event handler` then `@SocketMiddlewareError()` will catch it both?
4. It is a big problem to implement a middleware that can override an `@Args()` values?.  It wolud be great to have similar feature to express Models and Converters :)

**Comment by Romakita** [comment]
1. Yes, all socket decorators will be available.
2. SocketErr is required by me to inject the potential error when an error occur.
3. SocketMIddlewareError will catch all error for a middlewares chain.
4. Args return an array. By reference it's possible to change the value. But, I'm not sure if it's a good practice. I think a middleware can return the array of data with the updated values (or not).

```typescript
@SocketMiddleware()
export class MySocketService {
    async myMethod(@Args() data: any[], @SocketSession session: SocketSession) {

      //By reference
     data[0] = "otherValue";
      // or return value
      return [
          "otherValue2"
      ];
    }
}
```
4. Model and converters? Why not :)

**Comment by kalu111** [comment]
OK, all sounds great!

Regarding to middlewares chain - the returning value will be passed to the another middleware as a `@Args()`?

**Comment by Romakita** [comment]
Yes :)

**Comment by kalu111** [comment]
OK, I have no questions for now.
I think it is good proposal :)

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/tree/feat_socket_middlewares

**Comment by kalu111** [comment]
It looks nice ;)
Is it final version?

**Comment by Romakita** [comment]
Maybe. I haven't implemented unit test.

**Comment by kalu111** [comment]
I can't wait.
It will resolve the most of my issues :)

**Comment by Romakita** [comment]
You can checkout this branch and test it, but I'm not sure if it work fine.

**Comment by Romakita** [comment]
I'll try to finish this branch today, if I've a time

**Comment by Romakita** [comment]
@kalu111 Branch is tested and covered :). You can test it ;)

**Comment by Romakita** [comment]
released with v4.8.0

**Comment by kalu111** [comment]
What about models and conventers? Do you plan such feature in near feature?

**Comment by Romakita** [comment]
Why not =).

**Comment by virus2016** [comment]
Hey @Romakita,

Do converters work with socket.io?

**Comment by Romakita** [comment]
Yes converters works ;)

**Comment by virus2016** [comment]
We are on 5.60.2.

**Comment by virus2016** [comment]
Think we have to use @ignore rather than @ignoreproperty. Thanks again @Romakita!

**Comment by Romakita** [comment]
;)

**Comment by virus2016** [comment]
Hey @Romakita, 

We can't seem to get it working. Can you have a look below:

```typescript
    @InputAndEmit(DatabaseSocketEventEnum.test)
    @Returns(IExampleResponse)
    public async test(
        @Args(0) data: IExampleRequest,
        @SocketSession session: SocketSession,
        @Socket socket: SocketIO.Socket,
    ): Promise<IExampleResponse> {

        return {
            name: data.name,
            notToReturn: data.notToReturn,
        };
    }

```

```typescript

class IExampleRequest {
    @Property()
    name: string;

    @Property()
    notToReturn: string;
}

class IExampleResponse {
    @Property()
    name: string;

    @Ignore()
    notToReturn: string;
}
```

I have tried to use the returns but that doesn't work. Can you point me in the right direction?

Many thanks,
Cal

**Comment by Romakita** [comment]
Ha sorry. The converter is only available on input parameters. The returns decorators doesn't have effect here.
Can you create a new issue (and add hacktoberfest label) with your expectation :) 

The problem is here https://github.com/TypedProject/tsed/blob/production/packages/socketio/src/class/SocketHandlersBuilder.ts#L265 
The serializer method isn't called :) The PR is pretty simple ;)
