### ISSUE TITLE
ConverterService ignore property decorators

### ISSUE THREAD

**Issue by mduthilleul** [Romakita/ts-express-decorators#257]
## Informations

Type | Version
BUG | 4.0.7

****

The ConverterService doesn't use property decorators.
For example it will render every properties of an object, not only those marked with @Property.
It will also ignore getter/setter properties.
Whereas the swagger doc is generated correctly

Here is a little patch that does the trick : https://github.com/mduthilleul/ts-express-decorators/commit/c51d92818176f0a520ca3b31d527bd79b85cd60f
ConverterService doesn't use property decorators.
Didn't have time yet to properly test this or add TU, so didn't make PR

**Comment by Romakita** [comment]
Hi @mduthilleul 
Is not a bug. By default Converter use a strict model conversion and Property annotation to render you object (See: https://romakita.github.io/ts-express-decorators/#/docs/converters?id=validationmodelstrict-options).

You can change this behavior with the server configuration or the ModelStrict annotation.

See you,
Romain

**Comment by mduthilleul** [comment]
Thanks for the quick answer !
Unfortunatly I submit the bug report by inadvertence before finishing it.
My problem is about object serialization, not validation.

Let say I have an API endpoint that return an User with class defined as follow : 
`class User {
  _id : string
  @Property() name: string
}` 

I expect the JSON to be rendered as : 
`{ "name": "Jean" }`

**Comment by Romakita** [comment]
Well, it's the same problem with the converter. 

You can try that:
```typescript
@ModelStrict(false)
class User {
   _id: string;
   @Property()
   name: string;
}
```

or 

Add the annotation on all property.
```typescript
class User {
   @Property()
   _id: string;
   @Property()
   name: string;
}
```

**Comment by mduthilleul** [comment]
Thanks for the quick answer !
Unfortunatly I submit the bug report by inadvertence before finishing it.
My problem is about object serialization, not validation.

Let say I have an API endpoint that return an User with class defined as follow :
`class User {
  _id : string
  @Property() @Example("Jean") name: string
}`

I expect the JSON to be rendered as :
`{ "name": "Jean" }`
as is appears in the swagger documentation example

But actually the endpoint returns : 
`{ "_id": "1234", "name": "Jean"}`

I was excepting the _id property which it not annoted with Property decorator to not render.
But maybe it's not the intented behavior ?

Also `@ModelStrict(false)` have no effect.

Thank you !

**Comment by Romakita** [comment]
Can you send me your ServerSettings configuration?

**Comment by mduthilleul** [comment]
````json
{
rootDir: path.resolve(__dirname),
  acceptMimes: ['application/json'],
  serveStatic: {
    '/resources': '${rootDir}/resources',
  },
  mount: {
    '/': '${rootDir}/controllers/*.ts',
    '/dashboard': '${rootDir}/controllers/dashboard/**/*.ts',
    '/api': '${rootDir}/controllers/api/**/*.ts',
  },
  componentsScan: [
    '${rootDir}/middlewares/**/*.ts',
    '${rootDir}/models/**/*.ts',
    '${rootDir}/services/**/*.ts',
  ],
  swagger: {
    path: '/swagger',
  },
}```

**Comment by Romakita** [comment]
Ok. Add this:

```typescript
@ServerSettings({
validationModelStrict: true
})
```
And on your mode:
```typescript
class User {
   _id: string;
   @Property()
   name: string;
}
```
Tell if it works :)

**Comment by mduthilleul** [comment]
With this modification I get the desired behavior : https://github.com/mduthilleul/ts-express-decorators/commit/c51d92818176f0a520ca3b31d527bd79b85cd60f
If the object class has properties with Property decorator it will only render those.

**Comment by mduthilleul** [comment]
With validationModelStrict set to true, it get an error:

**Comment by mduthilleul** [comment]
With validationStrict set to true I get this error: 
`Property _id on class NoPasswordUserEntity is not allowed.`

**Comment by Romakita** [comment]
Hooo ok it's on the serialize method. Sorry for this mistake. Ok you can purpose your PR ;)

**Comment by Romakita** [comment]
It's almost the same needs with this issue. https://github.com/Romakita/ts-express-decorators/issues/238

I think it would be better to create the `@Ignore` decorator.

**Comment by mduthilleul** [comment]
It would be totally acceptable for me.
But then, the use of JsonProperty/Property decorator is maybe unclear.
The doc says it `let you decorate an attribute that can be serialized or deserialized`.
So I assumed it was mandatory for a property to be rendered.
But if not, yes a @Ignore decorator would be nice.
And then maybe for consistency the Swagger plugin should render example with all properties, not only those marked with @JsonProperty ?

**Comment by Romakita** [comment]
In fact, Converter should be based on the metadata generated by the annotation on the properties, not on the object return/send by the request.

TypeScript generate metadata on property only when the property is decorated. So if you write this code:
```
class Model {
   id: string;
}
```
TypeScript didn't generate metadata. For the converters, the hack is to use the object and list all keys. But with Swagger I can't use this hack, the object didn't live in this context.

It is better to rely on the description of the model rather than deduce it.
See you

**Comment by mduthilleul** [comment]
Very clear now, thanks for the explaination :-)

**Comment by Romakita** [comment]
@mduthilleul You can create a Pull request with you fix ;). I'll merge it !

**Comment by Romakita** [comment]
In addition, I'm working on the documentation to clarify the Model and converters behavior. 
Branch: https://github.com/Romakita/ts-express-decorators/tree/feat_converter_property_ignore

**Comment by Romakita** [comment]
PR: #259
