### ISSUE TITLE
Option to autogenerate swagger

### ISSUE THREAD

**Issue by alexproca** [Romakita/ts-express-decorators#26]
It would be nice to have the option to auto-generate an [OpenAPI](https://www.openapis.org/) (swagger) definition on route mounting step and expose it at some configurable path with default value `/openapi`

**Comment by Romakita** [comment]
You have this middleware [https://github.com/fliptoo/swagger-express](https://github.com/fliptoo/swagger-express) to generate the swagger-ui with express ;).

**Comment by Romakita** [comment]
see #76
