### ISSUE TITLE
Interceptors for Services

### ISSUE THREAD

**Issue by mitevs** [Romakita/ts-express-decorators#262]
## Informations

Type | Version
---|---
Improvement | 4.x

****

## Description
Would be nice if there's a controlled way to define decorators for services. For e.g. I have permission filter decorator that intercepts calls to my service methods. I need to keep the code this way because is not web-agnostic. This will be very similar to the concept of interceptors in EJB for Java. This is how I imagine it:

![screen shot 2018-03-08 at 10 27 13 am](https://user-images.githubusercontent.com/1431331/37143395-5591fcb8-22bb-11e8-89f1-76059c4778cf.png)

Don't mind the errors reported in my editor, I just wanted to illustrate the concept.

The interceptor might be applied only to a method as well, or to the whole class in which case it will be executed on every service method call.

I can elaborate a bit more if needed, but the concept is already present in [EJB](https://www.tutorialspoint.com/ejb/ejb_interceptors.htm)

**Comment by mitevs** [comment]
Or an alternative, which is more close to what EJB has.
![screen shot 2018-03-08 at 10 30 36 am](https://user-images.githubusercontent.com/1431331/37143558-cd37851c-22bb-11e8-8070-6c33aa556e99.png)

But this way we can only apply to the whole service. If there's need to only execute on a single method it will not be so intuitive.

**Comment by Romakita** [comment]
Good idea =)

**Comment by kalu111** [comment]
Maybe the better usage will be to set decorator to target method ?

**Comment by mitevs** [comment]
@kalu111 this is actually just a better way to define decorators that will blend nicely with the rest of the components.. like injecting services inside the decorator.. and also giving more declarative way to attach decorators to service methods. As I said in the second comment, it might be good if it is allowed for the decorator to be defined on a method in the service, or the service as a whole.

**Comment by kalu111** [comment]
@mitevs Of course, I do not mind :)
I just wanted to write about the additional possibility of setting decorators per method.

**Comment by mitevs** [comment]
I would be glad to participate in it myself, maybe I will submit PR, but I need first to get some feel of the src and experiment a bit. Meanwhile if someone contributes I will surely check what has been done! :)

**Comment by mitevs** [comment]
@Romakita I am trying to build the interceptor, but it's a bit tricky to make single class decorator that applies to every method, so I decided to try a different way. I created something similar to the Middleware annotation. First I created DecoratorRegistry like so:

![screen shot 2018-03-12 at 10 52 51 am](https://user-images.githubusercontent.com/1431331/37276930-89475d02-25e3-11e8-9b22-7e814401e02a.png)

Then I've created the DecoratorService

![screen shot 2018-03-12 at 10 53 40 am](https://user-images.githubusercontent.com/1431331/37276973-a7615cb6-25e3-11e8-9a1f-4f20ae411492.png)

This is very similar to the MiddlewareService, it's a normal service that $onInit uses the InjectorService.buildRegistry to build the registry for the Decorators.

Currently I have decorator with different name, but I will rename it to @Decorator, at the moment is called @ServiceIntereceptor, and it's like this:

![screen shot 2018-03-12 at 10 54 57 am](https://user-images.githubusercontent.com/1431331/37277040-d3619b0a-25e3-11e8-99bb-9f1934f9e7e0.png)

This one uses the DecoratorRegistry to merge this class into it. And finally I have the @Intercept annotation which is applied to the service methods of the custom service, like:

![screen shot 2018-03-12 at 10 55 47 am](https://user-images.githubusercontent.com/1431331/37277076-f196e044-25e3-11e8-993c-6c92d439ec9f.png)

It's a bit messy currently but I am testing my concept. The intercept is trying to find the interceptor symbol in the registry and executes the aroundInvoke. Inside it I should call proceed in order to allow the method to flow, or block it with a reason or exception. Here's a sample decorator that I want to use:

![screen shot 2018-03-12 at 10 57 24 am](https://user-images.githubusercontent.com/1431331/37277147-2c0f6598-25e4-11e8-9495-df8ebd637a99.png)

And this is how I apply it on the method in my service:

![screen shot 2018-03-12 at 10 57 48 am](https://user-images.githubusercontent.com/1431331/37277174-3b0c67e4-25e4-11e8-9be3-5a47405658a1.png)

This almost works, except when I try to inject other services in the decorator class constructor I get the following error:

<img width="857" alt="screen shot 2018-03-12 at 10 58 33 am" src="https://user-images.githubusercontent.com/1431331/37277200-53d2705c-25e4-11e8-8911-a5def7536d11.png">

I could see that in the MiddlewareService you inject the injectorService instance in the constructor, but in my case, when I try to inject the injectorService in the DecoratorService I get the same exact error. Seems like the serviceType is undefined in this part of the invoke method in the InjectorService:

![screen shot 2018-03-12 at 11 00 04 am](https://user-images.githubusercontent.com/1431331/37277297-97768f82-25e4-11e8-8776-2bad52a2cb72.png)

Maybe you can give me some hints? Thanks!

**Comment by mitevs** [comment]
This boils down the the concept of decorators in TS except the way I define the aroundInvoke is a bit more intuitive and the decorator is hooked to the tsED ecosystem and can access/inject other components if needed :)

**Comment by Romakita** [comment]
Hi @mitevs ,

I think it's a problem with Intercept decorator. In the Interceptor decorator, you have potentially an array of interceptor, but `DecoratorRegistry.get()` line 15 can't handle an array of class.  I think your problem come from this line. To begin try, with online one interceptor (not an array). 

I can checkout your branch and try on my local, if you want any help :)

Otherwise, it's a great job :)

In addition, I suggest you to move interceptor decorators, registries and classes under a new folder like `common/interceptor`. And rename DecoratorRegistries by InterceptorRegistries (more understandable ;)).

See you,
Romain

**Comment by mitevs** [comment]
Sure, let me try and see what I get, thanks! 👍

**Comment by Romakita** [comment]
I have a question. It's necessary to create a new registry ? Because, I think ProviderRegistry can be used to store interceptor too. DecoratorRegistry and ProviderRegistry looks like very similar ^^.

**Comment by mitevs** [comment]
I guess I can use it, I am still learning the architecture :)

**Comment by Romakita** [comment]
Ok no problem ;)

**Comment by mitevs** [comment]
I guess I don't have to call InjectorService.buildRegistry(..) then? Because this one is already built from the InjectorService no?

**Comment by mitevs** [comment]
Or I can make the code work and then you can do changes to the PR before we make a final version that will work correctly! :)

**Comment by Romakita** [comment]
Yes perfect ;)

**Comment by Romakita** [comment]
> I guess I don't have to call InjectorService.buildRegistry(..) then? Because this one is already built from the InjectorService no?

Exactly, but your a ServiceInterceptor is a Service with a specific method. This method will be invoked by your decorator.  The class build aspect hasn't a difference between Service and ServiceInterceptor. And if we go further, a service can become at any time an interceptor if it implements the right interface.

```typescript
@Service()
class MyServiceInterceptor implements IServiceInterceptor {
   aroundInvoke(ctx: any){
   }
}
```
And your interceptor decorator:
```typescript
export function Intercept(service: IServiceInterceptor | IServiceInterceptor[]): any {
    return (target: any, method: string, descriptor: PropertyDescriptor) => {
        const original = descriptor.value;

        descriptor.value = function (...args) {

            if (InjectorService.has(service)) {

                const instance = InjectorService.get<IServiceInterceptor>(service);

                return new Promise((res, rej) =>
                    instance.aroundInvoke({
                        target,
                        method,
                        args,
                        proceed: () => {
                            res(original.apply(this, args));
                        }
                    })
                );
            } else {
                return original.apply(this, args);
            }
        };
    };
}
```
I thinks it works ^^

**Comment by mitevs** [comment]
I've pushed PR, it's very similar to what you suggested, but just to make it bit more clear I've defined @Interceptor which might diverge with a bit different impl. in the future!

**Comment by Romakita** [comment]
Nice :)
