### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by krnprdp** [Romakita/ts-express-decorators#265]
## Informations

Type | Version
---|---
Question | 2.x

****

## Description
Hi, I am trying to run the examples. When I do npm install, I get the following errors:
controllers/calendars/CalendarCtrl.ts(5,5): error TS2305: Module '"/workspace/web-dev/example-ts-express-decorator/basic/node_modules/ts-express-decorators/lib/index"' has no exported member 'IPromise'.

controllers/calendars/EventCtrl.ts(1,55): error TS2305: Module '"/workspace/web-dev/example-ts-express-decorator/basic/node_modules/ts-express-decorators/lib/index"' has no exported member 'ICrud'.

My setup:

+ express@4.16.2
+ types/express@4.11.1
+ tsed/common@4.4.1
+ tsed/core@4.4.1
+ node 8.9.4
+ express 4.14.5
+ npm 5.7.1

**Comment by Romakita** [comment]
Hi @krnprdp ,
I thinks you use the example for v2. 
Here the latest version : https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-basic ;)

See you
Romain

**Comment by krnprdp** [comment]
Thanks for the quick answer @Romakita :)
Everything works well.
