### ISSUE TITLE
Service constructor default value not allowed

### ISSUE THREAD

**Issue by mitevs** [Romakita/ts-express-decorators#266]
## Informations

Type | Version
---|---
Bug | 3.10.x

****

## Description
Cannot define param with default value in constructor of a Service. E.g:

`
@Service()
class MyService {
 constructor(myValue = 'default value'){ ... }
}
`
This fails because the injector service tries to inject the myValue as another service instance. Is it possible that the injector sees those params that have default values and skip them?

**Comment by Romakita** [comment]
It's strange... When you declare a class as a Service, it mean you want to delegate the class building to the InjectorService and use the Singleton pattern. And you will never build your class from another class (excepted in the unit test maybe).

In which case would you need this?

**Comment by mitevs** [comment]
I have service hierarchy that needs some other details during construction of the instances. E.g. I have a BaseService<T extends Base> that sets-up basic CRUD ops for Base model class. Then I have an ItemService<T extends Item> extends BaseService<T>. The Item extends Base. This service add bit more specific store ops for the Items. The Item has subclasses, Document, Layout and Widget. This is a REST for a component-based solution I am building. The Item has discriminator prop "type" that is persisted in nosql, but when I map back I am instantiating the correct subclass based on the type prop.

Because I have only single collection of Items with their "type" I have created subservices for Document, Layout and Widget models, that is.. DocumentService, LayoutService, WidgetService respectively. In the ItemService I extend the BaseService find (Read) method and add additional query params so that I filter only the types of Items I need. For e.g. if I execute the find from the ItemService it will execute this query:

{ type: { $in: types} } where "types" is protected types: string[] = ['document', 'layout', 'widget'] in the ItemService constructor.

If I execute the find from the DocumentService, I need to scope down the types to only 'document', so through the constructor of the DocumentService I have this:

`
@Service()
ItemService<T extends Item> extends BaseService<T> {
constructor(protected types: ['document', 'layout', 'widget']) { ... }
}

find(query?) {
 return this.collection({... query, { type: { $in: this.types} }});
}
`

`
@Service()
DocumentService extends ItemService<Document> {
constructor() {
 super(['document']);
}
}
`
Now if I execute find from the ItemService instance I will get all the items with types 'document', 'layout', 'widget'. But if I execute the find from the DocumentService instance I will get only items with type 'document'.

I hope you understand the use case?

Thanks!

**Comment by mitevs** [comment]
I have found a workaround for this issue but I think it would be helpful if it's possible the InjectorService to skip props with default values if it cannot find the appropriate instance to be inejected in the registry. The current workaround I have is to add additional method init() in the service hierarchy which internally sets the types prop, and override this in the other services to redefine the type prop:

class ItemService {
 protected types: string[];
 
 constructor() {
 ...
 this.init();
 }

 init() {
  this.types = ['document', 'layout', 'widget'];
 }
}

class DocumentService extends ItemService{
 
init() {
 this.types = ['document'];
} 
}

This works but is a bit more code for the job.

**Comment by Romakita** [comment]
Well, You can write this, without mode code:

```typescript
@Service()
class ItemService {
    protected types: string[] = ['document', 'layout', 'widget'];
    constructor() {}
}

@Service()
class DocumentService extends ItemService{
    protected types: string[] = ['document']
}
```
Then to answer you, default value isn't detectable. Only the type of the parameters is given. And the purpose of the Injector is to emit an exception when the Service is unknown. Change this rule is not possible. Instead of, use a decorator is possible to avoid this behavior.

```typescript
function SkipInject(target: Type<T>, targetKey: string, descriptor: TypedPropertyDescriptor<Function> | number) {
      const paramTypes = Metadata.getParamTypes(target, targetKey);
      paramTypes[descriptor] = SkipInject;
     Metadata.setParamTypes(target, targetKey, paramTypes);
}
```

Then patch the InjectorService.ts L245:
```typescript

    static invoke<T>(target: any, locals: Map<string | Function, any> = new Map<Function, any>(), designParamTypes?: any[], requiredScope: boolean = false): T {

        if (!designParamTypes) {
            designParamTypes = Metadata.getParamTypes(target);
        }

        const parentScope = Store.from(target).get("scope");

        const services = designParamTypes
            .map((serviceType: any) => {

                if (serviceType === SkipInject) {
                     return undefined;
                }
                
                const serviceName = typeof serviceType === "function" ? nameOf(serviceType) : serviceType;

                /* istanbul ignore next */
                if (locals.has(serviceName)) {
                    return locals.get(serviceName);
                }
               // ....
          })
       //...
   }
```
You can try this solution and send me PR, if it works. (but I prefer the first the solution :p).

See you,
Romain

**Comment by mitevs** [comment]
@Romakita actually your solution is much more elegant, I did complex it a bit myself. I guess it's not needed to patch with SkipInject because it will create more confusion. It should be only used in conjunction with default value params, if omitted it will create issues.

Thanks, you can close this ticket!
