### ISSUE TITLE
Injected Express.Router is not the controller's router

### ISSUE THREAD

**Issue by alexheim** [Romakita/ts-express-decorators#272]
## Informations

Type | Version
---|---
Bug | 4.5.3

****

## Description
The controller documentation gives an example, to access the router's controller via the `@ExpressRouter` annotation. However, the router appears not to be the one, that has any of routes in the controller.  The injected route appears to be completely disconnected.

The following example is more or less taken from the documentation:
```typescript
@Controller("/calendars")
export class CalendarCtrl {
    constructor(@ExpressRouter private router: ExpressRouter) {
        router.get('/method1', this.method1)
    }

    method1(req, res, next){ [...]}

    @Get("/method2")
    async method2() { [...] }
}
```

In this example, requests to `"/calendars/method2"` are perfectly dispatched to `method2`. Whereas there seems no route to `method1` (neither `"/calendars/method1"` nor `"/method1"` are active routes).

When I use the debugger and set a breakpoint in the working `method2`, I can inspect `this.router` like this:
```typescript
this.router.stack.forEach((r) => {
    console.log(Object.keys(r.route.methods) + " -> " + r.route.path);
});
```
and can see, that this router has only 1 route: `get -> /method1`. Going further up the stack. In other words, that cannot possibly be the controller's router.

Is it possible to get access to the controller's router? I would like to use the router to add  callback triggers for route parameters (via `router.param(name, callback)`) and add `passport` authentication handlers.

A related question seems #165, which shows a deprecated variant on the injection, that does not work either.

**Comment by Romakita** [comment]
Hi @alexheim,

I think it's effectively a  bug. I've certainly introduce a regression with the latest version of this feature.
I'll fix that today and this example will work after that :)

See you,
Romain

**Comment by alexheim** [comment]
This was an amazingly fast bug fix! I'm looking forward to get the next version via npm. In case I forgot to mention: ts-express-decorators is a great framework and the typescript-swagger-world would be a lot poorer, if ts-express-decorators didn't exist!

**Comment by Romakita** [comment]
Thanks a lot @alexheim :D

**Comment by Romakita** [comment]
new release is available.

**Comment by Romakita** [comment]
Just for information, dynamic method added with ExpressRouter instance isn't registered in the Ts.ED endpoints registry :/
So the endpoint will not appear on the console and in the swagger documentation.

**Comment by alexheim** [comment]
Sure - makes sense. In my case, access to the router is for authentication and param resolution. The swagger API is defined classically, as intended by the framework's design.
