### ISSUE TITLE
How to bind services?

### ISSUE THREAD

**Issue by azanorth** [Romakita/ts-express-decorators#275]
Good day.
    Tell me please is it possible bind services?
In 'InjectorService' class there are many methods to work with injections of services. But I did not understand is it possible to bind or replace an existing service? Something like 'contaier.bind()...' in Inversify.js. 
    I have a task to create integration tests, but services, they work with the database, and their methods should be mocked. I need to start the server so that on, the test request the controller turned to the fake service. To do this, I need to replace the existing services with the same, but with the methods that return fake data, for example with help 'Sinon.createStubInstance(...)'

something like that:
```typescript
    InjectorService.load();

    const myService = InjectorService.get<MyService>(MyService);

    let myServiceMock: MyService = Sinon.createStubInstance(MyService);
```
That is, in this example, I created a fake service. And now I can identify him with fake methods.

something like that:
```typescript
    (<any>myServiceMock.getUserById).withArgs(1).resolves({"name": "John"}, ...);
```
The question is - how to replace the original service, this new fake service. Is it posible?

**Comment by Romakita** [comment]
Hello @azanorth ,

Mocking service is possible. Here an example:
```typescript

@Service()
class MyService() {
   constructor(parseService: ParseService) {
       parseService.parse("test")
   }
}

describe('MyService',() => {
    before(inject([InjectorService], (injectorService) => {
         this.parseServiceStub  = {parse: Sinon.stub()}
         const locals = new Map();
         locals.set(ParseService,  this.parseServiceStub);
         injectorService.invoke(MyService, locals)
    }))

    it('should call the parseService.parse method',() => {
        this.parseServiceStub.should.have.been.calledWithExactly("test");
    });
});
```

With the latest version of Ts.ED it also possible to change the InjectorService configuration:

```typescript
registerProvide({provide: ParseService, useClass: {parse: Sinon.stub()});

then InjectorService.load().
```

I agree, the package `@tsed/testing` must be improved ;) (in a future version).

See you
Romain

**Comment by azanorth** [comment]
Ok, thank you very much.
Have a nice day.
