### ISSUE TITLE
Call method after service initialization

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#277]
It would be a nice feature to declare method that will be called immediately after service initialization.
## Informations

Type | Version
Improvement|4.x

****

## Description
```typescript
@Service()
class MyService {
    constructor() {}
   
    @OnInit()
    async onInit() {
         // connect to redis
    }

    @OnDestroy()
    async onDestroy() {
        // disconnect
    }
}
```

**Comment by Romakita** [comment]
Have you look this page https://romakita.github.io/ts-express-decorators/#/docs/services/lifecycle-hooks :)
I think it'll answer about the OnInit cycle.

But destroy cycle didn't exists in Ts.ED. Service is never destroyed.

**Comment by kalu111** [comment]
Yes, it is what I have been looking for :)
