### ISSUE TITLE
@Any and @AllowTypes fail for Map properties in Swagger

### ISSUE THREAD

**Issue by clecompt-msft** [Romakita/ts-express-decorators#279]
## Informations

Type | Version
---|---
Bug | 4.7.0

****

## Description
Any of the decorators that write directly to the JSON schema type rather than the property metadata type (eg. `@Any` and `@AllowTypes` vs. `@PropertyType`) get overwritten by `OpenApiModelSchemaBuilder.createSchema` when they apply to a non-array collection. This causes a model like the following:
```ts
export class AnyCollection {
    @Any()
    values: Map<string, any>;
}
```
to be translated to a Swagger that looks like:
```json
{
    "definitions": {
        "AnyCollection": {
            "properties": {
                "values": {
                    "additionalProperties": {
                        "type": "object"
                    }
                }
            },
            "type": "object"
        }
    }
}
```
when it should look like:
```json
{
    "definitions": {
        "AnyCollection": {
            "properties": {
                "values": {
                    "additionalProperties": {
                        "type": [
                            "integer",
                            "number",
                            "string",
                            "boolean",
                            "array",
                            "object",
                            "null"
                        ]
                    }
                }
            },
            "type": "object"
        }
    }
}
```

**Comment by Romakita** [comment]
Hi @clecompt-msft ,

Is not a bug. In this issue #200, Any provide a way to allow all types listed in your previous example.
set an object type didn't provide the good behavior with swagger. 
If you want to obtain your first example, just replace the `@Any()` annotation by the `@Property` decorator ;)

See you,
Romain

**Comment by clecompt-msft** [comment]
I'm somewhat confused by your response - I'm actually trying to get the _second_ example, but am unable to because of the current behavior of `@Any` + Swagger.

**Comment by Romakita** [comment]
Sorry @clecompt-msft  ^^.

This output:
```
{
    "definitions": {
        "AnyCollection": {
            "properties": {
                "values": {
                    "additionalProperties": {
                        "type": "object"
                    }
                }
            },
            "type": "object"
        }
    }
}
```
is produced with this configuration:
```typescript
export class AnyCollection {
    @Property()
    values: Map<string, any>;
}
```

`@Any` decorator is here to cover all types supported by the JSONSchema and AJV. Swagger follow the same rules normally. `object` is too restrictive as explained in this issue #200.

I hope the examples is more clear :)
See you
Romain

**Comment by clecompt-msft** [comment]
Right, but that same output is currently also produced by `@Any`. I want the output with `"type": [ "integer", "number", "string", "boolean", "array", "object", "null" ]`, but `@Any` isn't producing it.

**Comment by Romakita** [comment]
It's strange. The units test work fine. I'll check again. maybe it's problem with the Swagger generator.

**Comment by clecompt-msft** [comment]
It works as expected with `JsonSchemesRegistry`, which is why I'm pretty sure it's an issue in the Swagger generation.

**Comment by Romakita** [comment]
Fixed :D

**Comment by clecompt-msft** [comment]
Thanks for the quick turnaround! :)
