### ISSUE TITLE
Mongoose Model. Can't find by id

### ISSUE THREAD

**Issue by RevanScript** [Romakita/ts-express-decorators#280]
Hello,

I'm trying to use `@tsed/mongoose@4.8.0` and have an issue here.

I don't want to exclude `_id` from schema and want users to see it in response, but when i add `@Property` decorator instead of `@IgnoreProperty` to `_id`, querying by id stops working, it just returns `null`.

```TypeScript
@Model({
    name: 'User'
})
export class UserModel {

    // @IgnoreProperty()
    @Property()
    _id: string;

    @Required()
    username: string;

}

...

const user = await this.userModel.findById(myUserId); // returns null
```

When i use `@IgnoreProperty` or leave `_id` without decorators, querying by id works fine. Is this a bug? Or there's any other way to do something with it?

Thanks!

**Comment by Romakita** [comment]
Hi @RevanScript ,
I just did not think about that possibility. It's clearly a bug ^^.
I'll release the fix immediately 

See you,
Romain

**Comment by Romakita** [comment]
Fixed :). v7.8.1

**Comment by RevanScript** [comment]
Great! Works fine now. Thanks a lot for a quick reaction!
