### ISSUE TITLE
@tsed/socketio bugs

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#282]
## Informations
I can't import  `@SocketMiddlewareError()` and `@SocketMiddleware()` decorators (missing import statements).
In examples are `@SocketErr()` but it should be `@SocketErr`.

Compilation error (TS version=2.6.2):
```
node_modules/@tsed/socketio/lib/services/SocketIOServer.d.ts(9,45): error TS1005: '=' expected.

9 export declare const SocketIOServer: unique symbol;
```

Is there any way to inject  to `@SocketMiddlewareError()` event name on which the error occurred?

Bug | 4.8.1

**Comment by Romakita** [comment]
@kalu111 Fixed :)

I've added a new decorator SocketEventName. Check the updated documentation ;)

**Comment by kalu111** [comment]
Thanks,
What tag should be now?

**Comment by Romakita** [comment]
v4.9.0

**Comment by kalu111** [comment]
I found an another issue.
Error thrown in middleware is not catched by `@SocketErrorHandler()`.

Can you also chek it, pls :)

**Comment by Romakita** [comment]
Normally if you catch the error, the process will not be exited. I don't remember who asked before about that, but is a requested feature. Normally, in Node.js when an error is thrown the process should be down (and free all allocated memory). The developer must put a process manager like PM2 to restart the process automatically.
But I understand the problem with this instruction (because this behavior is not the same with the HTTPException in the express server part).

**Comment by Romakita** [comment]
Normally. If you handle correctly the error (when the fix will be release XD), the catch will not triggered.

**Comment by Romakita** [comment]
Can you send me the configuration of Websocket Service with the event where you have the problem. Because I've tried different use case, and all work fine.

**Comment by kalu111** [comment]
```typescript
@SocketService('/')
@SocketUseBefore(MySocketMiddleware)
@SocketUseAfter(ErrorHandlerSocketMiddleware)
export class MySocketService {}

@SocketService('/')
export class OtherSocketService {
    @Input('request')
    public async handle() {
        // some code
    }
}

@SocketMiddleware()
export class MySocketMiddleware {
    public async use( ) {
        throw new Error('Error');
    }
}
```

**Comment by kalu111** [comment]
```typescript
@SocketService('/')
@SocketUseBefore(MySocketMiddleware)
@SocketUseAfter(ErrorHandlerSocketMiddleware)
export class MySocketService {}

@SocketService('/')
export class OtherSocketService {
    @Input('request')
    public async handle() {
        // some code
    }
}

@SocketMiddleware()
export class MySocketMiddleware {
    public async use( ) {
        throw new Error('Error');
    }
}
```

**Comment by Romakita** [comment]
Thanks

**Comment by Romakita** [comment]
For me it. Works. The ErrorHandlerSocketMiddleware catch the error correctly.

Here my middleware:
```typescript
@SocketMiddlewareError()
export class ErrorHandlerSocketMiddleware {
    async use(@SocketErr err: any, @Socket socket: SocketIO.Socket) {
        $log.error("===", err);
        socket.emit("eventErr", {message: "An error has occured"});
    }
}
```

How have you declared your ErrorHandlerSocketMiddleware ?

**Comment by kalu111** [comment]
Another issue :)
When I'm injecting @SocketSession to another SocketService or Middleware I'm getting empty `Map`.

```typescript
@SocketService('/')
export class MySocketService {
    @Input('request1')
    async handle(@SocketSession session: SocketSession) {
        session.set('test', 'test');
    }
}

@SocketService('/')
export class OtherSocketService {
    @Input('request2')
    async handle(@SocketSession session: SocketSession) {
        const test = session.get('test'); // undefined
    }
}
```

Pls, check it.

**Comment by kalu111** [comment]
OK, issue with `@SocketMiddlewareError` resolved :)
I injected a class to the middleware constructor described without `@Service()` decorator.

Sorry :)

But strange, that there was no warning about that?

**Comment by Romakita** [comment]
yes it's strange. Normally Injector must fail when a Service is unknown

**Comment by kalu111** [comment]
About `@SocketMiddlewareError` - I found the issue.
I set the error handler for SocketService where there was no event handlers.
```typescript
@SocketService('/')
@SocketUseBefore(MySocketMiddleware)
@SocketUseAfter(ErrorHandlerSocketMiddleware)
export class MySocketService {}
```
When I set error handler to SocketService with event handlter, then it works correctly
```typescript
@SocketService('/')
@SocketUseBefore(MySocketMiddleware)
@SocketUseAfter(ErrorHandlerSocketMiddleware)
export class OtherSocketService {
    @Input('request')
    public async handle() {
        // some code
    }
}
```
I was thought that middlewares are inherited :)

About `@SocketSession`
Yes, I can use my own implementation to store session data between SocketServices.
But I think, when we have opportunity to create multiple SocketService with the same namespace so it would be seems to can use session between them. SocketId is not change until disconnect - so access to the session data is not a problem. Right?

**Comment by kalu111** [comment]
Eventually store session per socket namespace?

**Comment by Romakita** [comment]
Per namespace, I thinks it's possible.

**Comment by Romakita** [comment]
Next release will let you to use the session per namespace :)

**Comment by Romakita** [comment]
v4.10.0

**Comment by kalu111** [comment]
It works great !
Thank you for your time :)

**Comment by kalu111** [comment]
I have also a few new topics but I will create separate threads for that :)

**Comment by Romakita** [comment]
Thanks @kalu111 :)
yes I'll prefer a separate topic for each demand. Is easiest for me to track the issue :)
