### ISSUE TITLE
@tsed/socketio - @SocketSession with key parameter

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#285]
`@tsed` stores socket session as a `Map`.
Is it possible to add a `key` parameter for a `@SocketSession` decorator?

```typescript 
@SocketService('/')
class SocketService {
    @InputAndEmit('event')
    async handle(@SocketSession('token') token: string) {
        return token;
    }
}
```

**Comment by Romakita** [comment]
No because, the decorator is implemented without parentheses. Change that will create a breaking change.

**Comment by kalu111** [comment]
Yes, of course.
Thanks :)
