### ISSUE TITLE
[Socket.IO] Use model on socket handlers

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#288]
```typescript

@SocketService()
class MyWS {
    @Input('event')
    @Emit('returnEvent')
    handler(@Args(0) user: User) {
         console.log("User", user); // User {}
    }
}
```
- [ ] Argument can be deserialized with the ConverterService.
- [ ] Deserialization is called before all middlewares. Args must contain the deserialized object based on the endpoint signature.
- [ ] Returned value can be serialized with the ConverterService.

**Comment by Romakita** [comment]
Actually, it's not designed. The description will be added soon. But normally, it will be the same as what you have with the controllers ;)

**Comment by kalu111** [comment]
Does model mapping will be fired before middlewares chain?

**Comment by kalu111** [comment]
Hi @Romakita  
It is very useful feature :)

When to expect a release?

Thanks!

**Comment by Romakita** [comment]
This month if I have the time :)

**Comment by kalu111** [comment]
I can't wait :)

**Comment by Romakita** [comment]
The branch and feature is almost ready here https://github.com/Romakita/ts-express-decorators/tree/feat_288_socket_converter_service

But I haven't a time to finish.

**Comment by Romakita** [comment]
PR Ready :)

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/pull/366

**Comment by kalu111** [comment]
I've checked and it works fine :)
Thanks.

But if I send payload parsed by `JSON.stringify()` then it don not want to works.

**Comment by Romakita** [comment]
@kalu111 I don't understand what you mean. Maybe a code example should help me ^^

**Comment by kalu111** [comment]
Sorry :)

Validation works with:
```typescript
socket.emit('event', {test:1});
```
but do not with:
```typescript
socket.emit('event', JSON.stringify({test:1}));
```

This is only my notice - not big deal :)

**Comment by Romakita** [comment]
Your emit is sent from the front-end ? Socket.io stringify for you the object. If your apply a json.stringify before it's normal, if the validation doesn't work because, the converterService receive a string instead of an object.
