### ISSUE TITLE
@Required seems to not function properly with inheritance in Swagger

### ISSUE THREAD

**Issue by clecompt-msft** [Romakita/ts-express-decorators#289]
## Informations

Type | Version
---|---
Bug/Question | 4.9.1

****

## Description
The following class hierarchy:
```ts 
class ParentModel {
    @Required()
    parentProperty: string;
}

class ChildModelA extends ParentModel {
    @Required()
    childPropertyA: string;
}

class ChildModelB extends ParentModel {
    @Required()
    childPropertyB: string;
}
```
generates the following Swagger definitions:
```json
{
    "definitions": {
        "ParentModel": {
            "properties": {
                "parentProperty": {
                    "type": "string"
                }
            },
            "required": [
                "childPropertyB"
            ],
            "type": "object"
        },
        "ChildModelA": {
            "properties": {
                "parentProperty": {
                    "type": "string"
                },
                "childPropertyA": {
                    "type": "string"
                }
            },
            "required": [
                "childPropertyB"
            ],
            "type": "object"
        },
        "ChildModelB": {
            "properties": {
                "parentProperty": {
                    "type": "string"
                },
                "childPropertyB": {
                    "type": "string"
                }
            },
            "required": [
                "childPropertyB"
            ],
            "type": "object"
        }
    }
}
```
The `properties` seem to be inherited correctly, but the `required` values seem to be overwritten by the final class. I also noticed that after defining these three models, the following statement returns `true`, which feels incorrect and possibly related (but I'm not sure I understand the interaction between stores and inheritance well enough to say for certain):
```ts
Store.from(ParentModel).get('schema') === Store.from(ChildModelA).get('schema')
```
FWIW, the inheritance works exactly as expected when using `JsonSchemesRegistry`.

**Comment by Romakita** [comment]
Hum effectively, it's a bit strange... I'll inspect this problem ;)

**Comment by Romakita** [comment]
Ok. The reason is the Store didn't use the Reflect.getOwnMetadata method. So all metadata are share between parent class and his children class. I've already fixed this issue for the JsonSchemesRegistry but I've missed that for the Store. 

The problem is fixed in swagger :). The release will be out soon.

**Comment by Romakita** [comment]
v4.10.3
