### ISSUE TITLE
How to manually inject parameters from decorators?

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#297]
I have the following decorator: @Captcha()

```ts
import { Required, Use } from '@tsed/common'
import { Store } from '@tsed/core'
import { INVALID_CAPTCHA } from '../errors/ApiErrors'
import { ValidateCaptcha } from '../middlewares/ValidateCaptcha'

// Potentially i would like to give this model directly to the parameters instead of defining it manually
export class CaptchaModel {
    @Required()
    captcha: string
}

export function Captcha() {

    return Store.decorate((store: Store) => {

        store.merge('responses', { [ INVALID_CAPTCHA.code ]: { description: INVALID_CAPTCHA.message } })
        store.merge('parameters', { body: { name: 'captcha', description: 'captcha', required: true } }) // this doesnt work.. what am i doing wrong?

        return Use(ValidateCaptcha)

    })

}

```

and this is the middleware code:

```ts
import { BodyParams, Middleware, Next, Req } from '@tsed/common'
import { INVALID_CAPTCHA } from '../errors/ApiErrors'
import { ApiError } from '../exceptions/ApiError'

@Middleware()
export class ValidateCaptcha {

    async use(@Req() request: Express.Request, @BodyParams() data: { captcha?: string }, @Next() next: Express.NextFunction) {

        if (request.session.captcha === undefined || data.captcha !== request.session.captcha) {
            throw new ApiError(INVALID_CAPTCHA)
        }

        next(null, request.session.captcha = null)

    }

}
```

Question:

How do i merge the parameters so the swagger documentation + validation works when i include the @Captcha decorator to my methods.

**Comment by Romakita** [comment]
Complex because you want to add metadata from a parameter and method (like Multipartfile decorator) but Possible ;)

You have two choices:
```typescript
export class CaptchaModel {
    @Required()
    captcha: string
}

// Solution 1
export function SimpleCaptcha() {
    return Store.decorate((store: Store) => {

        store.merge('responses', { [ INVALID_CAPTCHA.code ]: { description: INVALID_CAPTCHA.message } })

        return Use(ValidateCaptcha);
    })
}

// Solution2
import {descriptorOf, Store, Metadata} from "@tsed/core";
import {Required, Use} from "@tsed/core";
import {Description} from "@tsed/swagger";

export function Captcha() {
    return (target: any, method: string, index: number) => {
        const descriptor = descriptorOf(target, method);
        const store = Store.from(target, method, descriptor);
        
        store.merge('responses', { [ INVALID_CAPTCHA.code ]: { description: INVALID_CAPTCHA.message } });
        Required()(target, method, index);
        Description("captcha descripion")(target, method, index);
        Use(ValidateCaptcha)(target, method, index);
       
        // optional
       const paramTypes = Metadata.getParamTypes(target, method);
       paramTypes[index] = CaptchaModel;
       Metadata.setParamTypes(target, method, paramTypes);
    })
}

// usage
class MyCtrl() {

   //Solution 1
   @SimpleCaptcha()
   method(@Required() @Description('captcha') catcha: CaptchaModel)
     
   // Solution 2
   method(@Captcha() captcha: CaptchaModel)
}
```

I hope my example will work correctly ;)
See you,
Romain

**Comment by milewski** [comment]
@Romakita Thanks for the help! the example you showed has enlightened me in some other issues i was having with these whole decorator thing!  

What i am trying to do is actually decorate the method, im not really interested in the value of captcha for giving it as a param as the `ValidateCaptcha` middleware will be responsible for validating it, i am only interested into the generated documentation and validation, i would like to be able to decorate a method and it some how merge the `CaptchaModel` into the current `@BodyParams()` 

for example:

![image](https://user-images.githubusercontent.com/2874967/37865222-5ae45e4e-2fb4-11e8-92b9-a8437511c331.png)

![image](https://user-images.githubusercontent.com/2874967/37865238-9fad7074-2fb4-11e8-993e-ca97d4913882.png)

**Comment by Romakita** [comment]
Ok. Is not possible because SwaggerService generate the body schema from the User model and create a $ref key for the User schema. 

Here a hack:
```typescript
function Captcha() {
    return (target: any, method: string, index: number) => {
        const descriptor = descriptorOf(target, method);
        const store = Store.from(target, method, descriptor);

        store.merge("responses", {[INVALID_CAPTCHA.code]: {description: INVALID_CAPTCHA.message}});
        Required()(target, method, index);
        Description("captcha descripion")(target, method, index);
        Use(ValidateCaptcha)(target, method, index);

        const paramTypes = Metadata.getParamTypes(target, method);
        const BaseModel = getClass(paramTypes[index]);
        const CaptchaModel = class extends BaseModel {
        };

        Property({use: String})(CaptchaModel, "captcha");
        Required()(CaptchaModel, "captcha");

        Object.defineProperty(CaptchaModel, "name", {value: nameOf(BaseModel) + "CaptchaModel"});
        ParamRegistry.get(target, method, index).type = CaptchaModel;
    };
}
```
Usage:

```typescritpt
class MyCtrl {
    @Post('/login')
    async login(@Captcha() @BodyParams() user: User) {}
}
```
> Note: BodyParams didn't required a parameter by default.
I've tested this solution and it works ;)

**Comment by milewski** [comment]
@Romakita thanks again! this approach does work i can see the documentation is updated and the validation is indeed kicking in when i hit that controller method, however... now the problem is that i cant pass the validation haha... it always says:

```
Bad request on parameter \"request.body\".\nshould have required property 'captcha'
```

I guess this is due the validation is being performed against the `User` model not the modified `UserCaptchaModel` 

After Reading the swagger documentation i found that it is actually possible to specify more params in these section:
 
![image](https://user-images.githubusercontent.com/2874967/37872156-5e2f71ee-3034-11e8-97ed-dc2e371bed11.png)

current i am archiving this by manually specifying a `swagger.json`

```js
swagger: {
        path: '/documentation',
        specPath: path.resolve(__dirname, '../swagger.json')
}
```

![image](https://user-images.githubusercontent.com/2874967/37872169-a47beba0-3034-11e8-8f7f-69f7aa8e27c6.png)

I'm reconsidering my first issue and i believe now that it is more practical to only inject the documentation to swagger instead of modifying the underlying model and validating it as some sort of validation is already being handled within the `ValidateCaptcha` middleware. 

So backing to my first example:

```
store.merge('parameters', { body: { name: 'captcha', description: 'captcha', required: true } }) // this doesnt work.. what am i doing wrong?
```
(after reading the swagger docs) i should have written it like this:

````
store.merge('parameter', { // <- i was expecting that this would be injected into the swagger.json parameters section for this controller
   name: 'captcha',
   in: 'body',
   required: true,
   description: 'Captcha Description'
})
```

**Comment by Romakita** [comment]
The validation failed because I added a setter on the UserCaptchaModel. I forgot this point.

You should try `@Operation` annotation instead. parameter didn't exists (But BaseParameter yes).

```typescript
@Operation({ 
   parameters: [
      name: 'captcha',
      in: 'body',
      required: true,
      description: 'Captcha Description',
      schema: {
         type: string
      }
])(target, method, descriptor);
```
> This documentation will be merged with parameters list ;)

See you
Romain

**Comment by milewski** [comment]
@Romikita ! it worked! thanks again! 

just a small note as this`@Operation` decorator is not being exported from the `@tsed/swagger` (by mistake perhaps?) i used this syntax instead ! and it works!

```
store.merge('operation', {
    parameters: [
        {
            name: 'captcha',
            in: 'body',
            required: true,
            description: 'Captcha Description'
        }
    ]
})
```

**Comment by Romakita** [comment]
Not exported ? damned XD. I'll fixed that immediately ;)

**Comment by Romakita** [comment]
Fixed. v4.10.4
