### ISSUE TITLE
@tsed/socketio  - set array of middlewares

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#299]
Hi,
Maybe such improvement - possibility to set array of middlewares in `@SocketUseBefore` and `@SocketUseAfter()`

**Comment by Romakita** [comment]
You can do that:

```typescript

@SocketUseAfter(middleware1)
@SocketUseAfter(middleware1)
class MyClass {}
```

**Comment by kalu111** [comment]
What about when the list of middlewares are stored/set in one place (application config, other packages, etc)?

**Comment by Romakita** [comment]
Haaaa ok. I understand, you want to export the list from another file. Ok, good point ;)

**Comment by Romakita** [comment]
Ok proposal:

```typescript
const middlewares = [];
@SocketUseAfter(...middlewares)
```
