### ISSUE TITLE
[Decorator] Model deserialization

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#3]
`@BodyParams` can deserialize an entire object and restore his methods if the type is provided via ReflectMetadata and Typescript.

Example:
```typescript
@Controller("/")
export class EventCtrl {

     @Post("/")
     save(@BodyParams() event: Event){
          console.log(event instanceof Event); // true
     } 

     //OR
     @Post("/")
     save(@BodyParams('event') event: Event){}
}
```

**Comment by alexproca** [comment]
Hi!

Can you provide more details on how do you plan to deserialize an entire object and restore his methods ? I have had a similar problem an chose composition of the object with the actual class.

Thanks

**Comment by Romakita** [comment]
Hi Alex,

I've found this npm project on github: https://github.com/jf3096/json-typescript-mapper

I didn't know if I'll use the module or I'll develop my own lib...

**Comment by alexproca** [comment]
Maybe it would be interesting to let people add their own converters. For example the converter could be loaded in a similar manner like services for a certain type.

Example: 
```
interface Converter<T> {

   deserialize(data): T;
   serialize(object: T): string;

}

@Converter()
class MyFooConverter<Foo> {
.....
}
```

**Comment by Romakita** [comment]
Hum... good idea :)

**Comment by Romakita** [comment]
preversion v1.3.0-4 are available to test this feature.

With this version you can:

1. Define a model:

```typescript
class MyModel {
    name: string;

    @JsonProperty({name: 'last-name'})
    lastName: string;
     
    @JsonProperty()
    birthDate: Date;

    @JsonProperty({use: Task})
    tasks: Task[];
}

class Task {
     subject: string;
     rate: number;
}
```
> Theses ES6 collections can be used : Map and Set.
> Map will be serialized as an object and Set as an array.

2. Define your own Converter

```typescript
@Converter(Date)
class DateConverter {
     deserialize(data: string, targetType?: any,  baseType?: any)  {
           return new Date(string);
     }
     
    serialize(data: Date) {
           return data.toISOString();
    }
}
```
> `targetType` and `baseType` is set when you want convert an `Array`, `Map` or `Set` class. `targetType` is the collection and `baseType` the type for each item.
> By default `Date`, `Array`, `Map` and `Set` have a custom `Converter`.

`ServerLoader.scan` method can be used to auto import all custom converter in your project.
