### ISSUE TITLE
[SocketIO] adapter is not initialized

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#303]
Hi,
I try configure `socket.io-redis` adapter in that way, but in my redis server  I can not see any `pubsub channels`

```typescript
class Server extends ServerLoader {
    constructor() {
        super();
        this.setSettings({
            socketIO: {
                path: '/',
                adapter: fakeAdapter()
            },
        });
    }
}
```

Startup log shows that settings are set.

**Comment by Romakita** [comment]
Hello @kalu111 

This option provided by the SocketIO typing isn't supported by the tsed/socketio package. 
But I can solve it soon.

See you,
Romain

**Comment by kalu111** [comment]
https://github.com/Romakita/ts-express-decorators/blob/v4.12.2/src/socketio/services/SocketIOService.ts

4.12.2 not changes

**Comment by Romakita** [comment]
Yes, the release has failed. I fix that quickly.

**Comment by Romakita** [comment]
deployed ;)

**Comment by kalu111** [comment]
Now it works.
Great. Thanks!
