### ISSUE TITLE
[Bug] Mongoose @Ref decorator not respecting the property type 

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#305]
I found a regression introduced on the latests commits:

consider the following

```js
@Model()
export class User {
    @Ref(Favorite)
    favorites: string[]
}

@Model()
export class Favorite {    
    name:string,
    type:string,
}
```

```js
const favorite = await favoriteModel.create({....})
userModel.create({
   favorites: [ favorite ]
})
```

version: `4.10.5` outputs

```js
{
    "_id" : ObjectId("5abdbaa8ee9ba0c38a0a51b2"),
    "favorites" : [ 
        ObjectId("5abdbaa8ee9ba0c38a0a51b1")
    ]
}
```

however in the latest version it outputs

version: `4.11.0 `outputs

```js
{
    "_id" : ObjectId("5abdbaa8ee9ba0c38a0a51b2"),
    "favorites" : [ 
        {
            "_id" : ObjectId("5abdbaa8ee9ba0c38a0a51b3"),
            name: ....,
            type: ....
        }
    ]
}
```

it probably has something to do with this commit: https://github.com/Romakita/ts-express-decorators/commit/7e37b9e

**Comment by Romakita** [comment]
@milewski Great work. But you must create branch and PR before purpose a change. I shouldn't commit directly on the master branch. The risk is to lost the commit if another branch is merged and finished XD (master is reset from the production).

Normally the process is described here: https://romakita.github.io/ts-express-decorators/#/contributing?id=gflow
You not obliged to install gflow tool (you can reproduce the process with pure git command) but it follow the Gitflow and semantic-release. It help me to publish and finish feature/fix (and to have a clean history).

Don't worry about that ;) I'll clean the master branch and send your if in release.

See you
Romain

**Comment by Romakita** [comment]
It's my fault, I didn't give you the right process ;)

**Comment by Romakita** [comment]
Tell me if the process isn't clear ;) I need some feedback on this part.

**Comment by milewski** [comment]
Oh right im sorry i haven't seem that contributing page 👍  will do next time ~
