### ISSUE TITLE
[SocketIO] Rooms

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#307]
Hi,
Another issue :)
Actually decorators such as `@Emit()`, `@Broadcast()` cannot send event to specific rooms.
Maybe it is good idea to add second parameter or other decorator to set name of `room`?

**Comment by Romakita** [comment]
It think you mean `namespace` because the `tsed/socketio` package didn't create `room`. 
It's a bit strange that two namespace dialogue between them ?

https://socket.io/docs/rooms-and-namespaces/#

**Comment by Romakita** [comment]
Maybe I can add a method in SocketIOService to get a namespace instance :)

**Comment by Romakita** [comment]
@kalu111 the PR #346 can be reviewed ;)
