### ISSUE TITLE
[SocketIO] MaxListenersExceededWarning

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#308]
Hi,
I have more than 10 `@SocketService('/')` instances, so it produces a warning:

> (node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit

Maybe the better approach is to group events listeners per namespace and only register them after all  are loaded.

What do you think @Romakita ?

Of course I can increase a lImit ;)

**Comment by Romakita** [comment]
... I never thought about the possibility that a single namespace could be used by several classes. This is why I've designed my code about one class = one distinct namespace.

I must rethink the architecture :\

XD

**Comment by Romakita** [comment]
The next release should solve your problem ;)

**Comment by kalu111** [comment]
Nice to see that:)
I will check it after weekend.

In my opinion it is a great feature that allows to create modular application with services and other files that are stored in a separate folders.

**Comment by Romakita** [comment]
I saw that I had a performance problem when SocketService create the connect and disconnect listener.
