### ISSUE TITLE
[Decorator] MultipartFile

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#31]

**Comment by Romakita** [comment]
```typescript
@Controller('/')
class MyCtrl {
     @Post('/file')
     private uploadFile(@MultipartFile() file: Multer.File) {

     }

     @Post('/files')
     private uploadFile(@MultipartFile() files: Multer.File[]) {

     }
}

```

**Comment by m0uneer** [comment]
Hi Romakita, how can Multer configuration be passed? I see that the only config available is the `uploadDir`

**Comment by Romakita** [comment]
Hi @m0uneer ,

Actually, global settings let you to customize the uploadDir. For more, options you need to give that to the MultipartFile decorators. 

```typescript
@MultipartFile(multerOptions)
```

See you

**Comment by khusamov** [comment]
Hello! And where does the class Multer.File come from?

**Comment by Romakita** [comment]
Hi @khusamov ,

Multer come from the `@types/multer` and the decorator come from ts-express-decorators.

**Comment by khusamov** [comment]
Thanks for the answer!

In the file `@types/multer/index.d.ts` I found only interface `Express.Multer.File` (line 99). But I can not understand how to connect it (with import).

I found how to connect the decorator `MultipartFile` with the help of` import {MultipartFile} from 'ts-express-decorators / multipartfiles'; `. At you on a site in the documentation it is passed (

**Comment by Romakita** [comment]
Hello @khusamov ,

Sorry for this mistake. I've just found the right example on my old project:

```typescript
import {Controller, Post} from "ts-express-decorators";
import {Multer} from "@types/multer";

type MulterFile = Express.Multer.File;

@Controller('/')
class MyCtrl {
    
  @Post('/file')
  private uploadFile(@MultipartFile() file: MulterFile) {

  }
     
  @Post('/file')
  private uploadFile(@MultipartFile({dest: "/other-dir"}) file: MulterFile) {
         
  }
}
```
It's work normally :)
See you !

**Comment by Romakita** [comment]
Documentation will be updated soon ;)

**Comment by naoric** [comment]
`@MultipartFile` still not recognized, copied the code from the documentation:
```
import { Controller, Get, Post } from '@tsed/common'
import Multer from 'multer'

type MulterFile = Express.Multer.File

export interface ViewerModel {
  name: string
  file: string
}

@Controller('/models')
export class ViewerModelCtrl {
  @Get('/')
  async renderModels() {
    return 'Hello World'
  }

  @Post('/')
  private uploadeModel(@MultiplartFile() file: MulterFile) {}
}
```

I get 'Cannot find name 'MultipartFile'

**Comment by naoric** [comment]
Solved by installing `@tsed/multipartfiles` and
```
import { MultipartFile } from '@tsed/multipartfiles'
```

In the documentation, `@tsed/multipartfile` is mentioned instead of `@tsed/multipartfiles` (plural)
And it looks like it should be used only for multiple files upload.

https://romakita.github.io/ts-express-decorators/#/tutorials/upload-files-with-multer?id=example

**Comment by Romakita** [comment]
Hum ok. I'll fix this typo :) Thanks @naoric
