### ISSUE TITLE
Middleware dependency to auth with passport.

### ISSUE THREAD

**Issue by jindev** [Romakita/ts-express-decorators#310]
## Informations

Type | Version
Question|2.x
Bug/Improvement/Question | 2.x

****

## Description
Hi @Romakita.

I think it could be better if ExpressApplication is not imported in PassportService to use auth middleware.
This is because the service has a dependency on expressApplication. Dependency on expressApplication seems to be good only for classes that inherit ServerLoader. 
Using express.use everywhere could be confused.

```typescript

import * as Passport from "passport";
import {Strategy} from "passport-local";
import {Service, BeforeRoutesInit, AfterRoutesInit} from "@tsed/common";
import {UserService} from "./UserService"; // other service that manage the users account

@Service()
export class PassportLocalService implements BeforeRoutesInit, AfterRoutesInit {

    constructor(private serverSettings: ServerSettingsService,
                private userService: UserService,
                @Inject(ExpressApplication) private  expressApplication: ExpressApplication) {

    }

    $beforeRoutesInit() {
        const options: any = this.serverSettings.get("passport") || {} as any;
        const {userProperty, pauseStream} = options; // options stored with ServerSettings

        this.expressApplication.use(Passport.initialize({userProperty}));
        this.expressApplication.use(Passport.session({pauseStream}));
    }

    $afterRoutesInit() {
        this.initializeSignup();
        this.initializeLogin();
    }
```

**Comment by Romakita** [comment]
I don't understand the problem with this code (and it's just an example). ExpressApplication is a factory and it can be injected everywhere. Not exclusively in the ServerLoader.
For example SocketIOService use HttpServer and HttpsServer factories, it's the same case than ExpressApplication.
