### ISSUE TITLE
Loading custom configurations

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#311]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
Hi!

Just starting to learn this framework and I am starting to love it!
One question though,

I want to load custom configurations into my server from an external file and/or from environment specific files (dev/qa/test/prd). I saw the `@Const` and `@Value` decorators, so I was wondering how can I load custom values into them.

This project really reminds me of SpringBoot (which I also love), and they also have this functionality.

Thanks for your help,

Tomer

**Comment by Romakita** [comment]
Hi @TomerAmirV,

I think you can do that:
```typescript
// conf.ts
import {deepExtends, EnvType} from "@tsed/core";

export const conf = {
     myConstant: "test",
     my: {
        value: "test"
     }
     // ... defaultConfig
};

deepExtends(conf, require('./conf/settings.json'));

if (process.env.NODE_ENV === EnvType.PROD) {
    deepExtends(conf, require('./conf/prod.settings.json'));
}
```
In your server Loader
```typescript
import {conf} from "./config/conf";

@ServerSettings(conf)
export class Server extends ServerLoader{

}
```
Then:

```typescript

@Service()
export class MyService {
    @Constant("myConstant")
    prop1: string;
   
    @Value("my.value")
    prop2: string;
}
```

I should work :)
See you

**Comment by kalu111** [comment]
Also, You can create a wrapper for your config

```typescript
@Service()
class ConfigService {

   private config: Map<string, any>;
   
   async $onInit() {
       this.load();
   }

   get(key) {
     this.load();
     return this.config.get(key);
   }

   private load() {
      if (!this.config) {
          // load config
      }
   }
}
```

Other way, there is a great place to create predefined service which we can override by `@OverrideService()` decorator. Such predefined service should be initialized before other services, becouse other services should have an access to config on initialization stage.
Config data loaded from that service should be accessible from `@Value()` and `@Constant()`.
It is also a great place to set server settings.
The main idea is to manage appliaction's config in one place.

What do you think @Romakita?

**Comment by Romakita** [comment]
@kalu111 It's possible but not recommended. The `ServerSettingsService` contain some methods use by the framework.
It also possible to use the `globalServerSettings` instance like this:

```typescript
import {globalServerSettings, ServerSettingsService} from "@tsed/common";

@Service()
class ConfigService {
   constructor(private settingsService: ServerSetttingsService){

   }

  get myProp(){
     return this.settingsService.get('myProp');
  } 
  static configure(){
       const conf = require('../configs/settings.default.json');

       if (process.env.NODE_ENV === EnvType.PROD) {
          deepExtends(conf, require('./conf/prod.settings.json'));
       }
       globalServerSettings.set(conf);
  }
}

ConfigService.configure();
```
I thinks this approach is better :)

See you,
Romain

**Comment by TomerAmirV** [comment]
Thanks for your responses!
I'll check both ways and see what works best for me 😄

**Comment by kalu111** [comment]
Hi,
Thanks @Romakita for your example.
I have a similar solution.

But I try to override `ServerSettingServer` only for `read` purposes, and my code does not work.
What am I doing wrong?
```typescript
import { OverrideService, ServerSettingsService } from '@tsed/common';
import * as config from 'nconf';

@OverrideService(ServerSettingsService)
export class OverrideServerSettingsService extends ServerSettingsService {

    get<T>(propertyKey: string): T {
        let value = super.get(propertyKey);

        if (undefined === value) {
            value = config.get(propertyKey);
        }

        return <T>value;
    }
}
```

**Comment by Romakita** [comment]
@kalu111 I think the ServerSettingsService is a bit specific because this service is built manually when the server is started. 
Actually, I work on the containerization in Ts.ED. I would look for the override of the configuration is possible.
See you

**Comment by kalu111** [comment]
Hi,
Did you check if it is possible?

**Comment by awaragi** [comment]
Why not simply use an external dependency Config package for your projet?

**Comment by kalu111** [comment]
I'm using an external config package, but I want to have posibility to read config values by using `@Value()` decorator. But to do that I need to override `ServerSettingsService`.

For me is the best, cleanest way to use class instead creating more complicated logic :) 

@Romakita When to expect a release ?

**Comment by Romakita** [comment]
@kalu111 You can already use `@Value()` without override the ServerSettingsService.

This code works:
```typescript
const conf = require('./conf.dev.json'); // Something like that {'myCustomKey': 'value'}

@ServerSettings({
   mount: {
   },
   ...conf,
   // or
  conf
})
```
Then:
```typescript
@Service()
class MyService {
   @Value('myCustomKey')
   myCustomKey: string;
  
  @Value("conf.myCustomKey")
  myCustomKey: string;
}
```
So I don't know why you need to override the service, if your need. is to use this decorator ;).

Well, to answer, I work on. This week, I guess, the feature will be released.

See you,
Romain

**Comment by kalu111** [comment]
Thanks @Romakita 
I need it because it allows me to inject more complex config logic (from db or micro service).
That's all :)

**Comment by Romakita** [comment]
PR #376 will allow to override the ServerSettingsService (and more). I need help to review, and test the branch with a reel project :)

**Comment by kalu111** [comment]
Hi @Romakita ,
I will try to test it tomorrow :)

Bye.

**Comment by milewski** [comment]
@kalu111 it has been merged to master already, have a try see if the latest `^4.20.2` works for you

**Comment by kalu111** [comment]
Hi, Thanks for info :)
But my code is not called
```typescript
import { OverrideService, ServerSettingsService } from '@tsed/common';
import * as config from 'nconf';

@OverrideService(ServerSettingsService)
export class OverrideServerSettingsService extends ServerSettingsService {

    get<T>(propertyKey: string): T {
        let value = super.get(propertyKey);

        if (undefined === value) {
            value = config.get(propertyKey);
        }

        return <T>value;
    }
}
```

**Comment by kalu111** [comment]
Hi,
Did you test it properly?

With `@OverrideService` an instance of class is never created.
With `@Service` an instance of class is created but `get()` method is called only once with `logRequestFields` key - strange :(

How to properly override `ServerSettingsService`?
I have found an `@OverrideProvider` decorator but it doesn't help too.

**Comment by Romakita** [comment]
Fixed

**Comment by Romakita** [comment]
Latest version :)

**Comment by Romakita** [comment]
You can use OverrideService or OverrideProvider. Then import your service in the Server.ts like that:

```typescript
import "./services/CustomConfigService";

@ServerSettings()
class ServerLoader {

}
```

**Comment by TomerAmirV** [comment]
I just upgraded, and I am still using the following method:

```typescript
const conf = require('./conf.dev.json'); // Something like that {'myCustomKey': 'value'}

@ServerSettings({
   mount: {
   },
   ...conf,
   // or
  conf
})
```

For some reason, I stopped getting the values when using `@Constant` or `@Value`

Is this method deprecated?

**Comment by TomerAmirV** [comment]
I just upgraded to version `4.22.1` and I am still using
```typescript
const conf = require('./conf.dev.json'); // Something like that {'myCustomKey': 'value'}

@ServerSettings({
   mount: {
   },
   ...conf,
   // or
  conf
})
```
and not it seems like `@Constant` and `@Value` stopped working for me...

Is this method deprecated?

**Comment by Romakita** [comment]
What is your log error ?

**Comment by TomerAmirV** [comment]
No error from tsed, I just get an undefined value

**Comment by Romakita** [comment]
Ok, can you send me the code with the `@Constant` or `@Value` please ?

**Comment by TomerAmirV** [comment]
Sure 😄 

Code using decorators:

```typescript
@Service()
export default class RedisService {
	@Constant('redis.host')
	private static redisHost;

	constructor() {
		this.redis = new Redis(RedisService.redisHost);
	}
}
```

Error:
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

logging the value prints: `undefined`

**Comment by Romakita** [comment]
Ok, I'll try to solve it :)

**Comment by Romakita** [comment]
ho shit... I know what is the problem. Now, the injector create your instance and bind your properties with Constant and Value after calling the constructor. I introduced a breaking change without thinking about it. My work about containerization impact some decorator like Constant or Value.

You can fix your code with the $onInit hook:
```typescript
import {Env} from "@tsed/core";
import {Constant, Value} from "@tsed/common";

export class MyClass {

    @Constant("env")
    env: Env;

    @Value("swagger.path")
    swaggerPath: string;

    @Value("swagger.path", "defaultValue")
    swaggerPath: string;

    constructor() {
       console.log(this.swaggerPath) // undefined. Not available on constructor
    }
    $onInit() {
      console.log(this.swaggerPath)  // something
    }
 }
```

**Comment by TomerAmirV** [comment]
I tried and it doesn't seem to work... I'll try again tomorrow (it's late here 😄)

I don't this that I'll have any issue to switch (if it's working) if there will be no issues with dependency injection... (not sure in what order things are done)

I'll test and report back here

**Comment by TomerAmirV** [comment]
@Romakita 
I tried to use `onInit`, but it doesn't seem to work... tried tsed 4.22.1 and 4.23.0

**Comment by Romakita** [comment]
$onInit ?

**Comment by TomerAmirV** [comment]
yes

**Comment by Romakita** [comment]
Strange...

**Comment by Romakita** [comment]
@TomerAmirV For me it works fine.
Here code example:  
Server => https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-basic/src/Server.ts#L16
Service => https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-basic/src/services/calendars/CalendarsService.ts#L10-L19

The log display correctly the value of the constant.
See you

**Comment by TomerAmirV** [comment]
@Romakita 
you are working with version: `@tsed/common": "^4.19.0` 😄 
look here https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-basic/package.json

**Comment by Romakita** [comment]
@TomerAmirV ^4.19.0 mean the version latest can be installed locally too. And my test work with the latest version :)

**Comment by Romakita** [comment]
https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-basic/yarn.lock#L103
Yarn.lock use the 4.23.1 ;)

**Comment by TomerAmirV** [comment]
Ok... found out why it's not working for me...
I declared the field as `private static`:
```typescript
@Service()
export class MyService {
	@Constant('presence.redis.host')
	private redisHost;

	private redis: Redis.Redis;

	$onInit() {
		this.redis = new Redis(this.redisHost);
	}
}
```

When I removed the `static` modifier it started working...

I will change it for now, but what do you think about this?

**Comment by Romakita** [comment]
Before it worked because the configuration was accessible globally. Now the configuration is in a container and is not accessible from a static property.

But isn't a problem if you change remote the static keyword, because the service is a singleton :).

**Comment by TomerAmirV** [comment]
Thanks @Romakita !
Awesome work 👍
