### ISSUE TITLE
Issue stubbing methods called in beforeRoutesInit lifecycle hook when testing using mocha and sinon

### ISSUE THREAD

**Issue by loganforsyth** [Romakita/ts-express-decorators#313]
I am writing some tests using mocha for a rest API, I am using the bootstrap function to start the server, supertest to call the application and using sinon to stub database calls and to stub other external calls. The issue I am having is when I am trying to stub a method that is called in the beforeRoutesInit lifecycle hook the method doesn’t get stubbed if it is not in the first test file that is run. From what I understand once you start the server with bootstrap it will not restart the server between test files and won’t recall any of the lifecycle hooks. 
Is there any way to have the Server restart, re initiate all services and controllers and all the lifecycle hooks?

**Comment by Romakita** [comment]
Hi @loganforsyth ,

Actually, is not really possible properly because Ts.ED hasn't a container. I work on this part to have the possibility to start the server with different context and several times.

But you can hack the bootstrap (I do that in my own) with the inheritance. Example:
```typescript
import {Server} from "../src/Server";
@ServerSettings({}} // optional if you don't wan't override the default configuration from your original server
class TestServer extends Server{
     beforeRoutesInit() { // now this hook is empty 
     }
}

describe("Rest API", () => {

    before(bootstrap(TestServer));
    before(inject([ExpressApplication], (expressApplication: ExpressApplication) =>
        this.app = SuperTest(expressApplication)
    ));

    describe("GET /api-doc/swagger.json", () => {

        before((done) => {
            this.app
                .get("/rest/calendars")
                .expect(200)
                .end((err: any, response: any) => {
                    this.spec = JSON.parse(response.text);
                    done();
                });
        });

        it("should have a swagger version", () => {
            expect(this.spec.swagger).to.be.eq("2.0");
        });
   })
});
```
I hope this example will help you.

See you,
Romain
