### ISSUE TITLE
[Improvement/Request] Jest support

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#318]
## Informations

Type | Version
---|---
Improvement| 4.x+

****

## Description
You probably heard about [Jest](https://facebook.github.io/jest/) which is an awesome testing framework which makes things much easier (IMO) for testing. they also support typescript and has built-in coverage reporting.

If you could add support for it, it would be awesome. I tried wiring it myself, but I think that something fails in the `bootstrap` function.

Thanks!

**Comment by mikerhyssmith** [comment]
Hey @TomerAmirV I've been using Jest with tsed, have you got a snippet of the test you're having trouble with ?

**Comment by TomerAmirV** [comment]
Actually, I solved most of the issues I had yesterday. now I am just having an issue where the 3000 port is not released after the test is terminated, causing issues in the next runs. also, why is a port being allocated for tests?

Here is my current test file:
```js
import {inject, bootstrap} from "@tsed/testing";
import {ExpressApplication} from "@tsed/common";
import * as SuperTest from "supertest";
import {Server} from "../../server";
import {$log} from "ts-log-debug";


describe('test', () => {

	beforeAll(() => {
		$log.level = "OFF";
	});

	beforeEach(bootstrap(Server));

	test('my test', inject([ExpressApplication], (app: ExpressApplication) => {
		SuperTest(app).get('/api/account/123').then(response => {
			expect(response.status).toBe(404);
		});
	}));
});

```

**Comment by TomerAmirV** [comment]
I dug a little deeper, and this seems like a problem with the `bootstrap` functions.
It's supposed to replace the `startServers` in the ServerLoader class with a function that does nothing, but it does not work for some reason when I am using jest.

**Comment by TomerAmirV** [comment]
Nevermind... found the issue.
I called:
```js
new Server().start();
```
in my `server.ts` file. This allocated the port, and then the bootstrapper created another instance properly.
