### ISSUE TITLE
@OverrideMiddleware not working in v13.0.*

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#320]
Something has changed on the commit: https://github.com/Romakita/ts-express-decorators/commit/bd7dec4 which makes all my APIs endpoint return HTML instead of JSON

`4.12.4`
```json
{
    "success": false,
    "message": "User already exists.",   
}
```

`4.13.0`
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>
             Error: User already exists.          
        </pre>
    </body>
</html>
```

The issue is that im using a `GlobalErrorMiddleware` with `@OverrideMiddleware`

```ts
@OverrideMiddleware(GlobalErrorHandlerMiddleware)
export class GlobalErrorMiddleware {
   use(){
      console.log('Not Called in v4.13.0')
   }
}
```

Im trying to identify on the commits but nothing seems obvious to me at this point..

**Comment by Romakita** [comment]
Ok i'll inspect that. The cause is the refactoring about registries.

**Comment by Romakita** [comment]
@milewski  Fixed :)
