### ISSUE TITLE
[Question] Multiple Swagger API Docs in a single server

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#322]
## Informations

Type | Version
---|---
Question | 4.12.4

****

## Description
Is there a way to have different swagger API docs for different controllers?
I am building a server which actually holds multiple modules with different responsibilities, and I would like the modules to be documented separately (it is later published to a WSO2 API gateway, so it's important that each API doc will hold only the endpoints related to the specific use they serve).

Thanks!

**Comment by Romakita** [comment]
@TomerAmirV Actually not. You can hide some controllers from  documentation with `@Hidden`decorators. But create two or more docs is not supported. 

See you,
Romain

**Comment by Romakita** [comment]
Maybe we can use tags field to create documentation per tag in a future version of `@tsed/swagger`.

**Comment by TomerAmirV** [comment]
Thanks for the quick answer!
could this be added?
It's not that uncommon. here is a Java Spring implementation to what I mean:
https://github.com/springfox/springfox-demos/tree/master/boot-swagger

**Comment by Romakita** [comment]
No problem. Just, I need a time to dev that :).

**Comment by Romakita** [comment]
Released with v4.14.0

**Comment by TomerAmirV** [comment]
Thanks a lot! 🎉 😃

**Comment by Romakita** [comment]
Doc: https://romakita.github.io/ts-express-decorators/#/tutorials/swagger
