### ISSUE TITLE
Swagger - map of custom object

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#329]
## Informations

Type | Version
---|---
Bug/Improvement/Question | 4.13.5

****

## Description
I am trying to create an object which holds a `Map` of another object like this:
```ts
export default calls Parent {
	@Property()
	children: Map<string, Child>;
}
```

The problem is that I do not get a swagger file with `additionalProperties`:
```json
{
    "definitions": {
        "Parent": {
            "properties": {
                "children": {
                    "type": "object"
                }
            },
            "type": "object"
        }
    }
}
```
But the desired result is:
```json
{
    "definitions": {
        "Parent": {
            "properties": {
                "children": {
                    "additionalProperties": {
                        "$ref": "#/definitions/Child"
                    }
                }
            },
            "type": "object"
        }
    }
}
```
I saw #279 and even tried to use `@Any()` or another decorator with no success.

Am I doing something wrong?

Thanks!

**Comment by Romakita** [comment]
Hello @TomerAmirV ,

Just try that:

```typescript
export default calls Parent {
	@PropertyType(Child)
	children: Map<string, Child>;
}
```

See you,
Romain

**Comment by TomerAmirV** [comment]
Hi @Romakita and thanks for the quick response!

I tried this way, but the result is the same as in arrays, which causes problems with code generators from swagger.

Here is the result:
```json
{
    "definitions": {
        "Parent": {
            "properties": {
                "children": {
                    "$ref": "#/definitions/Child"
                }
            },
            "type": "object"
        }
    }
}
```

**Comment by Romakita** [comment]
Hello @TomerAmirV,
I tried my example and it works fine. Can you send me your Child and Parent model, and the context where you use the model in the controller ? Please :)

See you,
Romain

**Comment by TomerAmirV** [comment]
Ok, this is weird,

I found out that this issue happens when I use `"ts-node": "^5.0.1"` and does not happen when using `"ts-node": "^6.0.0"`

I have no clue as to why this happens, but for now, it's working.

Thanks for your help!

**Comment by TomerAmirV** [comment]
Actually, I still have an issue.
[Reading a bit online](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties) (I it's the same for [OAPI 3](https://swagger.io/docs/specification/data-models/dictionaries/)), it seems like the correct way to represent a map in swagger is like this:
```js
{
    "definitions": {
        "Parent": {
            "properties": {
                "children": {
                    "type": "object", // <---- This is currently missing
                    "additionalProperties": {
                        "$ref": "#/definitions/Child"
                    }
                }
            },
            "type": "object"
        }
    }
}
```
The type of the `property` itself is missing for me. (as can be seen above)

This causes some issues with some client generators. Am I still doing something wrong? here is my parent class again:
```typescript
export default calls Parent {
	@PropertyType(Child)
	children: Map<string, Child>;
}
```

Thanks again

**Comment by Romakita** [comment]
@TomerAmirV I'll check the generated spec.

See you,
Romain

**Comment by TomerAmirV** [comment]
Thanks!
I checked and the fix works fine 😄
