### ISSUE TITLE
unable to retrieve class properties with .toJSON()

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#330]
## Informations

Type | Version
---|---
Bug/Improvement/Question | 4.13.6

Im not able to call toJSON() into classes that has being decorated with `@Required` for example:

```ts
export class RegisterRequest {

    @Required()
    @Email()
    email: string

    @Required()
    @MinLength(6)
    password: string

    @Required()
    @MinLength(6)
    passwordConfirmation: string

    @Required()
    @Default(false)
    acceptTerms: boolean

    @Property()
    referralID?: string

}
```

`RegisterRequest.prototype.toJSON() -> //nothing empty string`

however the following works:

```ts
export class RegisterRequest {

    @Email()
    email: string

    @MinLength(6)
    password: string

    @MinLength(6)
    passwordConfirmation: string

    @Default(false)
    acceptTerms: boolean

    @Property()
    referralID?: string

}
```

```ts
RegisterRequest.prototype.toJSON() -> { 
  email: undefined,
  password: undefined,
  passwordConfirmation: undefined,
  acceptTerms: undefined,
  referralID: undefined
}

```

i believe that the `@Required` might be overriding the metadata for the classes properties...

**Comment by Romakita** [comment]
It's normal to use the RegisterRequest.prototype.toJSON via it's prototype ? It's a bit strange.

**Comment by Romakita** [comment]
I think I'll even remove this method add on the stolen models because it's really dirty

**Comment by milewski** [comment]
Yeah getting the properties directly from the `PropertyRegistry` is much better...
