### ISSUE TITLE
Swagger UI serves the same spec when using multiple specs

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#335]
## Informations

Type | Version
---|---
Bug | 4.14.0

****

## Description
This is a bug relates to #332 
The issue is that when using multiple specs and trying to reach the Swagger UI, the same spec is returned.

**Note**: The `swagger.json` spec is fine.

I believe the issue is caused by [this line](https://github.com/Romakita/ts-express-decorators/blob/master/src/swagger/services/SwaggerService.ts#L60) since in every iteration the same middleware is used for all endpoints, so basically it's being overwritten and the last spec is served for all instances.

I think that having a swagger-ui instance for each spec will fix this issue, or, the same ui will serve all specs in a dropdown. I know that the original swagger ui lib supports it, but not sure if `swagger-ui-express` supports it.

**Comment by Romakita** [comment]
@TomerAmirV ,

SwaggerService create an Express.Router, it's normal if you have the "/" when the swagger-ui middleware is added. The final path is determined by https://github.com/Romakita/ts-express-decorators/blob/master/src/swagger/services/SwaggerService.ts#L66
and it depend directly from your configuration.

As explained in the documentation, you need to configure a route for each swagger configuration like this:

```typescript
@ServerSettings({
  rootDir: __dirname,
  swagger: [
    {
      path: "/api-docs-v1",
      doc: 'api-v1'
    },
    {
      path: "/api-docs-v2",
      doc: 'api-v2'
    }
  ]
})
```
> Note: path for each configuration must be different!

This configuration will not work:
```typescript
```typescript
@ServerSettings({
  rootDir: __dirname,
  swagger: [
    {
      path: "/api-docs",
      doc: 'api-v1'
    },
    {
      path: "/api-docs-v2",
      doc: 'api-v2'
    },
    {
      path: "/api-docs",
      doc: 'api-v3'
    }
  ]
})
```
> Only, the first configuration will be accessible when express solved the routing path.

`swagger-ui-express` didn't provide documentation to load multiple spec with the same instance.

So, just check your configuration according to my previous example. If it doesn't work, send me your configuration to reproduce the problem.

See you,
Romain

**Comment by TomerAmirV** [comment]
Hi @Romakita 

I understand what you meant I should do. The docs are clear 👍 

Here are my server settings:
```typescript
@ServerSettings({
	httpPort: 3001,
	httpsPort: false,
	mount: {
		"/api": `./controllers/**/*.ts`
	},
	componentsScan: [
		`./services/**/**.ts`,
		`./middlewares/**/**.ts`
	],
	swagger: [
		{
			path: "/ctrl1/api-docs",
			doc: "doc1",
			showExplorer: true
		},
		{
			path: "/ctrl2/api-docs",
			doc: "doc2",
			showExplorer: true
		}
	]
})
export class Server extends ServerLoader {
...
```

I have two controllers, `Ctrl1` and `Ctrl2` each of them has a corresponding `@Docs('doc1')` or `@Docs('doc2')` decorator.

The issue is when I am trying to access `http://localhost:3001/ctrl1/api-docs` I am getting the ``http://localhost:3001/ctrl2/api-docs` page. I debugged, and I'm pretty sure that the line I sent you causes the issue. this is not because of the path (I understand how the `express` router works), but because the configuration passed to `swagger-ui-express` is overwritten.

I really appreciate your time and help, and you are doing a really good job,

Tomer

**Comment by Romakita** [comment]
Ok I found the problem. My swagger-ui-express version isn't the latest. v2 work fine, v3 use a singleton...
It's a problem, because swagger-ui-express doesn't provide a way to configure multiple spec.

**Comment by TomerAmirV** [comment]
I am working around it using the `showExplorer` setting and entering the `swagger.json` path that I want to view, but this it would be preferable if there would be a workaround.
I understand that you are limited by `swagger-ui-express`. [found this](https://github.com/scottie1984/swagger-ui-express/issues/65) in their repo. seems like it could help?

**Comment by Romakita** [comment]
The fix will be release soon ;)

**Comment by Romakita** [comment]
v4.14.1
