### ISSUE TITLE
Is it possible to get a random port assigned by the OS?

### ISSUE THREAD

**Issue by Szauka** [Romakita/ts-express-decorators#336]
## Informations

Type | Version
---|---
Question | 3.7.x

****

## Description
Is it possible to get a random port assigned by the OS, while using the @ServerSettings() decorator ?

## Todos

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (question)

Something like this example: 
<pre>
var app = module.exports = express();
var server = http.createServer(app);

var start = function() {
    //listen to a random port that the OS assigns
    server.listen(0, function() {
        app.set('port', server.address().port);
    });
}
</pre>

**Comment by Romakita** [comment]
@Szauka currently not. This new feature can be added.

**Comment by Romakita** [comment]
PR ready
