### ISSUE TITLE
Broken Swagger documentation on version v4.14.1

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#337]
After upgrading to version `v4.14.1` my docs started to shows up this message... 

![image](https://user-images.githubusercontent.com/2874967/39185990-a79203f4-47fb-11e8-9772-94a4163b4257.png)

![image](https://user-images.githubusercontent.com/2874967/39186158-244a6bd4-47fc-11e8-94fc-e77123824607.png)

Im running the whole api inside of a docker container, prior this version `v4.14.1` everything was working fine..

**Comment by Romakita** [comment]
Ok the new feature to make multiple swagger documentation has changed something...

**Comment by Romakita** [comment]
Can you send me the version of your swagger-ui-express ?

**Comment by Romakita** [comment]
@milewski Can you send me your configuration for swagger and the version of swagger-ui-express because I cannot reproduce your bug.

**Comment by mduthilleul** [comment]
Same problem here with ts.ed v4.12.2 & swagger-ui-express v3.0.8.

My swagger configuration : `swagger: [
    {
      path: '/swagger',
      doc: 'api',
    },
  ],`

Should we use swagger-ui-express v2 or v3 ? The release note suggest swagger v3 but tsed/swagger@4.14.2 has a peer depency of swagger-ui-express@^2.0.15.

And with swagger-ui-express 2.0.15 I have the following error: `Error: Cannot find module 'swagger-ui-express/swagger-ui-init.js'`

**Comment by Romakita** [comment]
yes, I forgot to update the peerDependency. But v3 should be works.

**Comment by Romakita** [comment]
@milewski & @mduthilleul I confirm, you need to install swagger-ui-express v3. I realize, v2 and v3 has a lot of change. I can't support v2 anymore because multiple swagger docs require v3 and I use a small hack to do that... I assume my implementation isn't not good. 
Maybe it's a time to remove the dependency with swagger-ui-express and implement this feature directly inside the `@tsed/swagger`.

**Comment by Romakita** [comment]
@milewski I've test your configuration. It's work with v3, but you need to add annotation on your all controllers when you use `doc: 'api'`.

```typescript
@Docs('api')
class MyController {

}
```

**Comment by mduthilleul** [comment]
@Romakita It's what I have done, but it's not working for me. 
I'm using Node 9.11.1 on MacOS

**Comment by milewski** [comment]
wow im late for the conversation... but here we go:

> Can you send me the version of your swagger-ui-express ?

i have being using the latest version `^3.0.8` since always... 

> I've test your configuration. It's work with v3, but you need to add annotation on your all controllers when you use doc: 'api'.

i have just tried it...  didnt work..

-----

If i open the documentation trough: `http://0.0.0.0:9000/documentation`  as the second screenshot shows... it works normally as before.. however because i am running it trough docker, i cannot access my container trough `0.0.0.0` on my host machine.. instead docker "binds" the port `:9000` to my `localhost:9000`, so when i try to access trough `localhost:9000` the swagger shows that problem due to CORS,

**Comment by milewski** [comment]
Changing this line to my actually hostname im using solves the issue to me: 

https://github.com/Romakita/ts-express-decorators/blob/056f7c0a0cc2882afa162e72922adad08a9d46cf/src/common/config/class/ServerSettingsProvider.ts#L317

why is it hardcoded to `0.0.0.0` ? 0.0.0.0 doesn't work on windows machine

**Comment by Romakita** [comment]
hooo....yes, I've missed that...

**Comment by milewski** [comment]
`0.0.0.0` means bind to all network interfaces available, so if i start my server listening on `0.0.0.0`, means i will be able to access it through: `localhost`, `173.0.10.1`, `192.168.1.80` or whatever other interface i have available ... but i wont be able to access it trough -> because it is not a valid address (at least on windows) `http://0.0.0.0`

**Comment by Romakita** [comment]
Yes. The fix is ready. Release is coming soon ;)

**Comment by Romakita** [comment]
released !

**Comment by milewski** [comment]
thanks! confirmed it's working now :)

**Comment by milewski** [comment]
i think swagger requires an absolute URL to works properly

![image](https://user-images.githubusercontent.com/2874967/39229362-128d23ac-4895-11e8-940e-40272214abbc.png)

i have noticed this element appeared on the bottom of my page i guess this is just an extra check that swagger does to see if the schema is correct.. but it fail because swagger was set to a relative url instead of an absolute one...

**Comment by Romakita** [comment]
swagger-ui-express make me crasy...

**Comment by Romakita** [comment]
@milewski I've created a new branch without swagger-ui-express. Now `@tsed/swagger` use directly the official package swagger-ui-dist.

If you have a time, can you try this branch https://github.com/Romakita/ts-express-decorators/tree/feat_swagger_ui_integration with your project ?

See you,
Romain

**Comment by milewski** [comment]
@Romakita i just tested here... i cant get it to work... the "instruction" to open swagger docs dissapeared, accessing: `http://localhost:9000/documentation/` returns `Cannot GET /documentation/`

```
[2018-04-26T00:34:53.008] [INFO ] [TSED] - HTTP Server listen on http://0.0.0.0:9000
[2018-04-26T00:34:53.009] [INFO ] [TSED] - HTTP Server listen on https://0.0.0.0:8000
[2018-04-26T00:34:53.009] [INFO ] [TSED] - Started in 977 ms
```

**Comment by milewski** [comment]
never mind i just realized i forgot to install `swagger-ui-dist` the new peer dependency 😄 yeah it woooorks

but that error at the bottom of the page is still present:

![image](https://user-images.githubusercontent.com/2874967/39261216-6534789a-48ee-11e8-8fbe-1d82eb2b7603.png)

**Comment by Romakita** [comment]
Fixed :)

**Comment by milewski** [comment]
broken here 😮 

![image](https://user-images.githubusercontent.com/2874967/39504632-7994f592-4dff-11e8-8f72-2d2de488d91b.png)

**Comment by Romakita** [comment]
Yes. Just a problem with the url. Add a slash in your browser "http://localhost:9000/documentation/".
I don't know why I don't see that... I'll check with swagger-ui-express how he manage the url with "/" and without "/".
See you

**Comment by Romakita** [comment]
Maybe express has changed the behavior with the "/" trailing. I fixed the problem with a middleware.
See you,
Romain

**Comment by Romakita** [comment]
Fixed :)

**Comment by milewski** [comment]
confirmed working ! thanks again 👍
