### ISSUE TITLE
@Default decorator not working with falsy values

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#338]
```js
@Model(...)
export class Product {

    @Default(false or 0) // <-- setting this option to false or 0 takes no effect... 
    availability: ?

 ....

    @Default(true | -1 | 'string') // <-- setting this option to true -1 or any string: works as expected.. 
    availability: ?

}
```

the model created results in something like this

```text
/* 1 */ using @Default(true)
{
    "_id" : ObjectId("5ae04db8dd3c80e7efdb5e98"),
    "availability" : true, 
    "version" : 0
}
/* 2 */ using @Default(false)
{
    "_id" : ObjectId("5ae04dd0ba74c9e7f56e9548"),
    "version" : 0
}
```

i believe that somewhere it is actually doing a if(value) check.. to see if that option is empty or no but it is failing because the value is actually false...

**Comment by Romakita** [comment]
@milewski Can you fix this bug ? ^^

**Comment by Romakita** [comment]
haaa ... shit ok. I'll take a time found the problem ;)

**Comment by Romakita** [comment]
Haaaaaaaa .... the problem come from the merge method. Hum... T.T

**Comment by milewski** [comment]
that `deepExtends` thing? could u use a library to deal with extending an object? it can be very tricky to do by hand...

**Comment by Romakita** [comment]
The safe way is to change the default decorator implementation:

```typescript
export function Default(defaultValue: string | number | boolean | {}) {
    return decoratorSchemaFactory((schema: JsonSchema) => {
        schema.set("default", defaultValue);
    });
}
```

**Comment by milewski** [comment]
just to note Infinity value also gets ignored:

```
export class Variant {
    @Default(Infinity)
    quantity: number
}
```

**Comment by Romakita** [comment]
@milewski `.toString` on the decorator is a little bit brutal :p, because AJV use this information and I don't know what is the behavior in this case.

For the deepExtends function, library doesn't provide the same behavior. Is not a simple extends. For example, Array and Object will be merged. 

I'll fix asap this decorator ;)

**Comment by milewski** [comment]
i have come across some deepExtend libraries before even made one myself.. many out there let you add / or pick a custom logic for merging arrays maybe one could have the functionality your deepExtends does built in? https://www.npmjs.com/package/deepmerge

**Comment by Romakita** [comment]
Problem found. It come from the clean method in `@tsed/mongoose` pacakge.

**Comment by Romakita** [comment]
Fixed :)

**Comment by milewski** [comment]
tested working now thanks 👍

**Comment by milewski** [comment]
hi @Romakita, there is something wrong with the `@Default()` decorator again in version `4.26.3` (im not sure which version the problem started), now any value that i set with default always return as undefined:

```ts
export class UserProductsRequest {

    @Default(false)
    draft: boolean

}


async index(@BodyParams() { draft }: UserProductsRequest) {
    console.log(draft) // undefined
}

```

**Comment by Romakita** [comment]
@milewski Default is used only to set metadata. It didn't change the behavior of your property.

According to the documentation, the default value must be also assigned to your property:
```typescript
class Model {
  @Default("10")
   property: string = "10";
}
```
> I agree, it's redundant XD

See you ;)
