### ISSUE TITLE
Error getting swagger ui after updating to 4.15.0

### ISSUE THREAD

**Issue by floriantraber** [Romakita/ts-express-decorators#344]
## Informations

Type | Version
---|---
Bug/Improvement/Question | 4.15.0

****

## Description
Calling the swagger ui endpoint produces the following error: 

> ENOENT: no such file or directory, open 'D:\myproject\node_modules\@tsed\swagger\lib\views\index.ejs'

The swagger.json endpoints works.

**Comment by Romakita** [comment]
@floriantraber Thanks for your issue ;) . The fix will be released with v4.15.1

**Comment by dsasidhar** [comment]
@Romakita Having similar issue after updating to 4.31.6.
`Error: ENOENT: no such file or directory, open '/project-path/node_modules/@tsed/swagger/lib/views/index.ejs`

When I tried to open up the `node_modules` there is no folder named `views` in `@tsed/swagger`

**Comment by Romakita** [comment]
Sorry. The latest has reintroduced the bug. Problem with the relative links. I'll fix that again...
