### ISSUE TITLE
@Allow() decorator not working

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#348]
Have just tried this out and looks like this decorator is not working:

```ts
export class userModel {

    @Required() // <-- have also tried passing '' in here
    @Allow('') // <-- preferably setting this to null would be better than empty string
    email: string

    @Required()
    @Allow('') 
    password: string

}
```

```ts
const user = await userModel.create({ password: null, email: null }) // doesn't work
const user = await userModel.create({ password: '', email: '' }) // doesn't work
const user = await userModel.create({ password: 'abc', email: 'abc' }) // works
```

Error

```
users validation failed: password: Path `password` is required., email: Path `email` is required.
```

optimally i think setting `@Allow(null)` is better than an empty string

**Comment by Romakita** [comment]
Ok I found the problem. After the fix, you can use allow as following:

```typescript
export class userModel {

    @Required() 
    @Allow('', null) // allow accept a list of value (null, '', undefined)
    email: string

    @Required()
    @Allow('', null) 
    password: string
}
```

**Comment by Romakita** [comment]
Fixed :)

**Comment by Romakita** [comment]
Ok. Can you send me the code of the `create` method. 
I tested with that:

```typescript
export class UserModel {

    @Required()
    @Allow(null)
    email: string

    @Required()
    @Allow(null)
    password: string
}

ConverterService.deserialize({email: null, password: null}, UserModel);
```
As you had mentioned in your first example. Now the problem is different because, the error, now,  come from mongoose and Allow has any effect with Mongoose validator.

**Comment by Romakita** [comment]
The problem is you have a many validator in your configuration. ConverterService validate the required value (with allow), then you have the AJV and to finish you have the mongoose. Conciliate all validators it's a hard work XD.

**Comment by Romakita** [comment]
I'll check if allow is possible with Mongoose.

**Comment by milewski** [comment]
the create method comes from mongoose: http://mongoosejs.com/docs/api.html#create_create

One option could be defining the required prop as a function and do some checking to allow the value or not... something like this: 
```
email: {
    type: String,
    required: function() {
        return doSomeCheckAgaintsTheGivenValue(value);
    }
}
```
