### ISSUE TITLE
[Bug] Swagger Multiple APIs get the same spec

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#355]
## Informations

Type | Version
---|---
Bug | 4.17.2

****

## Description
It seems like issue #335 has returned in version 4.15.0
When managing multiple APIs and trying to access the Swagger UI, all UI endpoints show the same spec.

This is probably caused by the move to the new swagger-ui lib in version 4.15.0

Thanks!

**Comment by Romakita** [comment]
@TomerAmirV For me it works fine. Can you send me your swagger configuration please ?

**Comment by TomerAmirV** [comment]
Sure 😄 

```typescript
import {IServerSettings} from "@tsed/common";

export const conf: IServerSettings = {
	httpPort: 3000,
	httpsPort: false,
	mount: {
		"/api": `./controllers/**/*.ts`
	},
	componentsScan: [
		`./services/**/**.ts`,
		`./middlewares/**/**.ts`
	],
	swagger: [
		{
			path: "/api1/api-docs",
			doc: "api1"
		},
		{
			path: "/api2/api-docs",
			doc: "api2"
		}
	]
};
```

**Comment by Romakita** [comment]
ok fixed :)

**Comment by Romakita** [comment]
v4.17.3

**Comment by TomerAmirV** [comment]
Thanks!!! 🎉
