### ISSUE TITLE
Service created twice

### ISSUE THREAD

**Issue by troyanskiy** [Romakita/ts-express-decorators#358]
## Informations

Type | Version
---|---
Bug | 4.17.x

****

## Description
Service created twice if it injected into middleware.

**Comment by Romakita** [comment]
Hum I can't reproduce your bug. Have you an example ? (copy your imports and decorator on middlewares, controllers, services + server settings configuration pls).

See you

**Comment by Romakita** [comment]
Ok I've found a reproducible example

**Comment by Romakita** [comment]
Fixed :)

**Comment by troyanskiy** [comment]
Cool! merci!
