### ISSUE TITLE
How to use the `invokeMethod` method from InjectorService?

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#365]
im following this: https://romakita.github.io/ts-express-decorators/#/docs/testing?id=mock-dependencies , it shows how to inject the dependencies on the constructor, how about injecting the dependency to the method? i have tried a bunch of combinations but none works, and seems the documentation is wrong: `{ this }` is invalid and it has been switched from `ControllerService` to `InjectorService` accordingly with the `deprecated` warning on the `ControllerService` class

```ts
  /**
   * Invoke a class method and inject service.
   *
   * #### IInjectableMethod options
   *
   * * **target**: Optional. The class instance.
   * * **methodName**: `string` Optional. The method name.
   * * **designParamTypes**: `any[]` Optional. List of injectable types.
   * * **locals**: `Map<Function, any>` Optional. If preset then any argument Class are read from this object first, before the `InjectorService` is consulted.
   *
   * #### Example
   *
   * ```typescript
   * import {InjectorService} from "@tsed/common";
   *
   * class MyService {
   *      constructor(injectorService: InjectorService) {
   *          injectorService.invokeMethod(this.method, {
   *              this,
   *              methodName: 'method'
   *          });
   *      }
   *
   *   method(otherService: OtherService) {}
   * }
   * ```
   *
   * @returns {any}
   * @param handler The injectable method to invoke. Method parameters are injected according method signature.
   * @param options Object to configure the invocation.
   */
  public invokeMethod(handler: any, options: IInjectableMethod<any> | any[]): any {
    return InjectorService.invokeMethod(handler, options);
  }
```

i

**Comment by Romakita** [comment]
Hi @milewski,
But my example doesn't show how to use `invokeMethod()` (it doesn't exists on ControllerService). The documentation isn't updated too, because it show the `ControllerService.invoke()` which is an alias to `InjectorService.invoke()` (this is why the method is deprecated now).

`InjectorService.invokeMethod()` is used only by the `@Inject` decorator in this case:

```typescript
class ServerLoader () {

    @Inject()
    $onMountingMiddlewares(service: Service) {
          
    }
}
```
But this way is little dirty and in future in think I'll remove this because it prevents me from setting up the containers / modules.

Have you a method/code which use injection on method ?

Romain

**Comment by milewski** [comment]
im looking to the `invokeMethod()` on the `InjectorService` this is my full example:

```ts
@Seeder()
export class UserTableSeeder implements SeederInterface {

    public handle(userService: UserService) {
        return Promise.resolve()
    }

}
```

```ts
bootstrap(Server)(async () => {

    const mongodb = InjectorService.get<MongooseService>(MongooseService)
    await mongodb.get().connection.dropDatabase()

    const seeders =  [
        UserTableSeeder,
    ]

    await InjectorService.load()

    const series = seeders.map(constructor => {
        const seeder =  InjectorService.invoke<SeederInterface>(constructor)
        return seeder.handle() // <-- needs user service
        /// InjectorService.invokeMethod(......) would like to use invokeMethod instead so all dependencies get resolved
    })

    Promise.all(series).then(() => {
        console.log('Seeder Completed.')
        process.exit()
    })

})
```

**Comment by Romakita** [comment]
Why you don't use the injector on constructor in UserTableSeeder ?
And your code is a unit test ? 

The right test: 
```typescript
describe('test', () => {
     let results;

     before(bootstrap(Server));
     before(inject([InjectorService, Done], (injector: InjectorService, done: Done) => {
        const mongodb = injector.get<MongooseService>(MongooseService);
        await mongodb.get().connection.dropDatabase();

        const seeders =  [
            UserTableSeeder,
        ];
        
        const series = seeders.map(constructor => {
              const seeder =  injector.invoke<SeederInterface>(constructor) // Injection work here, so UserService can be provided here.
              return injector.invokeMethod(seeder.handle.bind(seeder)); // not necessary but why not.
        });

        Promise.all(series).then((_results_) => {
             results = _results_;
             console.log('Seeder Completed.', results);
             done();
        });
     });

     it('should do somethings', () => {
           expect(!!results).to.be.true;
     });
});
```

**Comment by Romakita** [comment]
Haa yes, I forgot options. 

describe('test', () => {
     let results;

     before(bootstrap(Server));
     before(inject([InjectorService, Done], (injector: InjectorService, done: Done) => {
        const mongodb = injector.get<MongooseService>(MongooseService);
        await mongodb.get().connection.dropDatabase();

        const seeders =  [
            UserTableSeeder,
        ];
        
        const series = seeders.map(constructor => {
              const seeder =  injector.invoke<SeederInterface>(constructor) // Injection work here, so UserService can be provided here.
              return injector.invokeMethod(seeder.handle.bind(seeder), {
                   target: constructor, 
                   methodName: "handle" // I know is redundant but I haven't the choice
              }); // not necessary but why not.
        });

        Promise.all(series).then((_results_) => {
             results = _results_;
             console.log('Seeder Completed.', results);
             done();
        });
     });

     it('should do somethings', () => {
           expect(!!results).to.be.true;
     });
});

**Comment by milewski** [comment]
thanks `@Inject()` works 👍
