### ISSUE TITLE
Is it possible to make a "mock" at once several services

### ISSUE THREAD

**Issue by azanorth** [Romakita/ts-express-decorators#371]
## Is it possible to make a "mock" at once several services

Type | Version
---|---
Question | 4.5.4

****
Hello.
In order to make "mock" for the service, according to your documentation, I need to do this:
```typescript
    const locals = new Map<any, any>();

    locals.set(DbService, {
        getData: () => {
           return "test";
        }
    })
    const instance: MyCtrl = injector.invoke<MyCtrl>(MyCtrl, locals);
```
But if I need to do the "mock" of several services at once?
Something like that:
```typescript
    const localsFirst = new Map<any, any>();
    const localsSecond = new Map<any, any>();

    localsFirst.set(DbService, {
        getData: () => {
           return "test";
        }
    })
    localsSecond.set(SomeService, {
        getItem: () => {
           return "some";
        }
    })
    
    const instance: MyCtrl = injector.invoke<MyCtrl>(MyCtrl, [localsFirst, localsSecond]);
```
Is it possible to solve it somehow?

**Comment by milewski** [comment]
how about?

```ts
const services = [ DbService, SomeService ].map(service => {
    return (new Map<any, any>()).set(service, { getData: () => service.constructor.name })
})

const instance: MyCtrl = injector.invoke<MyCtrl>(MyCtrl, services);
```

**Comment by azanorth** [comment]
Looks good, but the "invoke" function has arguments:
```typescript
    invoke(target: any, locals?: Map<any, any>, designParamTypes?: any[])
```
The "locals" argument should not be an array, otherwise it will not work.
And from your example it turns out that both services (DbService and SomeService) get the same method - getData().
But in practice, each service must have different methods that return different data.
That's why I still need to look for another approach ((

**Comment by milewski** [comment]
i think there is no away around it my suggestion was that you can create a array containing your data and loop trough it, it is more of a code improvement that solution to this problem.. cuz i feel that u are afraid of repeating your self given you have many services to mock...

```ts
const myServices = [
   {
       service: DbService,
       options: {},
       methods: {
            getData: () => 'test',
            getItem: () => 'test'
       }
   }
]

myServices.forEach(({service, methods, options}) => {
      so anything you need here.....
})
```

**Comment by azanorth** [comment]
This is a good decision, but I did not mean that.
The function of the "invoke" does not pass the array.
For example: 
```typescript
    const instance: MyCtrl = injector.invoke<MyCtrl>(MyCtrl, [localsFirst, localsSecond]);
```
[localsFirst, localsSecond] - it will not work ((

**Comment by azanorth** [comment]
It seems like I forgot about it )))
Everything works good.
Thank you very much for your help )
