### ISSUE TITLE
Inconsistent property type with @QueryParams

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#384]
Hello @Romakita i noticed that these ways of retrieving the queryParams returns different results
 perhaps a bug? or you can not infer the type from an object? that doesn't have property decorators on it? 

`/someurl?images=true`

```ts
@Get('/')
async index(@QueryParams('images') images: boolean) {
    console.log(typeof images) // boolean = true
}
```

```ts
@Get('/')
async index(@QueryParams() options: { images: boolean }) {
    console.log(typeof options.images) // string = 'true'
}
```

```ts
export class Options {
    @Property()
    images: boolean
}

@Get('/')
async index(@QueryParams() options: Options) {
    console.log(typeof options.images) // boolean = true
}

```

**Comment by Romakita** [comment]
Hi @milewski ,

Normal, in your second example, you use an inline interface. In TypeScript interface haven't consistency :). Any metadata are generated in this case and ConverterService cannot deduce the type for your variable.

See you,
Romain

**Comment by milewski** [comment]
i see. yeah understandable.
