### ISSUE TITLE
Upgrade @Value decorator

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#385]
Hi @Romakita,
After deep digging with server settings I found two issues - maybe new features.

1. Can `@Value` decorator get default value of property when settings provider return `undefined`?
2. `@Value` decorator is always called once to set property value, so when config value will change then property have invalid state.

**Comment by kalu111** [comment]
Hi,
Thanks for an answers :)

1. Yes, I agree :)
2. Maybe you have right. I will think about other solution.

**Comment by Romakita** [comment]
Right know, your proposal are implemented. I think for Value, it's for your own configuration. The release is coming soon :)

**Comment by Romakita** [comment]
v4.22.0
