### ISSUE TITLE
[question] Is it possible to pass initialization data to a service?

### ISSUE THREAD

**Issue by Szauka** [Romakita/ts-express-decorators#401]
Hi @Romakita thanks for the great framework.
I'm not sure if I have got this right, so correct me please if I'm wrong. 

I understand that the `@Service()` decorator is a single instance like a singleton. 
If that is right is there any way that I could pass information to the service when is created?

I'll explain what I'm trying to do, my application receives some configuration trough the standard output when starting and I need to pass it to service so it will be available when I use the service. 

Thank you in advance.

**Comment by Romakita** [comment]
Hi @Szauka ,

I'm not sure but ServerSettingsService is here for that.

```typescript
@ServerSettings({
   myConf: {}
})
export Server extends ServerLoader{

}

@Service()
export MyService{

    // By decorator
   @Value("myConf")
   private myConf: any;   // Object
     
   constructor(setttingsService: ServerSetttingsService) {
      // or by serverSettingsService
      settingsService.get("myConf") // object
   } 
  
}

```
See you,
Romain

**Comment by Szauka** [comment]
Hi @Romakita, 

Thanks for the quick reply. 
That is what I was looking for, but I have another question. 

I start the app on the following order:
```
function initLaunchContext(next) {
	let jsonString = '';
	// Read the launch context JSON from stdin. when complete, parse the launch json
	process.stdin.setEncoding('utf8');

	process.stdin.on('readable', function () {
		const chunk = process.stdin.read();
		if (chunk !== null) {
			jsonString += chunk;
		}
	});

	process.stdin.on('end', function () {
		const launchContext = JSON.parse(jsonString);
		next(launchContext);
	});
}

function start(launchContext) {
	new Server(launchContext)
		.start()
		.then(() => {
			$log.info('Server started...');
		})
		.catch((err) => {
			$log.error(err);
		});
}

initLaunchContext(start);
```
Is it possible to set the config on the constructor ??
```
@ServerSettings({

})
export Server extends ServerLoader{
   set myConf: {} here ?
}
```

**Comment by Romakita** [comment]
```typescript
@ServerSettings({...})
export Server extends ServerLoader{
    constructor(launchContext: any) {
         super();

         this.settings.set("myConf", launchContext);
    }
}
```

See you,
Romain

**Comment by Szauka** [comment]
That is perfect, works great. 
Thank you.
