### ISSUE TITLE
@PathParams fetching data in other scope

### ISSUE THREAD

**Issue by iaejean** [Romakita/ts-express-decorators#402]
## Informations
Fetching PathParams from mount property or controller decorator

Type | Version
Bug|4.23.2

****

## Description
* I need a little help, I'll try to explain my case:
* I building an API with i18n module, then:
* I added to my @ServerSettings configuration a mount property with '/api/v1/:locale(en|es)'
* I created a localeMiddleware to fetch this value and then with @PathParams('locale') set the locale to my module
* But in serveral attemps (@Use, @UseBefore, @UseAfter, etc) I just got the locale when this is defined in my method/action, dosnt wotk on my mount property or Controllers decorator

```ts
// Server configuration... 
@ServerSettings({
  componentsScan: [
    /* tslint:disable-next-line:quotemark */
    "S{rootDir}/middlewares/*.ts"
  ],
  mount: {
    /* tslint:disable-next-line:quotemark no-invalid-template-strings */
    '/api/v1/:locale(en|es)': "${rootDir}/**/**Controller.ts",
  },
 ...
})


@Controller('/heartbeat')
@UseBefore(LocaleMiddleware)
export class HeartbeatController {

  @Get('')
  @UseBefore(LocaleMiddleware)
  public async getAction(@Req() request: Express.Request | i18n): Promise<Heartbeat> {
    return {
      message: request.i18n('heartbeat.status'),
      status: 200
    };
  }
}

@Middleware()
export class LocaleMiddleware implements IMiddleware {

  use(@Request() request, @PathParams('locale') locale) {
    request.setLocale(locale);
  }
}
```

**Comment by Romakita** [comment]
Hi @iaejean ,

You have to use `@MergeParams` on your controller or change the ServerSettings options for express.

https://romakita.github.io/ts-express-decorators/#/configuration

```typescript
@ServerSettings({
  componentsScan: [
    /* tslint:disable-next-line:quotemark */
    "S{rootDir}/middlewares/*.ts"
  ],
  mount: {
    /* tslint:disable-next-line:quotemark no-invalid-template-strings */
    '/api/v1/:locale(en|es)': "${rootDir}/**/**Controller.ts",
  },
 routers: {
   mergeParams: true
}
})

```

See you,
Romain :)

**Comment by iaejean** [comment]
Thanks!
