### ISSUE TITLE
[Question] Swagger & Responses.schema

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#403]
## Informations

Type | Version
---|---
Question | 4.25.0

****

## Description
Hello, I try to add a custom schema on my GET function.

For exemple : 

> 
    @Responses(200, {
        schema: {
            "type": "object",
            "title": "test",
            "properties": {
              "birthdate": {
                 "type": "string",
                 "format": "date"
              }
            }
          },
        description: "200 response",
        examples: {
            "application/json": [...]
        }
    })
    @Description("xxxx)
    @Authenticated({ role: [authCode.xxx] })
    @Get("/xxx")

But on my swagger it never show the schema. And the model is the description.

![capture 01](https://user-images.githubusercontent.com/2856778/42164516-8e88c3b6-7e06-11e8-87d1-399ac6ba7367.PNG)

![capture 02](https://user-images.githubusercontent.com/2856778/42164515-8e6767f2-7e06-11e8-9168-6c79443b9f68.PNG)

How can I use the shema from response ? 

And I see a weird code on "OpenApiModelSchemaBuilder.ts" line 39

`schema.properties![propertyKey] = this.createSchema(property);`

Thanks.

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hi @Tlahey 

Line 39 isn't a weird code. Is a schema builder based on a Model.
Maybe this documentation will help you : https://romakita.github.io/ts-express-decorators/#/api/swagger/returns

See you,
Romain

**Comment by Tlahey** [comment]
Thank you :)

**Comment by Tlahey** [comment]
Another question, with `@Returns`, how can I type an array model return ?

For exemple : 

> class AclModel {
    @Property()
    public principal: string;
    
    @PropertyType(String)
    public permissions: Array<string>;
}

> @Returns(200, { 
>         description: "Objet contenant l'ensemble des droits de l'utilisateur", 
>         type: Array<AclModel>
>     })

Thanks

**Comment by Tlahey** [comment]
Hello, thank you very much for your help 😃 but I still have a lot of questions 😛 

1. It's ok for me

2. I have an error, I think it's impossible to add `@Example` `@Default` `@Enum` `@Schema` ... decorator above a function parameter 

For example : 

`	@Put('/:id/')
    @Summary("xxxxxxx")
    @Description("xxxxxxx")
    @Security("xxxxxxxx")
    @Returns(200, { 
        description: "xxxxxx", 
        type: UpdateSuccinctPropertiesModel
    })
    @Returns(500, { description: "xxxxxxxxx"})
    @Returns(400, { description: "xxxxxxxxx"})

    public async updateDocument(
	
		[...]

        @Description("Type de version du document.")
        @Default('major')			// HERE
        @Enum('minor', 'major')		// HERE
        @BodyParams('versioningState') 
        versioningState : 'minor' | 'major' = "major",

        @Description("Commentaire de version du document.")
	@Example("Add electronic signature user user@xx.fr")	// HERO
        @BodyParams('versioningTag') 
        versioningTag : string,

		[...]

   ) : UpdateSuccinctPropertiesModel {
   
		// LOGIC
		
   }`

I've try to add with `@Schema` the enum and default but I have always the same error 

`TypeError: Cannot read property 'merge' of undefined
at Schema.decoratorSchemaFactory_1.decoratorSchemaFactory ([...]\node_modules\@tsed\src\common\jsonschema\decorators\schema.ts:43:11)`

It is possible to add decorator under function or it is necessary to make a class

Thanks 😁

**Comment by Romakita** [comment]
I've right, the `@Example` cannot be used on parameters. To do that, I need to change the Example decorator implementation.
Right know, the solution is to create a class and use it as a Model with BodyParams.

I'll try to improve Example decorator ASAP. For Enum and Default, is another problem :/

See you,
Romain

**Comment by Tlahey** [comment]
Thank you for your help, I will used the class :)

**Comment by dufaux** [comment]
Hello,

Is there a way to provide an Array as type in '@Return' decorator?
If I create a class that extends Array<something>, the swagger example value and model are empty.

**Comment by Tlahey** [comment]
@ReturnsArray 
:)
