### ISSUE TITLE
AcceptMimes must be valid all mimeType

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#407]
## Informations

Type | Version
---|---
Bug | 4.25.0

****

## Description
I this it's a bug,

I try to produce on my rest call an `application/xml`. But all my other call produce `application/json`

```typescript
    @Get("/generate/configuration")
    @Produces("application/xml")
    public func() { }
```

I use `GlobalAcceptMimesMiddleware` and on my server decorator I acceptMimes : 

```typescript
@ServerSettings({
    rootDir: Path.resolve(__dirname),
    acceptMimes: ["application/json", "application/xml"],
    uploadDir: `${rootDir}/uploads`,
    httpsPort: false,
    port: process.env.PORT != "false" ? process.env.PORT : false,
    swagger:
   [...]
```

But when I call the function, I have an error and the call return a 406: 

`"error": {
    "message": "You must accept content-type application/json",
    "stack": "NOT_ACCEPTABLE(406): You must accept content-type application/json\n    at serverSettingsService.acceptMimes.forEach (C:\\develop\\Brazil\\master\\Documents.Manager\\Documents.Manager.Server\\node_modules\\@tsed\\common\\lib\\mvc\\components\\GlobalAcceptMimesMiddleware.js:18:23)`

After search on the `GlobalAcceptMimesMiddleware.js`, if the first acceptMime does not matches with the produces call it throw an error.

Can you tell me if this is normal, or if it is possible that the calls can produce either one or the other.

Thank you.

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
haaa.... ok fix needed :)

**Comment by Tlahey** [comment]
Thanks ! =D
