### ISSUE TITLE
[QUESTION] Typed FormData param structure isn't displayed inside swagger

### ISSUE THREAD

**Issue by Barzou** [Romakita/ts-express-decorators#412]
## Informations

Type | Version
---|---
Question | 4.25.0

****

## Description
Hi !
I would like to generate a swagger documation wi this kind of controller

``` Typescript
public createERL(
	@BodyParams('erl', IERL) p_erl : IERL,
	@MultipartFile("file") @Required() files: Express.Multer.File[],
)
```

My IERL type is describe as a class :
``` Typescript
export class IERL{
    @Property() @Required()
    @Description(`Informations de l'expéditeur.`)
    "sender": ISender;
}
```

So I had this result :

![image](https://user-images.githubusercontent.com/7857690/42645067-6709a78e-85fd-11e8-8440-ae076ac737a9.png)

My IERL structure isn't displayed inside swagger ; because erl param is considered as formData as a simple string.

When I removed the MultipartFile param, I obtains what I would (with a structure of IERL object), because my param is considered as body param :

``` Typescript
public createERL(
	@BodyParams('erl', IERL) p_erl : IERL
)
```
![image](https://user-images.githubusercontent.com/7857690/42645148-96ee1ac0-85fd-11e8-9d7b-71c199596ce3.png)

Is there any way to force IERL to be displayed in swagger doc with it's structure without anything else than IERL class ?

**Comment by Romakita** [comment]
In typescript Interface hasn't consistency, when TypeScript is compiled to JavaScript. So isn't possible to create a schema from an Interface.

I think, this example works:
```typescript
export class IERL{
    @Property() @Required()
    @Description(`Informations de l'expéditeur.`)
    @Schema({type: 'object', properties: {'toto': {type: 'string'}})
    "sender": ISender;
}
```

**Comment by Barzou** [comment]
Hi Romain,

Thank you for your reply! But my problem is not about the interface.
My "interface" IERL is declared as ** class **, not like the interface ^^
And it works perfectly with the body settings (without file).

My problem is that I can not use the power of types when a MultipartFile is declared. Because my BodyParam is considered FormData. In my mind, I should be able to send a file and a body; as I use a body without file.

Finally, I guess it's more about the standard ; not about TSED.

So, I'm going to put my payload structure inside definition field, or something else not really satisfying...

See you

**Comment by Romakita** [comment]
Haa ok. Unfortunately, Swagger doesn't allow body and formData description at the same time.

https://swagger.io/docs/specification/2-0/file-upload/ (See Upload a File + Other Data).

So all data must be declared with the formData type and multipart/form-data. The limitation come from Swagger in version 2.

Sorry :/ because I haven't solution for that.
See you

**Comment by Barzou** [comment]
You're right, I found some similar issues on swagger api : https://github.com/swagger-api/swagger-editor/issues/889. 

Thanks for your response !
