### ISSUE TITLE
How to stream a file in Express.Response with any content type?

### ISSUE THREAD

**Issue by dgkmurthy** [Romakita/ts-express-decorators#413]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
We would like to stream a file in response with dynamic content type, but Express.Response is not stream writable.

Is there any alternative or workaround?

## Acceptance criterias

- [ ] File in response (to be able to send a file in response with dynamic content type)

**Comment by dgkmurthy** [comment]
Handled it through Custom SendResponseMiddleware by streaming the file to response.

**Comment by oehm-smith** [comment]
Hi @dgkmurthy, have you got an example of where you use this?  I can't see it in any of your github projects.
