### ISSUE TITLE
Invalid input in Enums

### ISSUE THREAD

**Issue by azigelman** [Romakita/ts-express-decorators#415]
## Informations

Type | Version
---|---
Question | 4.25

****

## Description
I would like to use an enum in my class

I use this in my code:
```
enum SomeEnum {
	ENUM_1 = 'val1',
	ENUM_2 = 'val2'
 }

export class Model {
	@Enum(SomeEnum)
	property: SomeEnum;
 }

```

I take it as an input through body params.
How do I handle errors for invalid value?
Should I implement custom error handling?

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hi @azigelman,

If you use `@tsed/ajv` plugins, normally, the validation should works as expected. If not, you can open issue or reply on this issue :)

See you,
Romain
