### ISSUE TITLE
[Question]: why the swagger service can get controller method parameter types

### ISSUE THREAD

**Issue by linxiaowu66** [Romakita/ts-express-decorators#419]
## Informations

Type | Version
---|---
Question | 4.20

****

## Description
Hi, 
 I read the swagger service code recently, but I can not find where  the code to read typescript definition.

for example:

```
@Get("/:id")
    async get(@Required() @PathParams("id") id: string): Promise<Calendar> {}
```

How can the swagger service can get the type of parameter `id`?

Thanks a lot

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @linxiaowu66 ,

TypeScript generate metadata when you use a decorator on class/method/parameters. Theses metadata store the type of your parameter (Object, String, Number, Boolean, Date, Class, etc...).
For example, PathParams get the type from metadata stored by TypeScript ;)

In Ts.ED the code responsible to read type is here https://github.com/Romakita/ts-express-decorators/blob/master/src/core/class/EntityDescription.ts#L188
EntityDescription is use by ParamMetadata and other classes.

I hope this answer will help you,
See you
Romain

**Comment by Romakita** [comment]
It's Ts.ED. But for PathParams, I'm not sure if your example work as expected.
It should be like something:
```typescript
@Get("/:id")
    async get(@Required() @PathParams() calendar: Calendar): Promise<Calendar> {

  }
```
But this example should probably failed if Calendar has som required fields.

**Comment by linxiaowu66** [comment]
er...

I means that how the Ts.ED can parse the variable `calendar` to type `Calendar`,  as I can not find any third-party library to do this. But the source code also can not.

**Comment by RevanScript** [comment]
@linxiaowu66 it's possible using decorators and reflect-metadata

**Comment by linxiaowu66** [comment]
@RevanScript 
 
yes, I had read this article, but the author has mentioned that we can not get the complex type. Now I find another tools to doing this.  Thanks a lot.
