### ISSUE TITLE
Dependency injection failing on standalone service

### ISSUE THREAD

**Issue by johncalvinroberts** [Romakita/ts-express-decorators#420]
## Description
I've wrote a few services to function as standalone services, i.e. doing some fetching and scraping, then calling some other repository services to save to DB. Point being: the service is not instantiated by a controller, just trying to instantiate in `Server.ts`.

## The Problem
Cannot inject service into `Server.ts`. Can compile without error, but the instance of the service class comes back as `undefined`.

## Steps to reproduce

1. Create a standalone service object class in `Services` directory

```javascript
// ShopifyScraperService.ts
import { Service } from '@tsed/common'
import { AbstractScraperService } from './AbstractScraperService'

@Service()
export class ShopifyScraperService extends AbstractScraperService {

    public startScraping = (url: string) => {
        console.log('hey, welcome to scraper service')
    }
}
```

2. Inject in `Server.ts` and try to call class method

```javascript
// Server.ts
import { GlobalAcceptMimesMiddleware, InjectorService, ServerLoader, ServerSettings } from '@tsed/common'
import '@tsed/mongoose'
import '@tsed/multipartfiles'
import { ShopifyScraperService } from './services/scraping/ShopifyScraperService'

// config @serversettings here
export class Server extends ServerLoader {
    public $onReady() {
       const shopifyScraperService: ShopifyScraperService = InjectorService.get(ShopifyScraperService)
        console.log(shopifyScraperService) // <--- WILL PRINT UNDEFINED
       shopifyScraperService.startScraping('https://scrapme.com/stuff') // <-- WILL THROW ERROR
  }
}
```

## What I tried
* Tried `@Inject` decorator above `$onReady` hook. Like: 
```javascript
    @Inject()
    $onReady(service: Service) {
          // service.doSomething()
    }

```
* Tried injecting in class constructor of `Server` class, like: 
```javascript
export class Server extends ServerLoader {
 constructor(public shopifyScraperService: ShopifyScraperService){}
```
* Tried injecting with`InjectorService`. See code sample from **steps to reproduce**
* also tried this method invoked inside of a `setTimeout`

Thanks in advance!

**Comment by milewski** [comment]
you can grab the instance of your service like this:

```ts
export class Server extends ServerLoader {
    public $onReady() {
        const shopifyScraperService: ShopifyScraperService = this.injector.get(ShopifyScraperService)
        shopifyScraperService.startScraping('https://scrapme.com/stuff')
    }
}
```

**Comment by johncalvinroberts** [comment]
Solution from @milewski worked completely 

Thanks!
