### ISSUE TITLE
Override parameter type in swagger 

### ISSUE THREAD

**Issue by akkunchoi** [Romakita/ts-express-decorators#421]
## Informations

Type | Version
---|---
Improvement| 4.x

****

## Description

I would like to set a type what I need in swagger API even if the parameter type is different from the swagger API type. My code converted path params from number to object by converters or the middlewares.

for example, source code: 
```
    @PathParams('user') user: User
```

then output in swagger: 
```
  "parameters": {"in":"path","name":"user","type":"object"}
```

what I need: 
```
  "parameters": {"in":"path","name":"user","type":"number"}
```

I guess this issue relates to OpenApiParamsBuilder.

```
        pathParam = Object.assign({}, pathParam, param.store.get("baseParameter") || {}, {
          type: swaggerType(param.type)
        });
```

Thanks in advance.

**Comment by Romakita** [comment]
Hi @akkunchoi ,
To do that:
```
 "parameters": {"in":"path","name":"user","type":"number"}
```
Just write that:
```
@PathParams('user') user: number
```

See you :)

**Comment by akkunchoi** [comment]
Hi @Romakita. Thanks for your reply. But my explanation was missing.

In my case, the middleware loads a user entity from `request.params.user` before controller process because of the purpose to share loading process (by the way, Converter does not seem to support async loading).

So, path params type should be entity class, and API path params type should be number.

Here is part of my code.
```
@Middleware()
export class UserLoaderMiddleware implements IMiddleware {
  constructor(private userRepo: UserRepository) {
  }
  public async use(@Request() request: Express.Request) {
    request.params.user = await this.userRepo.findOneOrFail({id: request.params.user}).catch((err: any) => {
      throw new NotFound(err)
    })
  }
}

export class UserController {  
  @Get("/:user")
  @UseBefore(UserLoaderMiddleware)  
  show(@PathParams('user') user: User) {
  }
}
```

This may be a peculiar method. But I think that this is very smart.

**Comment by akkunchoi** [comment]
I'd like to adopt your idea. Thanks!
