### ISSUE TITLE
Controller dependencies: add dependent Controller dynamically?

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/ts-express-decorators#43]
Hi,

I have a small server framework build on ts-express-decorators containing a generic abstract Controller implementation for the CRUD operations:
```ts
export abstract class ControllerBase<T, TId extends IToString> {

constructor(service: OvertimeService) {
        super(service, 'overtime', 'id');
    }


    @Authenticated()
    @Post('/')
    public create(
        @Request() request: Express.Request
        ): Promise<Overtime> {
        return super.createInternal(<Overtime>(<any>request).body);
    }
...
}
```

 When I want to add some additional function to a concrete controller, what's the best way to do? 
I have one solution based on dependent controller like:
```ts
@Controller('/query')
class QueryController {
    constructor(private service: OvertimeService) {
    }
    @Authenticated()
    @Post('/')
    public query(
        @Request() request: Express.Request
        ): Promise<Overtime[]> {
        let query = <IQuery> (<any>request).body;
        return this.service.query(query);
    }
}

@Controller('/overtime', QueryController)
export class OvertimeController extends ControllerBase<Overtime, number> {
...
```

But then I always have to implement this kind of code statically.

Is there a way to dynamically add a dependent controller with his corresponding route?

Or by adding a new decorator:

Example:
```ts
...
   @Authenticated()
   @Post('/query', OvertimeController)   
    public query(
        @Request() request: Express.Request
        ): Promise<Overtime[]> {
        let query = <IQuery> (<any>request).body;
        return this.service.query(query);
    }
```

Regards,
Walter

**Comment by Romakita** [comment]
Hi walter, 

I'm not sure but you have the RouterController class to retrieve the object Express.Router:
```typescript
@Controller('/query')
class QueryController {
    constructor(private service: OvertimeService, private routerController: RouterController) {
         
         const router = routerController.getRouter(); //   Express.Router
         
    }
    @Authenticated()
    @Post('/')
    public query(
        @Request() request: Express.Request
        ): Promise<Overtime[]> {
        let query = <IQuery> (<any>request).body;
        return this.service.query(query);
    }
}
```
After you can use router as you want. Each controller as here own Express.Router with here own routing configuration. Maybe that can help you ?

**Comment by WalterLeinert** [comment]
Thank you for the immediate feedback.
I will experiment with your hint.

Another question: is the order of controller methods important with regard to the corresponding endpoints?

**Comment by Romakita** [comment]
Order endpoints is the same as the order of yours methods implementation :)

**Comment by WalterLeinert** [comment]
Thank you for the clarification
