### ISSUE TITLE
testing required parameter returns 400 bad request hangs

### ISSUE THREAD

**Issue by dagda1** [Romakita/ts-express-decorators#436]
## Informations

Type | Version
---|---
Question | 4.30.1

****

## Description

I want to write a test that verifies if a call is made with a missing parameter then it returns 400.

I have the following controller:
```
@Controller('/payments')
export class PaymentsController {
  @Post('/')
  @Status(HttpStatusCode.Created)
  async create(
    @Request() req: Express.Request,
    @Required()
    @BodyParams('paymentType')
    paymentType: PaymentType
  ): Promise<CreatePaymentResponse> {
```

And I have the following test:

```
describe('payments', () => {
  let app: any;

  beforeAll(bootstrap(FakeServer));

  beforeEach(inject([ExpressApplication], (expressApplication: ExpressApplication) => {
    app = request(expressApplication);
  }));

  it('should return Bad Request Request for missing payment type', async () => {
    await app
      .post(paymentsUrl)
      .send()
      .expect(HttpStatusCode.BadRequest);
  });
```

I am using jest but it just hangs and displays this error message:

> Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

so for some reason the promise is not resolving gut only in test.  It works in reality.

Is there a better way to test this or why would the promise not be resolved?

**Comment by Romakita** [comment]
@dagda1 Can I close this issue ?
