### ISSUE TITLE
$afterCtrlsInit vs $afterRoutesInit

### ISSUE THREAD

**Issue by uxsoft** [Romakita/ts-express-decorators#44]
server-loader.ts line 92:
        const $afterRoutesInit = (<any>this).$afterCtrlsInit || new Function; // TODO Fallback
i believe should be $afterRoutesInit on both sides, as the interface and documentation references $afterRoutesInit.

**Comment by Romakita** [comment]
Thanks uxsoft. It's fixed with v1.3.5 ;)

**Comment by uxsoft** [comment]
Yeah, I noticed the issue was fixed in the repository after I created the issue so I closed it right away. Sorry :-( I really like this project so far, It reminds me of ASP.NET a bit actually :-)
