### ISSUE TITLE
ConverterService failed to serialize on TypeORM @OneToMany()

### ISSUE THREAD

**Issue by johnjerrico** [Romakita/ts-express-decorators#441]
Failed to serialized the following object at Get request
```
@Entity("sample")
export class Sample  {
    @OneToMany(type => Other, other => other.sample)
    @JoinColumn()
    others:Promise<Array<Other>>;
}
// serialize on get request
@Get("/")
async get() {
    const repo = getRepository(Sample);
    const result = await repo.find({relations:["others"]});
    return result;
}
```
Type | Version
BUG|4.30.1 and before

****

## Description
[https://github.com/Romakita/ts-express-decorators/blob/master/src/common/converters/services/ConverterService.ts](url) failed to serialized the object

## Acceptance criterias
should return 
`
{
  others: [
      Other {id:0}
  ]
}
`
instead of this 
`{}`

**Comment by Romakita** [comment]
Hi @johnjerrico,

You've missed to describe your model with the right decorator for the converter. But in your case, Promise cannot be deserialized correctly because convertersService doens't support promise and will never support that. Isn't his job :)

Try this example:

```typescript
@Entity("sample")
export class Sample  {
    @OneToMany(type => Other, other => other.sample)
    @JoinColumn()
    @PropertyType(Other)
    others: Other[];  // I removed the Promise type show you a model correctly configured
}
// serialize on get request
@Get("/")
async get() {
    const repo = getRepository(Sample);
    const result = await repo.find({relations:["others"]});
    return result;
}
```
You can have more information on Models feature here: http://tsed.io/docs/model.html

See you,
Romain

**Comment by johnjerrico** [comment]
thanks for your fast response, you are right after adding those decorators it works, sorry for the inconvenience

**Comment by Romakita** [comment]
@johnjerrico No problem :D
