### ISSUE TITLE
Swagger controller enhancer

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#447]
## Informations

Type | Version
---|---
Improvement | 4.29.1

****

## Description
On swagger, controller's without routes are displayed. 
It's is possible to delete controllers without routes on .json generation ?

My case : 
- backofficeCtrl (/backoffice)
  - AdministrationCtrl (/backoffice/administration)
  - [...]

`backofficeCtrl` have no routes.

Thanks.

**Comment by Romakita** [comment]
Hi @Tlahey,

You have `@Hidden` decorator to do that :)

See you

**Comment by Tlahey** [comment]
Thanks for the anwser.

With `@Hidden` the controller is hidden on swagger but his children too by the [dependencies](http://tsed.io/docs/controllers.html#dependencies)

Thanks.

**Comment by Romakita** [comment]
ha... ok I see
