### ISSUE TITLE
error TS2344: Type 'string | Function' does not satisfy the constraint 'object'.

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/ts-express-decorators#45]
Hi,

this morning I got this error after rebuilding my project from scratch:

.../server/node_modules/ts-express-decorators/dts/services/injector.d.ts(8,52): error TS2344: Type 'st
ring | Function' does not satisfy the constraint 'object'.
  Type 'string' is not assignable to type 'object'.

I used typescript "^2.1.5". 

After experimenting and doing some analysis I found that the problem seems to be related to ts 2.2.x.
When changing the typescript version to "2.1.5" (without caret) the error has gone.

Any idea?

Regards,
Walter

**Comment by Romakita** [comment]
Hello @WalterLeinert,

Actually, I don't test the 2.2.x version of typescript.
Maybe Typescript has changed the specification and/or the type checking for the decorators.

I can fix that this week ;)

**Comment by WalterLeinert** [comment]
Hi Romain,

I don't know what the reason is, I'm using ts 2.1.5. May be a fresh "npm install" of my projekt brought some ts 2.2.x dependency due to the weak" version specifications which cause the issue.

I experimented with shifting my whole project (3 libs, 1 main project) to ts 2.2.x, but I stopped after getting strange issues.

Regards,
Walter

**Comment by Romakita** [comment]
Hi @WalterLeinert,
TypeScript 2.2 has introduced the object type. With WeakMap<k, t> the "k" type has changed to object. 
According to https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/
string type isn't assignable to object.

I've changed WeakMap by Map to fix that.

v1.3.5 is released :)

**Comment by WalterLeinert** [comment]
Hi Romain,

thanks for fixing; I will revert my workaround and test again.
