### ISSUE TITLE
[BUG] Published packed modules include original .ts files

### ISSUE THREAD

**Issue by dario1985** [Romakita/ts-express-decorators#451]
## Informations

Type | Version
Bug   | 4.31.4

****

## Description

Due to the `tsc` module resolutions rules (https://www.typescriptlang.org/docs/handbook/module-resolution.html), having in the same dir `ts`, `ts.d`, `js` files, the first attempt will be on the `ts`.

Doing that, every time we try to compile a project including some `@tsed/*` deps, we'll also compile all inner `@tsed/*` files (https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler) ... and this is NOT normally needed: the side effects is that it may break compilation using different `tsconfig.json` settings.

A easy solution to that is specify an `outDir` in the `tsconfig.json`.

**Comment by Romakita** [comment]
Hello Dario,

Yes work on this part, but it's a bit different when you build multiple packages on the same repository.
Due to some problems with my previous build pipeline, I've changed a lot of things. But I know the produced npm packages aren't perfect . 

I'll work on ASAP.

**Comment by dario1985** [comment]
Maybe can be "fixed" by `.npmignore`?

**Comment by dario1985** [comment]
Oh thanks you @Romakita. I will confirm you tomorrow. :+1:  But definitely looks better:
```
...
package/lib/server/interfaces/IServerLifeCycle.js.map
package/lib/server/interfaces/OnRoutesInit.d.ts
package/lib/server/interfaces/OnRoutesInit.js
package/lib/server/interfaces/OnRoutesInit.js.map
package/lib/server/interfaces/OnServerReady.d.ts
package/lib/server/interfaces/OnServerReady.js
package/lib/server/interfaces/OnServerReady.js.map
package/src/config/constants/index.ts
package/src/config/decorators/constant.ts
package/src/config/decorators/value.ts
package/src/config/index.ts
package/src/config/interfaces/IServerSettings.ts
package/src/config/services/ServerSettingsService.ts
package/src/converters/components/ArrayConverter.ts
package/src/converters/components/DateConverter.ts
package/src/converters/components/MapConverter.ts
package/src/converters/components/PrimitiveConverter.ts
...
```

`package/src/*` could be added in the `.npmignore` to be omitted by npm publish? there is any reason to publish it?

**Comment by Romakita** [comment]
It's required if you want to debug an error which come from the Ts.ED library ;). The sourcemapping work only if the original source code is available. Otherwise, the stack error display the javascript source line.

See you,
Romain

**Comment by dario1985** [comment]
Problem fixed. Thanks you
