### ISSUE TITLE
Type annotation cannot appear on a constructor declaration.

### ISSUE THREAD

**Issue by duongvanba** [Romakita/ts-express-decorators#453]
I saw this error when I test code from homepage
Can you fix it for me 

Type annotation cannot appear on a constructor declaration.
```typescript
constructor(@Inject(MyModel) private model: MongooseModel<MyModel>): MyModel {
        console.log(model) // Mongoose.model class
    }
```

Cannot use 'new' with an expression whose type lacks a call or construct signature.
```typescript
 async save(obj: MyModel): MongooseModel<MyModel> {
        
        const doc = new this.model(obj);
        await doc.save();
        
        return doc;
    }
    
```

https://tsed.io/tutorials/mongoose.html#inject-model

**Comment by Romakita** [comment]
It should works for me...
Here the complete working example here : https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-mongoose

Can you sent me your model class declaration ?

**Comment by duongvanba** [comment]
My files

```typescirpt
// MyModel.ts

import {Model, Ref} from "@tsed/mongoose";
@Model()
export class MyModel {
    _id: string;
    calendarId: string;
}
```

```typescript
// ./test.ts
import {Service, Inject} from "@tsed/common";
import {MongooseModel} from "@tsed/mongoose";
import {MyModel} from "./MyModel";

@Service()
export class MyService {
    
    constructor( @Inject(MyModel) private myModel: MongooseModel<MyModel>) {
        
    }

    public af(){
        this.myModel.create()
    }
    
    
}

```

I saw error: Property 'create' does not exist on type 'MongooseModel<MyModel>'.

**Comment by duongvanba** [comment]
I found solution
 yarn add @types/mongoose
Thanks admin
