### ISSUE TITLE
can I deploy my code using webpack

### ISSUE THREAD

**Issue by dagda1** [Romakita/ts-express-decorators#455]
## Informations

Type | Version
---|---
Question | 4.30.1

****

## Description
I have a number of reasons why webpack is my preferred medium for deploying my node code.

At the moment, I define my server config like this:
```
@ServerSettings({
  rootDir: path.resolve(__dirname),
  acceptMimes: ['application/json'],
  port: process.env.PORT,
  mount: {
    '/v1': '${rootDir}/controllers/**/*.ts'
  },
  exclude: ['**/*.test.ts'],
  debug: true,
  componentsScan: ['${rootDir}/services/**/**.*s', '${rootDir}/middleware/**/**.*s']
})
```
I prefer to deploy my code to cloud foundry using webpack first to bundle the js because it will fix my relative path issues and any monorepo yarn workspace references, for example, I have the following code structure:

```
|_ common
|_ api
|_ frontend
```

Both frontend and api share code in common, I have references like this:

`import { PaymentType, PaymentPlan } from '../../../common/types/paymentType';`

If I use webpack, it will replace these relative references to point to the minified js file.  

I also have mono repo references like:

```
import { HttpStatusCode } from '@myspace/util';
```

I can use webpack [node externals](https://www.npmjs.com/package/webpack-node-externals) to reslove these references.

I cannot do any of the above because of the way components are scanned and I have had to copy my monorepo code into the api code and I have to deploy:

```
|_ common
|_ api
```

For the relative path references to work.

I love the project but this is a show stopper for me.

Is there a way round this?

**Comment by Romakita** [comment]
Hello @dagda1 ,

This subject is already discussed on two different issue here: #270 #224 
For me, use bundler like webpack to deploy back-end code doesn't make sense. But, if you want to do that, you can change the configuration on ServerSettings.

By default the componentScan is configured to scan controllers/services/middlewares directory relatively to your Server.ts.
https://github.com/Romakita/ts-express-decorators/blob/master/packages/common/src/config/services/ServerSettingsService.ts#L44

You can define a configuration on production to scan or import symbols from a different paths:

```typescript
const env = process.env.NODE_ENV;
@ServerSettings({
   mount: { 
     "/rest": env === 'production' ? "path/prod/**.ts" : "path/dev/**.ts"
  },
  componentScan: env === 'production'  ? [
     "${rootDir}/mvc/**/*.ts", 
     "${rootDir}/services/**/*.ts", 
     "${rootDir}/converters/**/*.ts"
  ] : [....]
})
```
Just adapt this example to your context ;)
See you,
Romain

**Comment by dagda1** [comment]
@Romakita  The problem is that in production there won't be any paths because there won't be any directories.

I think the monorepo reason is a common enough reason as I don't want to deploy absolutely everything.

Webpack will also flatten my relative paths meaning I don't have to deploy everything which I currently do.

Would there be anyway to do this?  Can I set the componentScan to look at 1 file or must it be directories?

**Comment by Romakita** [comment]
It's a glob pattern, you can write only one path as long as the file exports the symbols correctly. The ones on which I have a doubt because Webpack changes the way its exported classes and symbols.

**Comment by dagda1** [comment]
@Romakita how can I find out more about the symbol resolution?  I'd be keen to come up with a solution if I fully understood what was wrong

**Comment by Romakita** [comment]
The solution is to not use componentScan to import your Class. 

ComponentScan import classes with ES6 import dynamically. Service decorator add the classes to registry, so it's equivalent to import your classes with ES6 import in Server.ts.

But for the mount options is a bit different because mount need to have the classes exported and accessible. Webpack bundles symbols, I don't know exactly how (I thinks it's based closure function).

The solution is to import manually you classes in the Server.ts

Example:
```typescript
import {Ctrl} from "./path/to/myController";
import "./path/to/myService.ts";

@ServerSettings({
   mount: { 
     "/rest": [
        Ctrl
     ]
  }
})
```
In this case, webpack will resolve correctly your classes.

See you,
Romain

**Comment by dagda1** [comment]
brilliant, this works.
