### ISSUE TITLE
Swagger - Controller method parameter with array type

### ISSUE THREAD

**Issue by YehonatanVonage** [Romakita/ts-express-decorators#457]
## Informations
Question about swagger on tsed
@tsed/swagger: 4.30.1

****

## Description
My controller contains get method, which include param of type string[] (string array).
The param is decorated with @BodyParams().
When I check the swagger I get the next code example:
{
  "myParam": [
    {}
  ]
}

How can I change the swagger documentation to be:
{
  "myParam": []
}

**Comment by Tlahey** [comment]
Hi @Romakita 

I have used an Array Param on `@QueryParams` but on my controller, string doesn't split on "," see : 

![image](https://user-images.githubusercontent.com/2856778/46003299-7a187380-c0b0-11e8-80ff-14017254b313.png)

`http://localhost:8001/[...]/update/toto?modules=generic-case,toto`

Module's doesn't split on the comma.

But works with 

`http://localhost:8001/[...]/update/toto?modules=generic-case&modules=toto`

In the [swagger specs](https://swagger.io/docs/specification/describing-parameters/) we can specify a [serialization method](https://swagger.io/docs/specification/serialization/) (see Parameter Serialization) to `explode` to separate with many items.

Thanks.
