### ISSUE TITLE
Decorator lists in documentation are broken

### ISSUE THREAD

**Issue by SargoDarya** [Romakita/ts-express-decorators#461]
## Informations

Type | Version
---|---
Bug | Latest

Chrome 69 on Mac OS
Firefox 61 on Mac OS

****

## Description

Currently, all decorators on the documentation pages are missing the decorator listing. Same goes for the API docs, they don't seem to show up at all. See attached screenshots for example.

Console in verbose mode shows no errors.

<img width="1269" alt="screen shot 2018-09-20 at 10 46 14" src="https://user-images.githubusercontent.com/404206/45807029-c5064580-bcc2-11e8-920a-123be90e52fc.png">
<img width="1253" alt="screen shot 2018-09-20 at 10 48 31" src="https://user-images.githubusercontent.com/404206/45807031-c5064580-bcc2-11e8-81e2-104e36c7d7a1.png">

## Acceptance criterias

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Strange.... Ok I'll fix that ;) thanks for your reply.
