### ISSUE TITLE
Mongoose Timeout on $onInit hook

### ISSUE THREAD

**Issue by myrddraall** [Romakita/ts-express-decorators#468]
## Informations

Type | Version
---|---
Question | 4.32

****

## Description
A few sentences describing the overall goals of the issue.

After following the instructions at

[http://tsed.io/tutorials/mongoose.html#installation
](http://tsed.io/tutorials/mongoose.html#installation
)

the server issues the following warning:

`[WARN ] [TSED] - Timeout on $onInit hook. Promise are unfulfilled on serviceMongooseService In production, the warning will down the server!`
~and the endpoints of controllers that inject the MongooseService or MongooseModel return a 404~

**Comment by Romakita** [comment]
Hello @myrddraall,

It means your mongo db server isn’t accessible (I think). Check your config according to your mongo db config.

See you

**Comment by Romakita** [comment]
You have a working example here https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-mongoose

**Comment by myrddraall** [comment]
My mongo is accessible, i'm able to read/write records to it. i'll try the example and see if that changes it
