### ISSUE TITLE
Is there a way to integrate socket.io?

### ISSUE THREAD

**Issue by jlberrocal** [Romakita/ts-express-decorators#47]
Actually i'm working with a project that require socket.io. I did it long time ago using js but i want to update it and your decorators looks awesome, so there is a way to create some kind of integration? 

Thanks in advance

**Comment by Romakita** [comment]
Hello @jlberrocal,

You have an example here #7 to integrate Socket.io with TsExpressDecorators. I'll write a new page in the wiki about Socket.io integration ASAP ;)

See you

**Comment by Romakita** [comment]
Hi @jlberrocal,

Here a new example to integrate Socket.io in TsExpressDecorators :)

https://github.com/Romakita/ts-express-decorators/wiki/How-to-integrate-Socket.io

Have a good day :)

**Comment by jlberrocal** [comment]
Awesome thanks a lot
