### ISSUE TITLE
Bootstraping problems when working with Jest/ts-jest

### ISSUE THREAD

**Issue by levkaganv** [Romakita/ts-express-decorators#477]
## Informations

Type | Version
---|---
Bug| 4.x
****

## Description
Hello,

When I bootstrap the server while using jest\ts-jest I've noticed that none of my controllers are mounted. 

I debugged into the loader and I saw that [next code](https://github.com/Romakita/ts-express-decorators/blob/05a67f3f90bbdb2d33edc4fd821101f5a5e738b6/packages/common/src/server/components/ServerLoader.ts#L610) checks for 'require.extensions[".ts"]'. But because ts-jest uses other way to compile typescript files into javascript this entry does not exit. The result of it is that pattern is changed from '...*.ts' into '...*.js'. But because those files do not exist nothing is mounted. 

When I changed (in debug) the patterns back to '...*.ts' everything worked fine.

```
  static cleanGlobPatterns(files: string | string[], excludes: string[]): string[] {
    excludes = excludes.map((s: string) => "!" + s.replace(/!/gi, ""));

    return []
      .concat(files as any)
      .map((file: string) => {
        if (!require.extensions[".ts"]) {
          file = file.replace(/\.ts$/i, ".js");
        }

        return Path.resolve(file);
      })
      .concat(excludes as any);

```

The only way it did work for me is only when I run it on compiled files.
 
Thank you!

**Comment by Romakita** [comment]
Hi @levkaganv,
What is the solution ? 
We use require.extensions to know if the environment support the TypeScript files. I can change this code because it fix issue for the developpers which use ts-node. 
I don't know how ts-jest works.

If you any idea, tell me ;)
