### ISSUE TITLE
Way to get all routes in a node micro-service

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#48]
Hello,

I'm working on a project with many micro-services. 
All controllers have routes.
But in my case, i would like get all controller's routes in on of my micro-service (for the scalability).

For exemple : 
  - MyServCtrl1
    - /myServ1/put
  - MyServCtrl2
    - /myServ2/post
    - /myServ2/get
If I start a server with MyServCtrl1 (scan folder MyServ1). I would like to get all routes from both controllers when I'm using routeService getRoutes()

So i decided to launch 1 server with all controllers, saves all routes, stop it and create the micro-service. But, the second server, keep the first server routes ! (In the Properties Metadata map).

Do you have a mean to retrieve all routes in this micro-service ?

Thanks in advance

**Comment by Romakita** [comment]
Hi @Tlahey,

I don't understand exactly why you need to create two server to build your routes one time again.
You can mount all micro-service on the final server rather than launch a server then stop it and retrieve the built routes. The final result is the same.

Maybe I need an example to understand your need.

See you.

**Comment by Tlahey** [comment]
Ok so, i've got a system where I use multiple micro services hosted on different Docker containers. Each of these microservices should be aware of all the routes there is. So we are trying to find a way to instatiate all the routes once to use as a list for our initialisation. But once we have this list we want each of our services to only be aware of the routes hosted on this container.

A quick example
I've got 3 controllers that instantiate 3 endpoints : /a /b /c
We've got one container per controller but we want each container to be aware of all the routes.
We actually need to have the routes in each container but each separate endpoint should only be accessible in its own container

Thanks in advance,

**Comment by Romakita** [comment]
So you need to have three express server instance (that instantiate his own controllers), one per container, and one express server that list all services generated by each instances. The fourth server will be a proxy, I think.

Actually,  TsExpressDecorators, manage one express server by node process.  So you must to start micro service  in a separately node process (container).

The fourth server can get all routes via an http request on `/rest`endpoint for each server started.

I'm not if I answered to your question, and if my solution is the right solution ^^. 

See you

**Comment by Tlahey** [comment]
While your solution is correct, it can cause problems. I can see two mains sources of problems with this implementation :

- If one of my micro Service dies, the lister server will not be able to get its endpoints, resulting in a truncated list of endpoints
- If the lister server dies, all my micro-Services are incapacitated 
We discussed it internally and we are going to develop a external parsing solution to get routes and controller methods directly from .ts controller files.

Thank you for your time and keep up the good work

**Comment by Romakita** [comment]
Thanks @Tlahey ^^

You can use node forever to prevent this problem :) Node application will be restarted automaticaly ;)
