### ISSUE TITLE
Mongoose virtual references

### ISSUE THREAD

**Issue by alex-dev** [Romakita/ts-express-decorators#482]
## Informations
Improvement for @tsed/mongoose

## Description
Is there any interest to support mongoose virtuals for referencing collection in classes by decorators? If there is I am willing to work on it.

## Plan
- Two decorator: VirtualObject and VirtualCollection which sets metadata;
- Some changes to buildMongooseSchema.;
- Tests;

**Comment by Romakita** [comment]
Hello @alex-dev 
I don't what this feature doing. But If it's not complicated to implement you can sent a PR ;)

See you
Romain

**Comment by Romakita** [comment]
Ok why not :D

**Comment by alex-dev** [comment]
Another issue... A subdocument doesn't have a load class applied to it.
I hesitate.

Would it be better to explicitly force the consumer to apply a decorator to his subdocument schemes? This would allow the mongoose schema to become:
```
var Reply = new mongoose.Schema({
   body: String,
   created_at: {
     type: Date,
     default: Date.now
   }
});

var Comment = new mongoose.Schema({
   body: String,
   replies: {
      type: [Reply]
   }
});
```

**Comment by Romakita** [comment]
For point 2, we would have to upgrade mongoose to 5.1.0. Do I go ahead or not?
Not necessary. 5.1.0 hasn't change on the mongoose package :)

Would it be better to explicitly force the consumer to apply a decorator to his subdocument schemes? This would allow the mongoose schema to become:
Yes it should be better :)

**Comment by alex-dev** [comment]
Schema and model build process is completed... Tests are passing.
Only thing left is to create the actual decorators. For a decorator for Schema, should I repurpose the current one to this and rename it SchemaTypeOptions, or SchemaType? Or do you have a better name in mind? Document could do, but it wouldn't be exactly the proper term used by mongoose.

**Comment by Romakita** [comment]
For Map support, I'll write it, assuming Mongoose is 5.1.0... Ok, my mistake, I thought you talking about `@tsed/mongoose`. Yes you can suppose the mongoose version is up to date we don't provide support for all versions. A message on the documentation can be added to inform the consumer about the minimal version supported by the feature ;)

Unfortunatly rename Schema will introduce a breaking change why do you need rename Schema ? 

Great job ;)

**Comment by alex-dev** [comment]
Mostly because Schema represent better declaring a class that is not a model but is a schema available to models. Unless it is possible to use the same name to convey very different meanings.
I could reuse the same name, but I fear it would complicate the API more than help it. And javascript has no overloads... So it would be done in the same function... Which is weird at best.

**Comment by alex-dev** [comment]
Thank you.

**Comment by alex-dev** [comment]
There is a small bug in code you gave me... I should call the function in property in place.
