### ISSUE TITLE
Support for `router.all`

### ISSUE THREAD

**Issue by m0uneer** [Romakita/ts-express-decorators#50]
Hello everyone,
Thanks again for this lib :)
I'm looking for a support for route-range-based authentication, something like this
```javascript=
app.all('admin/*', authenticate)
```
But I can't find a direct way with current router. So, is there a support for [router.all](http://expressjs.com/en/4x/api.html#router.all) or [app.all](http://expressjs.com/en/api.html#app.all)?
I tried injecting both ExpressApplication and RouterController into `$onMountingMiddlewares` but in vain. All other hooks doesn't suit and I think a `beforeControllerRoutesInit` hook would be ideal for this use case.

Thanks.

**Comment by Romakita** [comment]
I @m0uneer :),

You can $onMountingMiddlewares to handle all routes like this:

```typescript@ServerSettings({
    rootDir: Path.resolve(__dirname)
})
export class Server extends ServerLoader {

    /**
     * This method let you configure the middleware required by your application to works.
     * @returns {Server}
     */
    public $onMountingMiddlewares(): void|Promise<any> {
         this.use('admin/*', authenticate); //proxy method to ExpressApp.use()
    }
}
```
I think that will be work fine :). In addition, you can see the new Middleware feature introduce in v1.4 to use decorator and a class to manage your all routes. See https://github.com/Romakita/ts-express-decorators/wiki/Middlewares

`$onMountingMiddlewares` is called before all routes are built. 

If it doesn't work, isn't normal XD.

See you !

**Comment by m0uneer** [comment]
Unfortunately not working
```
public $onMountingMiddlewares(): void|Promise<any> {
  this.use('admin/*', function authenticate() {
    console.log('admin');
    ...
  });
}
```
Navigating to both `/{endpointUrl}/admin/bar` and `/admin/foo` results in `404` and not passing by `authenticate`

**Comment by Romakita** [comment]
Ok, Sorry, bad example.

I'd just try that and it work for /admin and /admin/foo
```typescript
public $onMountingMiddlewares(): void|Promise<any> {
  this.use('/admin', function authenticate() {
    console.log('admin');
    ...
  });
}
```

`admin/*` doesn't works fine with Express also if it a regex `/admin\/*/` (I think). `/admin` handle all routes for admin path. 

See you :)

**Comment by m0uneer** [comment]
Works like a charm! Thanks @Romakita :)
