### ISSUE TITLE
InjectorService invoke method doesn't call $onInit

### ISSUE THREAD

**Issue by avivVonage** [Romakita/ts-express-decorators#504]
If I write a test like this:
```
test('testName', inject([MyService, Done], async(myService: MyService, done: Done) => {
  ...
}
```
The `$onInit` method of MyService is called.

But if I want to mock the services that MyService uses I want to write it like this:
```
test('testName', inject([InjectorService, Done], async(injectorService: InjectorService, done: Done) => {
  ...
  const locals = new Map();
  locals.set(OtherService, myMock);
  const myService = injectorService.invoke<MyService>(MyService, locals);
  ...
}
```
Unfortunately, now the `$onInit` method of MyService is **not** called.

I can call this method by myself, but why isn't it done inside the invoke method?

**Comment by Romakita** [comment]
Hello @avivVonage 
Yes isn't normal. I already works on the fix. After the new release,  your unit test should be written like that:
```typescript
before(TestContext.create)
after(TestContext.reset)
test('testName', async () => {
  const myService = await TestContext.invoke<MyService>(MyService, [
      provide: OtherService, use: myMock
  ]);
  ...
}
```
> async / await is only required if the $onInit method return a promise. Otherwise, isn't required.

I'll tell you when the fix is released
See you,
Romain

**Comment by Romakita** [comment]
Release in progress
