### ISSUE TITLE
Idea for new decorators

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#51]
Hi,

In express, we are able to send data from one middleware to anoher via the response.locals attribute. Would it be possible to have a decorator (something like the QueryParams one) that allows us to get this data without changing its type ? 

Example : 
In my middleware :
    response.locals["myLocalAttribute"] = "test";
In my controller 
  @Locals("myLocalAttribute") attr : any

Thanks in advance

**Comment by Romakita** [comment]
Hello @Tlahey ,

Yes, I can plan this decorators for the next version :)

**Comment by Romakita** [comment]
v1.4.2 is available with the @Locals decorators :)

**Comment by Tlahey** [comment]
Thanks a lot ! :)

**Comment by Tlahey** [comment]
I'm currently using the decorator, but i think he is on the request parameter.
`file "middleware.ts" line 295`

In express api, the local param are bind on the response parameter. 

Source : 
> http://expressjs.com/fr/api.html#res.locals

**Comment by Romakita** [comment]
Hello @Tlahey ,

Yes, I've copy the bad decorators to do that. So v1.4.4 fix that and I remove the converter option in this case to store an object with references.

You can do that:
```typescript

@Get('/')
myMethod(@Locals() obj: any);  // return the locals objects by reference
myMethod(@Locals("exp") value: any);  // return the parsed expression (by reference if it's an object)
myMethod(@Locals("exp") value: MyModel); doesn't work's 
```

Sorry for this mistake :)

**Comment by Tlahey** [comment]
Hello @Romakita 

No problem for the mistake ;)
I've try the v1.4.4 and all it's ok ! :) 

Thanks for all

**Comment by Romakita** [comment]
Ok it's work if you already added manually a class in the locals attribute ;). In this case, the converter mechanism isn't used to convert POJ to a class instance like BodyParams.
