### ISSUE TITLE
isAuthenticated is not a function

### ISSUE THREAD

**Issue by cedvdb** [Romakita/ts-express-decorators#53]
Am I meant to implement the isAuthenticated() method that's in the doc myself? The doc isn't clear on that point.

EG:

```
class Server extends ServerLoader {
    public $onAuth(request, response, next): void {
        next(request.isAuthenticated());
    }
}
```
 > [ERROR] TypeError: request.isAuthenticated is not a function

I used jwt 

```
import jwt = require('express-jwt');

export let jwtCheck = jwt({
  secret: 'y',
  audience: 'x'
});
//....
this.use(jwtCheck); // this = server
```

**Comment by Romakita** [comment]
Hi @cedvdb ,

You need to use a library like Passport.js to use the request.isAuthenticated(). isAuthenticated is added by passport.js.

I'll update the doc to explain that clearly :)

Romain

**Comment by cedvdb** [comment]
@Romakita thank you very much

**Comment by Romakita** [comment]
Here the doc:

By default, the decorator respond true for each incoming request. To change this, you must implement your Authentification strategy by adding your method $onAuth on your Server (with Passport.js for example):

class Server extends ServerLoader {
    public $onAuth(request, response, next): void {
        /// request.isAuthenticated() is provided by passport.js by you can implements other library
        next(request.isAuthenticated()); // boolean
    }
}
```
You can found some examples here https://github.com/Romakita/example-ts-express-decorator/tree/master/
