### ISSUE TITLE
POST requests return 201

### ISSUE THREAD

**Issue by m0uneer** [Romakita/ts-express-decorators#57]
Hello everyone,
@ `ts-express-decorators/src/controllers/endpoint.ts` I saw this
```
        if (request.method === "POST") { // TODO remove that in future version
            response.status(201);
        }
```

Could you please explain for me the reason for setting status here? Thank you.

**Comment by vincent178** [comment]
My guess is for the rest api, usually post means create a resource, so the response status code should be 201.

But agree, for the rest post api, it should not be 201.

**Comment by Romakita** [comment]
I had forgotten this line. As has explain vincent178, the POST usually in RestFull API return the status 201 but, in fact, all API aren't RestFull and use the POST for other action (because old firewall doesn't support the PUT verb).

I had planned to delete it XD

Removed in v1.4.6 :)

**Comment by m0uneer** [comment]
Thanks guys, this seems logic for me. And yes I agree about its removal to not be opinionated.
