### ISSUE TITLE
[Decorator] @Scope on Service

### ISSUE THREAD

**Issue by RevanScript** [Romakita/ts-express-decorators#58]
Hi,

Did you think about the implementation of something like Spring bean's scope (https://www.tutorialspoint.com/spring/spring_bean_scopes.htm) for services? Like the following:

```typescript
@Service
@Scope('request')
export class BlaBlaService { ...
```

For example: default scope is a singleton which is a single instance per IoC container. But it's also possible to choose **request** scope where instance exists only in the context of current HTTP request.

It would be useful to store user profile data which was obtained in the middleware for example. Of course, data from middleware can be stored within express context as a param, but it's not very comfortable to provide type safety and it isn't object oriented way :)

**Comment by vincent178** [comment]
it's actually a really good topic to discuss. I like this idea.

**Comment by Romakita** [comment]
Hi @RevanScript ,

Good proposal RevanScript ;). I think it's possible, but it's big improvement and I need some examples with usecase to do that. 

My question, where is injected the Service  when you use the Scope("request") decorator ?

```typescript
@Service
@Scope('request')
export class BlaBlaService {

}

export class BlablaCtrl {
       constructor(private blablaService: BlablaService) { // here ?
       }
       @Get('/') 
       getMethod(blablaService: BlablaService) { // or here ?
       
       }
}
```

See you,
Romain

**Comment by RevanScript** [comment]
Here's an example how i'd like to use it:

```typescript
/*
** Service which contains user details
** UserDetailsService instance should be created on request and destroyed after (in the last middleware)
*/

@Service
@Scope('request')
export default class UserDetailsService {
    private _profile: IProfile;
    
    get profile() {
        return this._profile;    
    }
    
    set profile(profile: IProfile) {
        this._profile = profile;
    }
}

/*
** Middleware which checks auth and gets user profile
*/

@Middleware()
export default class TokenMiddleware implements IMiddleware {
    
    // Inject service into middleware
    constructor(public userDetailsService: UserDetailsService) {
        
    }

    use(@Request() request: Express.Request,
        @EndpointInfo() endpoint: Endpoint,
        @Response() response: Express.Response,
        @Next() next: Express.NextFunction) {
        
        ...
        this.userDetailsService.profile = user;
        ...
    }

}

/*
** Controller
*/

@Controller()
export class SomeController {

    // Inject service into controller
    constructor(public userDetailsService: UserDetailsService) {
        super();
    }
    
    @Get('/profile')
    @TokenRequired('profile')
    profile() {
        return this.userDetailsService.profile;
    }
    
}
```

But i see that there's a problem with injecting such services into the class constructor, because constructor is called once and doesn't create instance each request. It looks like a problem :)

Not sure, but maybe this problem can be solved with Proxy. Scoped service can't be injected on mounting, but it can be injected on fly.

Here's what i mean:

1. Route can use controller instance wrapped with Proxy
2. Proxy will handle access to injected scoped properties. If property is scoped, new instance can be created within express request context

**Comment by Romakita** [comment]
@RevanScript thanks for your example :)

I can planed this enhancement for the v1.5 or v1.6 maybe.

**Comment by RevanScript** [comment]
@Romakita ok, it's great. will look forward to it :)

**Comment by Romakita** [comment]
Hi @RevanScript ,

Just to say you. @Scope exists in ts-express-decorators, to change the controller behavior.
When a controller is annotated by @Scope, the controller will be instantiate for each request.

Maybe that can help you ;)

**Comment by nicojs** [comment]
> Proxy will handle access to injected scoped properties. If property is scoped, new instance of service can be created within express request context

I understand that that is possible, but it can lead to some strange behaviors. For example:

```typescript
@Middleware()
export default class TokenMiddleware implements IMiddleware {
    private currentProfile: IProfile;
    // Inject service into middleware
    constructor(public userDetailsService: UserDetailsService) { }

    use(@Request() request: Express.Request,
        @EndpointInfo() endpoint: Endpoint,
        @Response() response: Express.Response,
        @Next() next: Express.NextFunction) {
        
        ...
        this.userDetailsService.profile = user;
        this.currentProfile = user; // seems pretty harmless but this has a totally different effect
        ...
    }
}
```

These kind of things are also done in the Java world (with CDI) and it can be a real head-scratcher at times.

Maybe it would be more clear if request scoped dependencies can only be used in other request scoped services/middlewares/controllers. For example:

```typescript
@Middleware()
@Scope('request') // leaving out this line could give a clear error message: "Service of type `UserDetailsService` can not be injected as it is request scoped, while `TokenMiddleware` is singleton scoped"
export default class TokenMiddleware implements IMiddleware {
    // Inject service into middleware
    constructor(public userDetailsService: UserDetailsService) { }

    use(@Request() request: Express.Request,
        @EndpointInfo() endpoint: Endpoint,
        @Response() response: Express.Response,
        @Next() next: Express.NextFunction) {
        
        ...
        this.userDetailsService.profile = user;
        ...
    }
}
```

Just a suggestion, I've got no clue how difficult it would be to implement.

**Comment by Romakita** [comment]
Hi @nicojs,

Totally agree :)

**Comment by Romakita** [comment]
https://github.com/Romakita/ts-express-decorators/pull/181
