### ISSUE TITLE
how to access request headers...

### ISSUE THREAD

**Issue by oshri551** [Romakita/ts-express-decorators#60]
Hi, probably stupid question...

Where can i access request headers within the controllers ? 

I'm new to decorators...so i'm trying to find out how to debug the function behind the decorator and access basic functionality within the express server...

**Comment by vincent178** [comment]
You have multiple ways to get the request headers.

One is the normal express way, use `@Request` decorator to get the express request instance, and then use request.headers.
https://github.com/Romakita/ts-express-decorators/wiki/Controllers#response-and-request

The other one is that use `@Header` to directly get the header.
https://github.com/Romakita/ts-express-decorators/wiki/Controllers#header

Hope this is helpful.
