### ISSUE TITLE
decorator BodyParamsRequired not exists

### ISSUE THREAD

**Issue by Roman-Yefimchuk** [Romakita/ts-express-decorators#61]
Hi, I cannot find decorator BodyParamsRequired, but in your controller example it exists. Does it deprecated?

**Comment by vincent178** [comment]
You're right, this decorator is deprecated now.

You're very welcome to send a PR to fix it.

Thanks.

**Comment by Romakita** [comment]
@Roman-Yefimchuk ,

You can use `@Required() @BodyParams() param` instead of :)

See you

**Comment by Roman-Yefimchuk** [comment]
thanks
