### ISSUE TITLE
question: global middleware for custom serialization

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/ts-express-decorators#62]
Hi,

I would like create some hook to perform custom serialization for incoming request data and outgoing response data like it's implemented in SendResponseMiddleware.

I experimented a little bit with global middleware, but with no success; I found no way to manipulate the data. Do you have some hint for me?

Regards,
Walter

**Comment by Romakita** [comment]
Hi @WalterLeinert ,

You can create your own decorator or use the UseAfter decorator to add your own middleware on a method.

SendResponseMiddleware is the last middleware called for one method. After that, it's the global middleware witch handle the current request.  The ReponseViewMiddleware is the right example to change the behavior outgoing response data. Try this : https://github.com/Romakita/ts-express-decorators/wiki/Middlewares#how-to-format-the-response-with-middleware.

See you :)
Romain

**Comment by WalterLeinert** [comment]
Hi Romain,

thank you for the answer and your hints. 
As in SendResponseMiddleware I need global handling of requests/responses to serialize my data in one place. I dont want to decorate each corrresponding controller method.

Any idea?

Regards, 
Walter

**Comment by Romakita** [comment]
Maybe you can use Converter to create a serializer for a Model (class). But I don't think if that answer to your need. See https://github.com/Romakita/ts-express-decorators/wiki/Converters

Other solution is to override the SendReponseMiddleware.use() method with the `MiddlewareService.get(SendResponseMiddleware)` //=>instance of middleware.

I haven't a mechanism to do that easily actually (except with the Converter).

See you,
Romain

**Comment by Romakita** [comment]
Hum maybe that will be works:

```typescript
export class ExtendedSendResponseMiddleware extends SendResponseMiddleware {

   public use(@ResponseData() data: any, @Response() response: Express.Response) {

        /// place your code here ....

        
        return super.use(data, response);
    }
}

// it's hack
(MiddlewareService as any).middlewares.set(SendResponseMiddleware, {
    provide: SendResponseMiddleware, 
    useClass: ExtendedSendResponseMiddleware,
    type: 1
});
```

Maybe works ^^

**Comment by WalterLeinert** [comment]
Hi Romain,

Thank you for your proposal. I will try it tomorrow.

Retardierte, walter
