### ISSUE TITLE
Get PathParams from controller path

### ISSUE THREAD

**Issue by petervyvey** [Romakita/ts-express-decorators#63]
Hello,

Currently I am setting up a api server with express-decorators and I am trying to use something like:

@Controller('/:tenantid/projects')
export class ProjectController { 
 ...

    @Get('')
    public getAll(@PathParams('tenantid') tenantid: string): ...

But this doesn't seems to work, the param 'tenantid' is undefined. Is there a way or pattern to have my routes configured like this ?

Grtz,

Peter

**Comment by Romakita** [comment]
Hi @petervyvey,

You can see the issue #55 ;)

See you,
Romain

**Comment by petervyvey** [comment]
Hi Romain,

Got it working ... next time I will also read through the closed issues :-)

Thx
