### ISSUE TITLE
Scanning files on windows

### ISSUE THREAD

**Issue by ferquo** [Romakita/ts-express-decorators#65]
There is an issue with scanning controllers, middlewares, services etc.
The path to these folders will combine slashes and backslashes.
Ex.: 'D:\projects\example\dist/services/**/*.js'.

Because of this, this library does not work on windows environments.

**Comment by Romakita** [comment]
Hi @ferquo,

Thanks for your issue. I'll fix that ASAP.

**Comment by Romakita** [comment]
Hi @ferquo ,

Can you test  the v1.4.7-1 please ? Ask me if that work fine ^^!

See you.
Romain

**Comment by ferquo** [comment]
Hi, sorry for the late response.
I'm afraid it still not works in version 1.4.7-1.

The only way I can make it to work, is to specify the mount option in the ServerSettings decorator, and build the path as follows:

let controllerPath = Path.join(rootDir, 'controllers','**','*.js');
