### ISSUE TITLE
ts-node integration

### ISSUE THREAD

**Issue by zoubarevm** [Romakita/ts-express-decorators#67]
Hey!

I wanted to ask you guys to see if there's any way to integrate the `ts-node` module for the running of the passport project. 

I'm currently running the passport example, with the following: 
```bash
nodemon --watch '**/*.ts' --ignore '**/*.spec.ts' --ignore 'node_modules/**/*' --exec 'node_modules/.bin/ts-node' app.ts
```

The only problem I'm facing right now is with the code for the loading of the controllers / services in the `scan` method:

```typescript
        files
            .forEach(file => {

                try {
                    const exportedClasses = require(file);
                    $log.debug(`[TSED] Import file ${endpoint}:`, file);
                    nbFiles++;

                    Object
                        .keys(exportedClasses)
                        .map(clazzName => exportedClasses[clazzName])
                        .filter(clazz => Metadata.has(CONTROLLER_URL, clazz))
                        .forEach(clazz => {
                            let endpoints = Metadata.get(CONTROLLER_MOUNT_ENDPOINTS, clazz) || [];

                            endpoints.push(endpoint);

                            Metadata.set(CONTROLLER_MOUNT_ENDPOINTS, endpoints, clazz);
                        });

                } catch (er) {
                    /* istanbul ignore next */
                    $log.error(er);
                }

            });
```

The catch there is logging error to the console, but isn't propagating them further. `ts-node` will complain that a ts file couldn't be compiled, but the loading of the server will continue. As a hack, I've added:
```typescript
            catch (er) {
                /* istanbul ignore next */
                $log.error(er);
                if (er.name === 'TSError') {
                    // compilation error
                    throw er;
                }
            }
```
which seems to do the trick... but it doesn't seem to be very clean =(

I was wondering if there was anyway to add some sort of event for this exception? Something that will escalate the exception and I can catch the `TSError: ⨯ Unable to compile TypeScript` error.

Cheers,

P.S. at least in my initial tests, it seems quite a bit faster than: 
```bash
concurrently "npm run tsc:w" "nodemon app.js --ignore *.ts"
```

**Comment by Romakita** [comment]
Hi @zoubarevm,

You can add these lines to emit an event instead of throwing an error :
```typescript
catch(er) {
    if ("$onServerInitError" in this) { 
        return (<any>this).$onServerInitError(err);
    } else {
        $log.error("[TSED] HTTP Server error", err);
    }
}
```
The event will be emitted and the developer can handle this event with the $onServerInitError hook, like here:

```typescript
@ServerSetting({...})
class Server extends ServerLoader {
    $onServerInitError(err) {
         // instruction...
         if (err.name === 'TSError') {
               
         }
    }
}
```
But this solution will not stop the server initialization :/

You can test this solution and propose a pull request if you want ;)

See you

**Comment by zoubarevm** [comment]
@Romakita that could work. I guess I could throw the error from the `$onServerInitError` method. I'll try in a few.
