### ISSUE TITLE
Best was for propagating an error from db service to a client

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/ts-express-decorators#68]
Hi Roman,

Currently i'm struggeling a little bit about the right way to propagate an error e.g. got from a db service (like optimistic lock exception or duplicate entry) in a controller by means of a global middleware for error handling.
I built some custom serialization for transferring client request and response data and in addition custom exceptions (like OptimisticLockException). My problem ist that I'm not sure how to "throw" an exception the right way so it always will be handled by the global error handler and correctly be serialized to the client.

Currently I'm rejecting a custom exception in my db service, which is called from my controller but this exception is not handled in the global error handling middleware.

Do you have some hints for me?

Regards, walter

**Comment by WalterLeinert** [comment]
sorry, title should be: "Best way for propagating an error from db service to a client"

**Comment by Romakita** [comment]
Hi  @WalterLeinert,

You can throw a custom Exception (like BadRequest with ts-httpsexception).  If your exception is instance of Exception or error have a status attributs, GlobalHandler catch this and produce a response with the message and status code. Other errors, will be caught by the globalHandler but it'll produced an error 500.

So these examples works: 

```typescript
@Controller('/')
class Cltr {
   @Get('/')
   get() {
        return Promise.reject(new BadRequest("test"));
        /// OR
        throw new BadRequest("test");
        /// OR
        dbService.throwAnError(); 
        // OR
        return Promise.resolve()
           .then(() => {
                 throw new BadRequest("test");
           });
   }
}
```
To help you, I need to see your code :).

See you 
Romain

**Comment by WalterLeinert** [comment]
Hi Romain,

thanks for your reply. I have multiple layers of services:

at the lowest level I'm using knex in my abstract BaseService class to work with a DB; in my abstract controller class ControllerBase I'm using BaseService (which implemets IBaseService).

I found one issue by myself: originally the "catch((err) ..." block was missing in my code below, because I thought a possible rejection would be propagated automatically.

`export abstract class ControllerBase<T extends IEntity<TId>, TId extends IToString> extends ReadonlyController<T, TId> {
  protected static logger = getLogger(ControllerBase);

  constructor(service: IBaseService<T, TId>, tableName: string, idName: string) {
    super(service, tableName, idName);
  }
...
  protected updateInternal(
    request: IBodyRequest<T>
  ): Promise<UpdateResult<T, TId>> {
    return new Promise<UpdateResult<T, TId>>((resolve, reject) => {
      const deserializedSubject = this.deserialize<T>(request.body);
      this.service.update(request, deserializedSubject)
        .then((result) => {
          resolve(this.serialize(result));
        })
        .catch((err) => {
          reject(err);
        });
    });
  }

...
`
On the client side I'm working with angular2 and Observables and I'm using some redux-like framework and some kind of simple ORM with corresponding decorators (like @Table, @Column, ...).

Slowly I'm debugging through my code and trying to find the right error handling patterns (like Observable.throw vs. observer.error).

Do you know some good article or cookbook where these topics are explained?

Regards,
Walter

**Comment by Romakita** [comment]
You can write your method like here:
```typescript
export abstract class ControllerBase<T extends IEntity<TId>, TId extends IToString> extends ReadonlyController<T, TId> {
  protected static logger = getLogger(ControllerBase);
 
  constructor(service: IBaseService<T, TId>, tableName: string, idName: string) {
    super(service, tableName, idName);
  }
...
    protected updateInternal(
        request: IBodyRequest<T>
    ): Promise<UpdateResult<T, TId>> {
        return Promise.resolve()
            .then(() => this.deserialize<T>(request.body)
            .then(deserializedSubject => this.service.update(request, deserializedSubject)) 
            .then<UpdateResult<T, TId>>(result => this.serialize(result));
  }
}
...
```
it's just an optimization ;)

For your question, I haven't a good topics for you :/

See you,
Romain

**Comment by WalterLeinert** [comment]
Hi Romain,

thank you for the optimization hints!
My problem is solved by the solution above by adding a catch handler to every controller method. Then the exceptions are propagated to my global error middleware and serialized as expected to the client.

Regards,
Walter

**Comment by WalterLeinert** [comment]
see my last remark.
