### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by ferquo** [Romakita/ts-express-decorators#69]
I wasn't able to run unit tests, I get the following error when trying to run tests:

> mocha ".build/**/*.spec.js"

module.js:471
    throw err;
    ^

Error: Cannot find module 'ts-express-decorators/testing'

Can you help me out with this error?

**Comment by Romakita** [comment]
Hi ferquo,

I think, it's because you use the v1.4.7-1 (for the previous issues) and in this package, the testing isn't rightly bundled. Sorry.

Can  you revert to the version v1.4.6, run npm install and try again please :) ?

See you,
Romain

**Comment by ferquo** [comment]
Hi, thanks for the reply!

I've reverted to v1.4.6, and the test do work now.
I've followed the instructions from the wiki, to write tests for controllers, but injecting a fake service to a controller doesn't seem to work. (It returns the same values as the original service, and the test fails).

These are the steps that I took:
1. bootstrapped the Server on beforEach()
2. created a map (locals), set the first parameter the original service, and the second parameter is an object with the same functions as the service:
 locals.set(PersonsService, {
            getPersons: () => {
               return [
                    new Person('1test','TestFirstName1', 'TestLastName1'),
                    new Person('2test','TestFirstName2', 'TestLastName2')
                ];
            },
            getPersonById: (id: string) => {
                return new Person(id,'TestFirstName', 'TestLastName');
            }
        })
3. invoked the controller with this variable:
        const instance: PersonsController = controllerService.invoke<PersonsController>(PersonsController, locals);

When calling a method from the controller, it returns the values from the original service, and not the fake one. Am I missing something?

Thanks in advance!

**Comment by Romakita** [comment]
Hi @ferquo ;

It's fixed with v1.4.7 (without bundle bugs ;) )

**Comment by ferquo** [comment]
Thank you, I appreciate your hard work!

When is the release for v1.4.7?

**Comment by Romakita** [comment]
It's released ^^
