### ISSUE TITLE
Is there a way to get Service instance outside the controller?

### ISSUE THREAD

**Issue by RevanScript** [Romakita/ts-express-decorators#7]
In ServerLoader for example. I need to configure socket.io and oauth2orize somewhere and i don't have any idea how to do it.
Or maybe you've got plans to make something like @Configuration annotation in Spring Framework (Java)? It would be great!

P.S. Thanks for amazing library!

**Comment by RevanScript** [comment]
Ok, i see that services are initializing on startup. Everything's fine now. I thought they are initializing only when they are injected to controllers.

**Comment by Romakita** [comment]
Hello RevanScript,

Thanks for your compliments :)

Here a link to the wiki:
https://github.com/Romakita/ts-express-decorators/wiki/Class:-ServerLoader#serverloaderonready-void

You have the $onReady hook. It let you to configure your SocketIO:
```typescript
class Server extends ServerLoader implements IServerLifecycle {

    public $onReady(): void {
        console.log('Server ready');
        const io = SocketIO(this.httpServer);
        // ...

    }
}
```
For oauth2orize I never used before.

**Comment by RevanScript** [comment]
Ok, i have a question about your option. If i'll initialize socket.io in the $onReady hook, how can i use it in controllers then?

**Comment by Romakita** [comment]
I confess that I did not push the problem so far. For me the controller is here to map the Express request to your method. Socket IO use Express to bind the server but I didn't use the Express method to create endpoint. 

Do you have an example of what you would like to do with Socket IO and a controller?

**Comment by RevanScript** [comment]
I need socket.io instance, to emit messages on requests. For example: user is sending request to **/chat/message**, then we insert message into the database and emit socket.io notification to other users.

Here i wrote a little example for this case:

```typescript
@Service()
export class ChatService {

    io: SocketIO.Server; // socket.io instance
    
    constructor(public chatService: ChatService) {
        // constructor
    }

    postMessage(message: string) {
        this.chatService.postMessage(message);
        this.io.emit('message', message);
    }

}
```

**Comment by Romakita** [comment]
Ok I see :)

You can create your own SocketService like this:

```typescript
@Service()
export default class SocketService {
      static io: SocketIO.Server;

      constructor() { 
      
      }

      // Maybe work
      public emit(...args) => SocketService.io.emit(...args);

      static createServer(httpServer)  {
           SocketService.io = SocketIO(httpServer);
      }
      
}
```
Then  in your Server.ts
```typescript
import SocketService from "./services/SocketService";

class Server extends ServerLoader implements IServerLifecycle {

    public $onReady(): void {
        
          SocketService.createServer(this.httpServer);

    }
}
```
And finally, In your controller or service you can inject SocketService to emit your event.

```typescript
@Service()
export class ChatService {
    
    constructor(public chatModel: ChatModel, private socketService: SocketService) {
        // constructor
    }

    postMessage(message: string) {
        this.chatModel.insertMessage(message);
        this.socketService.emit('message', message);
    }

}
```
I think that will work :)

**Comment by RevanScript** [comment]
Yes, it's interesting idea. Thank you very much for the detailed answer! :)
