### ISSUE TITLE
[Feature] Swagger UI

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#76]
## Status
**Enhancement**

## Description
The decorators should fill the swagger documentation.

## Usage example
Example with a model:
```typescript
export class EventModel {

    @Title("iD")
    @Description("Description of event model id")
    @Example("example1", "Description example")
    @JsonProperty()
    public id: string;

    @JsonProperty()
    public startDate: Date;

    @JsonProperty()
    public endDate: Date;

    @JsonProperty("Name")
    public name: string;

    @JsonProperty({use: Task})
    public tasks: Task[];

}
```
Example with the controller:
```typescript
@Controller("/")
@Controller("/events")
export class EventCtrl {
    @Patch("/:id")
    @Responses("404", {description: "Not found"})
    patch(@Required() @BodyParams() event: EventModel): EventModel {

        if (event.id === "0" || event.id === "") {
            throw new NotFound("Not found");
        }

        return event;
    }
}
```
Example to configure swagger ui:
```typescript
import * as Express from "express";
import {$log} from "ts-log-debug";
import {ServerLoader, ServerSettings} from "ts-express-decorators";
import "ts-express-decorators/swagger";
import * as Path from "path";

const rootDir = Path.resolve(__dirname);

@ServerSettings({
    rootDir,
    port: 8000,
    swagger: {
        path: "/api-doc",
        specPath: `${rootDir}/spec/swagger.json`,  //optional
        cssPath: `${rootDir}/spec/style.css`, // optional
        showExplorer: true, //optional
        spec: require(`${rootDir}/spec/swagger.default.json`) //optional
    },
    debug: true
})
export class Server extends ServerLoader {
}
```

## Acceptance criteria
- [x] swagger.json generated by Ts.ED is valid,
- [x] All routes decorated by Ts.ED is in the swagger.json.

**Comment by Romakita** [comment]
Hi @vologab,

You can test v2.0.0-1 with swagger-ui.

To test this, you must install `swagger-ui-express` and `@types/swagger-schema-official` before run your project.

Note (migrate to v2):
- ServerLoader.isAuthenticated hooks is removed. Use ServerLoader.$onAuth hook insteadof.
- Interface IPromise is removed. Use Promise insteadof.
- Interface ICrud is removed.
- ServerLoader.AcceptMime() is removed. Use GlobalAcceptMimesMiddleware insteadof. 

See you,
Romain

**Comment by vologab** [comment]
Hi @Romakita. Thank you.
It's wonderful feature

**Comment by Romakita** [comment]
Hi @vologab ,

Here the new website documentation. I've added a doc on the swagger feature.
https://romakita.github.io/ts-express-decorators/#/tutorials/swagger

See you
Romain
