### ISSUE TITLE
run in aws lambda

### ISSUE THREAD

**Issue by vetras** [Romakita/ts-express-decorators#78]
Hi,
I am using this project for a node api that runs in AWS Lambda functions.
I run into issues while getting the glue code to work and would like to share the knowledge.

What do you think it is the best way to do this? I don't know.

Basically what I have done is to create a static method on the Server class:
```typescript
@ServerSettings({  /* ... */ })
export class Server extends ServerLoader {

/* ... other code ... */

    private static Build = (): ServerLoader => {
        let port = config.get("server.listen-port") as number || 3000;
        let server = new Server();
        server.settings.port = port;
        return server;
    }

    public static InitializeLocal = (): Promise<any> => {
        let server = Server.Build();
        return server.start();
    }

    public static InitializeLambda = (): any => {
        let server = Server.Build();
        server.start();
        return server.expressApp;
    }
}

```

and then call `InitializeLambda()` from the AWS code:

> lambda.js
```javascript
"use strict";
const app = require("./lib/server");
const awsServerlessExpress = require("aws-serverless-express");

const lambdaServer = awsServerlessExpress.createServer(app.Server.InitializeLambda());
module.exports.handler = (event, context, callback) => awsServerlessExpress.proxy(lambdaServer, event, context);

```

This is the code we set on AWS Lambda to start up our code.

When I'm running locally I just do:
> $ node local.js

where `local.js` is:
```javascript
var app = require("./.build/src/server");
app.Server.InitializeLocal();
```

Hope to hear from you!
Cheers,
vetras

**Comment by Romakita** [comment]
Hi @vetras ,

Thanks for sharing your knowledge. I'll add this to a new topics in the new documentation version.

I think you can optimize the code on ServerLoader, if the build method is only to set the port.
```typescript
@ServerSettings({ 
   port: config.get("server.listen-port") as number || 3000
})
export class Server extends ServerLoader {
/* ... other code ... */
}
```
And finally in the specifics code can be moved to your app.js and lambda.js.

`lambda.js`
```javascript
"use strict";
const Server = require("./lib/server");
const awsServerlessExpress = require("aws-serverless-express");

const server = new Server();
const lambdaServer = awsServerlessExpress.createServer(server.expressApp);

server.start();

module.exports.handler = (event, context, callback) => awsServerlessExpress.proxy(lambdaServer, event, context);
```
`local.js`
```javascript
const Server = require("./.build/src/server");
new Server().start();
```

See you and thanks your again :)
Romain

**Comment by vetras** [comment]
You are absolutely right, how have I missed that?
Many thanks.

**Comment by vetras** [comment]
I have made some small fixes on the wiki.

Since we cant do pull requests on the wiki, i followed this:
 * https://stackoverflow.com/a/11481887/797369

So, if you like, you can merge the changes from my cloned repo:
* https://github.com/vetras/ts-express-decorators-wiki
* branch: **hotfix/typos**
into your wiki.

I thought I could re-use this ticket (still open) instead of creating a new one.

Cheers!

**Comment by Romakita** [comment]
Thanks a lot @vetras, it's merged :)

Actually I work on the new documentation website (see https://github.com/Romakita/ts-express-decorators/tree/feat_refactoring_arch). After the migration, it'll be easier to contribute and propose pull request on documentation ;)

Romain

**Comment by vetras** [comment]
Hi again,

I have made some small fixes on the wiki (again).
So, if you like, you can merge the changes from my cloned repo:

 * https://github.com/vetras/ts-express-decorators-wiki
 * branch: *hotfix/typos*

into your wiki.
It's the same branch as before,

I've added a section explaining how to disable logs so that the unit tests run with/without them.

Cheers,
vertas

**Comment by Romakita** [comment]
Hi @vetras 
Thanks, I'll merge this ASAP ;)

I've just publish a new website documentation. It's more easier to contribute it now :)
In addition, I've added a tutorial https://romakita.github.io/ts-express-decorators/#/tutorials/aws from your example on AWS. If you have the time see it and check it, It will be wonderful for me ;)

See Vetras and thanks again,
Romain
