### ISSUE TITLE
Webpacking project

### ISSUE THREAD

**Issue by virus2016** [Romakita/ts-express-decorators#79]
Hi there,

Maybe this isn't an issue but I am looking to minify the generated javascript code from this framework. I was trying to load in webpack but there is a problem with the dynamic paths. 

Can someone help me out?
Many thanks,

**Comment by Romakita** [comment]
Hi @virus2016 ,

It depend how do you configured your project. 

Webpack have his own dev webserver to expose your app. So you have many approach to expose your webapp. 

The first way is to use the serve-static module for express. It'll expose all files under one or more folders. This is the quick solution ;)

Here the documentation to use serve-static with Ts.ED:
https://github.com/Romakita/ts-express-decorators/wiki/Class:-ServerLoader---Lifecycle-Hooks#serverloaderafterroutesinit-void--promise

The second solution is useful when you want separate your API node process to your webapp process. You just need to use a proxyserver to expose only one public address. In dev mode you can also use this solution with webapp and his proxy configuration.

See you ;)
Romain

**Comment by virus2016** [comment]
Hey Romain,

Thanks for getting back to me so quick! This is by far my favourite package for typescript, well done. 

I want to use you're dev server etc but when it comes to deployment, I need one bundled file with all node modules etc in there. Does that make sense? 

Thanks again

**Comment by Romakita** [comment]
Actually the best practice is to separate. You can do that (for architecture folders):
```bash
├── server
│    ├── package.json // package.json for the server
│    ├── services
│    ├── controllers
│    └── etc...
└── webapp     // your webpack app
       └── package.json
```
Or more integrated
```bash
├── package.json // package.json for the server
├── services
├── controllers
├── etc...
└── webapp     // your webpack app
        ├── dist     // the final bundle built by webpack
        ├── app     // your webapp source
        ├── node_modules
       └── package.json
```
Then you must configure the ServerLoader to expose all directory that required by your webapp when you build your bundle.

```typescript
import {ServerLoader, ServerSettings} from "ts-express-decorators";
import Path = require("path");
const rootDir = Path.resolve(__dirname)

@ServerSettings({
   rootDir,
   serveStatic: {
      "/": `${rootDir}/../webapp/dist`,  // according to the architecture choice
      "/": `${rootDir}/../webapp/node_module`  // according to the architecture choice
   }
})
export class Server extends ServerLoader {

}
```
> See https://github.com/Romakita/ts-express-decorators/wiki/Serve-static-files

Normally, it should be work fine for the production.

But for the development, I recommend you to use the proxy setting of webpack. The proxy is very useful to map the server express address to your webapp. You can see an example of the configuration for webpack:
https://github.com/webpack/webpack-dev-server/tree/master/examples/proxy-simple

I hope that all these explanation will help you ;)

See you,
Romain

**Comment by virus2016** [comment]
Hey Romain,

Thanks for explaining this. My experience with webpack is that it creates one bundled file and not multiple files.

Ultimately, I am looking to mangle and minify the js output. Are you able to create a webpack that does the above as I am really struggling with this?

Many thanks again,

**Comment by Romakita** [comment]
Hi @virus2016 ,

I'm not an expert in Webpack. Usually I use a yeoman generator or Fountain.js to scaffold the webpack project. It's very helpful, because you have some tasks already implemented like minifying and optimization of the assets and you have profile to build your app.

To answer at your question you have a short example here:
https://stackoverflow.com/questions/25956937/how-to-build-minified-and-uncompressed-bundle-with-webpack

See you,
Romain
