### ISSUE TITLE
Add support for base endpoint param

### ISSUE THREAD

**Issue by Tlahey** [Romakita/ts-express-decorators#82]
## Informations

Type | Version
---|---
Improvement|1.4.4

****

## Description
Hello, i'd like to be able to add a parameter inside my base endpoint.
Example : 
           let endPointPath : string = "/:parameter/api/rest";

And retrieve this parameter as a path parameter inside the request object (for my middlewares).
Is it possible and or recommended ?

Thank you in advance.

**Comment by Romakita** [comment]
Hello @Tlahey,

This feature is already exists with @MergeParam()  in v1.4.x. See https://romakita.github.io/ts-express-decorators/#/docs/controllers?id=merge-params

But I'm not sure if the merge params works with the global endpoint. It's an express configuration.
Can you try to add the @MergeParams on the Controller where you use the middleware ?

If you have a lot of controller where you need to add this decorator, maybe I can add a global configuration to change the behavior of all Express.Router that will be created by Ts.ED.

**Comment by Tlahey** [comment]
I my case I would like in my server contructor : 

```
constructor(){
    let endPointPath : string = "/:param/api/rest";
    this.myModulesContollers.forEach(moduleCtrl => {
        this.mount(endPointPath, moduleCtrl);
    });
}
```

In my route for example : 
  GET    │ /api/:parameter/rest/documents/:id   (/api/:parameter/rest -> endPointPath)

And my param can be found in my server middleware.

**Comment by Romakita** [comment]
MergeParams respond to this need normally. You need to annotate all Controller for that. So I already prepared a feature to change the global routers behavior.

I have a question. Why you need to loop on a module controller list ? I'm curious ^^

**Comment by Tlahey** [comment]
OK thank you !

For the loop, I start many nodeJs with docker and ts-express. I need this for the scalability, to specify the module wich I start on my server.

So I have many controllers like document / casefile / folder / email / notifications / users .... and I start 1 Docker with 1 or many nodeJs controllers.

**Comment by Romakita** [comment]
Okey I see ^^,

Maybe, I can improve, the component scan to accept a list of pattern path for an endpoint like here:

```typescript
@ServerSettings({
   "mount": {
      "/:param/rest/": [
         "${rootDir}/controllers/**/Ctrl1.js",
         "${rootDir}/controllers/**/Ctrl2.js",
         etc...
      ]
  }
}
```

No ?

**Comment by Tlahey** [comment]
Yes but I start nodeJs with parameters

```
node app.js --MODULES=documents,casefiles
node app.js --MODULES=users,documents 
```

So, all my controllers are not initialized on a specific server.
(I can add a server with only documents module if the client need more power for this particular module)

**Comment by Romakita** [comment]
It's interesting ^^. 
I thinks it's possible to get the env configuration and use it in the ServerSettings.

```typescript
@ServerSettings({
   "mount": {
      "/:param/rest/": process.env.MODULES.split(',')
  }
}
class Server extends ServerLoader {
   public mount(endpoint, moduleName) {
        // I thinks you have already override the mount method to translate your moduleName to a path. 
        const modulePath = translateModuleName(moduleName);
        return super.mount(endpoint, modulePath);
   }
}
```
So I just a proposal. Because your mechanism is very interesting ^^. It's a kind of containerization and I haven't that feature today.

**Comment by Tlahey** [comment]
It's ok for the parameter on the base endpoint but i cannot get it on my server middleware in the Express.Request.

I can parse the url (req.originalUrl) but I don't think it's the correct way.

**Comment by Romakita** [comment]
I've publish the v1.5.0 with the global routers configuration.

I see this subject. https://stackoverflow.com/questions/25319731/cannot-get-request-params-in-express-middleware

Maybe that help you.

**Comment by Romakita** [comment]
And https://github.com/expressjs/express/issues/2088

**Comment by Tlahey** [comment]
Thanks ! :)

**Comment by Tlahey** [comment]
I can not `npm install ts-express-decorator@1.5.0 ` on npm :s

**Comment by Romakita** [comment]
I've tried just now and it work. On npmjs.com, the 1.5.0 is available.

Have you an error when you run the npm install ?

**Comment by Tlahey** [comment]
```
Valid install targets:
npm ERR! notarget 0.0.1, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0-0, 1.2.0-1, 1.2.0-2, 1.2.0-3, 1.2.0-4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2
.5, 1.3.0-0, 1.3.0-1, 1.3.0-2, 1.2.6, 1.3.0-3, 1.3.0-4, 1.3.0-5, 1.3.0-6, 1.3.0-7, 1.3.0-8, 1.3.0-9, 1.3.0-10, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0-0, 1.4.0-1, 1.4.0-2, 1.4.0-3, 1.4
.0-5, 1.4.0-6, 1.4.0-7, 1.4.0-8, 1.4.0-9, 1.4.0-10, 1.4.0-11, 1.4.0-12, 1.4.0-13, 1.4.0-14, 1.4.0-15, 1.4.0-16, 1.4.0-17, 1.4.0-18, 1.3.5, 1.4.0-19, 1.4.0-20, 1.4.0-21, 1.4.0-22, 1.4.0-
23, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7-1, 1.4.8, 1.4.9-0, 1.4.9-1, 1.4.9-2, 1.4.9, 1.4.10, 2.0.0-0, 2.0.0-1, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 2.0.0-2, 1.4.15
```

**Comment by Romakita** [comment]
Ok maybe you have a cache. 
Try https://registry.npmjs.org/ts-express-decorators in your browser. Normally you'll seen the 1.5.0 version in the dist-tag.
Then try npm info ts-express-decorators. If you don't have the v1.5.0 in response, try 
```bash
 npm cache clean && npm info ts-express-decorators.
```
See you

**Comment by Tlahey** [comment]
Ok thanks :)

**Comment by Tlahey** [comment]
All it's ok with the MergeParams on my server :) 

But i have no params on my middleware =/
Even if my route have more parameters.

```
            .use((req : Express.Request, res : Express.Response, next) => {
                if( req.params.MyParam == undefined)
                    throw new BadRequest("no param");
                next();
            })
```

**Comment by Romakita** [comment]
This is the subject in this links: expressjs/express#2088

Express didn't provide the request.params in a middleware when you use the router.use() method. I can't fix that if Express didn't support it. 

You need to parse manually the params or use the router.param(), if you want to solve your problem. Actually I haven't a feature to fix your problem.

**Comment by Romakita** [comment]
I thinks this solution will be work : http://expressjs.com/en/4x/api.html#app.param

**Comment by Tlahey** [comment]
Ok, i will used the url parse for get my first parameter.

Thank you for your help :)
