### ISSUE TITLE
[Decorators] Model validation with AJV

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#85]
## Status
Improvement

## Description
As a developer, I want to be able to validate an object from a request (or object returned in the response) with the decorators when I use the converters feature.

## Issues related

#126 
#35 

## Usage Example

```typescript
export class Post {

    @Length(10, 20)
    title: string;

    @Contains("hello")
    text: string;

    @IsInt()
    @Min(0)
    @Max(10)
    rating: number;

    @IsEmail()
    email: string;

    @IsFQDN()
    site: string;

    @IsDate() // there is necessary ?
    @Required()
    createDate: Date;
}
```
> Candidate library [ajv](https://github.com/epoberezkin/ajv)

## Acceptance criteria

   - [ ] A invalid model throw a BadRequest,
   - [ ] Declare automatically a property as JsonProperty,
   - [x] Metadata should be used to fill the swagger doc.

**Comment by gunzip** [comment]
moreover the constraints (ie. https://github.com/pleerock/class-validator) should go into the json-schema of the generated swagger specs.  (as side note, https://github.com/epoberezkin/ajv > joi)

**Comment by Romakita** [comment]
I agree :)

**Comment by Romakita** [comment]
Branch https://github.com/Romakita/ts-express-decorators/tree/feat_avj
