### ISSUE TITLE
SSL example?

### ISSUE THREAD

**Issue by robgrimball** [Romakita/ts-express-decorators#86]
## Informations

Type | Version
ts-express-decorators|1.5
Question

I am trying to set up SSL for my server using some certs I've used for the previous server and it does not work.  I have the following as the configuration to the server, and know that the certs/key is loading since I can debug and see them there.  Here is the relavent code:

```
const sslCrt = fs.readFileSync(rootDir + '/../ssl/ssl.crt');
const sslKey = fs.readFileSync(rootDir + '/../ssl/ssl.key');
const sslCA = fs.readFileSync(rootDir + '/../ssl/ca.crt');

@ServerSettings({
    rootDir,
    mount: {
        '/rest': `${rootDir}/controllers/**/**.js`
    },
    httpPort: 1337,
    httpsPort: 1338,
    httpsOptions: {
        key: sslKey,
        cert: sslCrt,
        ca: sslCA,
        passphrase: 'myPassphraseTest'
    }
})
```

Unfortunately when I try to start the server, I get the following error : 

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:105:17)
    at Server (_tls_wrap.js:794:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at ServerLoader.createHttpsServer (/root/nodejs/jwt-ldap/node_modules/ts-express-decorators/src/server/server-loader.ts:112:35)
```

What I am doing seems dead simple so I wonder if there is something obvious you can see that I am doing wrong, or if you can point me to a working example which starts a HTTPS server with the relevant key/certs with ts-express-decorators.

Thanks for any help/insight!

**Comment by Romakita** [comment]
Hi @robgrimball,

Regarding this topics, http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/, it might a problem with your certificate.

I've added a new example to configure the server with HTTPS options. 
https://romakita.github.io/ts-express-decorators/#/guide 
https://github.com/Romakita/example-ts-express-decorator/tree/2.0.0/example-https

See you,
Romain

**Comment by robgrimball** [comment]
Thanks for providing the example it helped a lot.
