### ISSUE TITLE
Working Controller Test Example requested..

### ISSUE THREAD

**Issue by robgrimball** [Romakita/ts-express-decorators#87]
I an trying to write a controller test that is fairly simple but can't get the locals mocking to work as given in the examples web page.

The examples page by the way has a lot of errors in it.

I tried to look at the examples repo however for a working test with mocking of a service and could not find one.  I think this would really help myself and others.

For my specific test, it looks like the following : 

```typescript
    it('should call queryMembersInGroup',
       inject([ControllerService],
              (controllerService: ControllerService) => {
                  const locals = new Map<any, any>();

                  locals.set(LdapService, {
                      queryMembersInGroup: (groupDN: string) => {
                          return 'called!';
                      },
                  });

                  const ctrl: LdapController =
                      controllerService.invoke<LdapController>(LdapController, locals);

                  expect(!!ctrl).to.be.true;
                  expect(ctrl.queryMembersInGroup('test')).to.equal('called!');
              }));

```

The test actually fires up and runs, but fails on the final expect as the actual LdapService.queryMembersInGroup function is being called rather than the mocked one.

Just to make clear, LdapController and LdapService both have a function called queryMembersInGroup.  Obviously I am trying to mock LdapService.queryMembersInGroup and call LdapController.queryMembersInGroup(which itself calls LdapService.queryMembersInGroup with the passed parameter) in this test.

Any insight into this would be appreciated, as well as a working example in the examples repo.

Thanks again!  The great news is that I already have a microservice running well with ts-express-decorators, and am now trying to get the testing framework set up to write some tests for it.  (I know, not TDD, but I'm still learning the framework and how it works first)

**Comment by Romakita** [comment]
Hello @robgrimball ,

I've improved the example-testing. You can find a complete working example here https://github.com/Romakita/example-ts-express-decorator/blob/2.0.0/example-testing/test/units/controllers/calendars/CalendarCtrl.spec.ts

What is your version of Ts.ED ?

See you,
Romain

**Comment by robgrimball** [comment]
That example helped a lot, thanks!
