### ISSUE TITLE
Rest API Tests

### ISSUE THREAD

**Issue by claudiofaustino** [Romakita/ts-express-decorators#88]
Hi,
First of all, congratulation for this excelent project.

I am trying to write some test to my REST Api but I am not being able to make the HTTP Server run or start the routes. Is this a know bug or I am doing something wrong?

The code is as follow:
```typescript
import {HttpServer as Server} from '../src/http-server';
import {ExpressApplication} from "ts-express-decorators";
import {Done, bootstrap} from "ts-express-decorators/testing";
import {expect} from "chai";
import * as SuperTest from "supertest";
import {inject} from "ts-express-decorators/lib/testing";

describe("Rest", () => {
    // bootstrap your Server to load all endpoints before run your test
    before(bootstrap(Server));

    describe("GET /rest/calendars", () => {

        it("should do something", inject([ExpressApplication, Done], (expressApplication: ExpressApplication, done: Done) => {

            SuperTest(expressApplication).get("/api/v1/fleets/1").expect(200).end((err, response: any) => {

                if (err) {
                    throw (err);
                }

                const obj = JSON.parse(response.text);

                expect(obj).to.be.an('array');

                done();
            });
        }));
    });
});
```
With this code, the server even run...

If I change the line "before(bootstrap(Server));" to "before(bootstrap(new Server().start()));
The server start but no route is loaded.
![f1](https://user-images.githubusercontent.com/7827189/29429177-1ef4c068-8366-11e7-9060-f8454e134c83.png)

**Comment by Romakita** [comment]
Hi @claudiofaustino ,

I think, maybe you have a problem with the path to scan your controller. I see, you work on Windows and glob library has a problem with `/` and `\`.  See #65 issue.

Say me if it work ;)

See you :)

**Comment by Romakita** [comment]
Hello @claudiofaustino,

To clarify:
```typescript
before(bootstrap(Server));
```
Bootstrap will start the server silently without listening port and configure the NODE_ENV on test.

This example https://github.com/Romakita/example-ts-express-decorator/tree/2.0.0/example-testing/test/integration work fine on Linux, Mac and Windows 10. I haven't test yet on Windows 7. You can try the example on your PC and say me if it work for you.

See you,
Romain

**Comment by oehm-smith** [comment]
Hi @Romakita, I am running tests in `example-https` (I had to change the versions of `@types/sinon-chai, @types/sinon, sinon-chai and sinon` to `^3.2.2, ^7.0.0, ^3.3.0 and ^7.2.2` respectively).  The tests under `test/` that contain `before(bootstrap(Server));` DO NOT RUN.  Comment out this line and they run (though fail of course since no server is running).

This is MacOSX .  It seems to run ok under Windows.  I'll investigate first and then post a separate issue for this.

**Comment by oehm-smith** [comment]
It appears the problem is `nyc / istanbul`.  As soon as I change to calling mocha directly, the `bootstrap(server)` runs ok, the server starts and the test passes.  I won't create an issue unless you'd like me to (the code should be changed in the way I suggested, however).
