### ISSUE TITLE
[Decorator] Templating decorator (Jade, EJS, etc...)

### ISSUE THREAD

**Issue by Romakita** [Romakita/ts-express-decorators#9]
`@ResponseView(partialName)` decorator use the render express method to send the response using the template HTML (or ejs, jade, etc...). In addition, the data returned by the method, will be used by ResponseView to provide the final HTML response (or any other format).

```typescript
@Controller("/events")
export class EventCtrl {

    @Get("/:id")
    @ResponseView("eventCard")
    public get(request: Express.Request, response: Express.Response): any {
        return {startDate: new Date(), name: "MyEvent"};
    }
}
```
> eventCard => views/eventCard.html

Annotation's name is a proposal. If you have a better idea of name, tell-it !

**Comment by alexproca** [comment]
Name proposal :)

```
@Template("event.ejs")
public get(...) {...}

@Template("login.jade")
public login(...) {...}
```

**Comment by Romakita** [comment]
Template isn't not bad :) 
Extension .ejs or .jade is optional with express when we use this.app.engine('.html', require('ejs').__express);

**Comment by vincent178** [comment]
I'd like to help on this, but I don't know if I have enough time.  :)

**Comment by Romakita** [comment]
Why not :)

**Comment by alexproca** [comment]
I do not have very much experience with template engines on server side (only used ejs and compiled handlebars). And I may be wrong but I read somewhere that you can use multiple template engines at the same time and the engine will be selected by template extension. 

```
var engines = require('consolidate');
app.engine('haml', engines.haml);
app.engine('html', engines.hogan);
```

**Comment by Romakita** [comment]
Ho yes. Exactly... so extension will be provided if is necessary.

**Comment by vincent178** [comment]
https://github.com/Romakita/ts-express-decorators/pull/16

**Comment by vincent178** [comment]
Hi guys, I implement a decorator called ResponseView to support this, code review is very welcome.

Thanks,
Vincent
