### ISSUE TITLE
Are you planning to make it compatible with noImplicitAny:true and strictNullChecks:true projects?

### ISSUE THREAD

**Issue by diegovilar** [Romakita/ts-express-decorators#92]
## Description
As of the current version (2.0.10), it's not possible to use ts-express-decorators in projects with compile options `noImplicitAny: true` and/or `strictNullChecks: true`. They will not compile due to the fact that ts-express-decorators itself has lots of implicit `any`, `undefined` and `null`.

Is it on the roadmap to make all types explicit in ts-express-decorators and thus not force projects that depend on it relax said compile options?

**Comment by Romakita** [comment]
Hi @diegovilar ,

It's fixed with v2.0.11 :)

See you,
Romain

**Comment by diegovilar** [comment]
Awesome, @Romakita! I'm gonna test it right now. Thanks for the great work!
